.TH "__DRIbufferRec" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIbufferRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "unsigned \fBint\fP \fBattachment\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBname\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBpitch\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBcpp\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBflags\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 765 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "unsigned \fBint\fP __DRIbufferRec::attachment"

.PP
Définition à la ligne 766 du fichier dri_interface\&.h\&.
.SS "unsigned \fBint\fP __DRIbufferRec::cpp"

.PP
Définition à la ligne 769 du fichier dri_interface\&.h\&.
.SS "unsigned \fBint\fP __DRIbufferRec::flags"

.PP
Définition à la ligne 770 du fichier dri_interface\&.h\&.
.SS "unsigned \fBint\fP __DRIbufferRec::name"

.PP
Définition à la ligne 767 du fichier dri_interface\&.h\&.
.SS "unsigned \fBint\fP __DRIbufferRec::pitch"

.PP
Définition à la ligne 768 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
