.TH "__DRIlegacyExtensionRec" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIlegacyExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fB__DRIscreen\fP *(* \fBcreateNewScreen\fP )(\fBint\fP screen, \fBconst\fP \fB__DRIversion\fP *ddx_version, \fBconst\fP \fB__DRIversion\fP *dri_version, \fBconst\fP \fB__DRIversion\fP *drm_version, \fBconst\fP \fB__DRIframebuffer\fP *frame_buffer, \fBvoid\fP *pSAREA, \fBint\fP fd, \fBconst\fP \fB__DRIextension\fP **extensions, \fBconst\fP \fB__DRIconfig\fP ***driver_configs, \fBvoid\fP *loaderPrivate)"
.br
.ti -1c
.RI "\fB__DRIdrawable\fP *(* \fBcreateNewDrawable\fP )(\fB__DRIscreen\fP *screen, \fBconst\fP \fB__DRIconfig\fP *config, drm_drawable_t hwDrawable, \fBint\fP renderType, \fBconst\fP \fBint\fP *attrs, \fBvoid\fP *loaderPrivate)"
.br
.ti -1c
.RI "\fB__DRIcontext\fP *(* \fBcreateNewContext\fP )(\fB__DRIscreen\fP *screen, \fBconst\fP \fB__DRIconfig\fP *config, \fBint\fP render_type, \fB__DRIcontext\fP *shared, drm_context_t hwContext, \fBvoid\fP *loaderPrivate)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 676 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIlegacyExtensionRec::base"

.PP
Définition à la ligne 677 du fichier dri_interface\&.h\&.
.SS "\fB__DRIcontext\fP*(* __DRIlegacyExtensionRec::createNewContext) (\fB__DRIscreen\fP *screen, \fBconst\fP \fB__DRIconfig\fP *config, \fBint\fP render_type, \fB__DRIcontext\fP *shared, drm_context_t hwContext, \fBvoid\fP *loaderPrivate)"

.PP
Définition à la ligne 695 du fichier dri_interface\&.h\&.
.SS "\fB__DRIdrawable\fP*(* __DRIlegacyExtensionRec::createNewDrawable) (\fB__DRIscreen\fP *screen, \fBconst\fP \fB__DRIconfig\fP *config, drm_drawable_t hwDrawable, \fBint\fP renderType, \fBconst\fP \fBint\fP *attrs, \fBvoid\fP *loaderPrivate)"

.PP
Définition à la ligne 689 du fichier dri_interface\&.h\&.
.SS "\fB__DRIscreen\fP*(* __DRIlegacyExtensionRec::createNewScreen) (\fBint\fP screen, \fBconst\fP \fB__DRIversion\fP *ddx_version, \fBconst\fP \fB__DRIversion\fP *dri_version, \fBconst\fP \fB__DRIversion\fP *drm_version, \fBconst\fP \fB__DRIframebuffer\fP *frame_buffer, \fBvoid\fP *pSAREA, \fBint\fP fd, \fBconst\fP \fB__DRIextension\fP **extensions, \fBconst\fP \fB__DRIconfig\fP ***driver_configs, \fBvoid\fP *loaderPrivate)"

.PP
Définition à la ligne 679 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
