.TH "__DRI2configQueryExtensionRec" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRI2configQueryExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBint\fP(* \fBconfigQueryb\fP )(\fB__DRIscreen\fP *screen, \fBconst\fP char *var, \fBGLboolean\fP *\fBval\fP)"
.br
.ti -1c
.RI "\fBint\fP(* \fBconfigQueryi\fP )(\fB__DRIscreen\fP *screen, \fBconst\fP char *var, \fBGLint\fP *\fBval\fP)"
.br
.ti -1c
.RI "\fBint\fP(* \fBconfigQueryf\fP )(\fB__DRIscreen\fP *screen, \fBconst\fP char *var, \fBGLfloat\fP *\fBval\fP)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1165 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRI2configQueryExtensionRec::base"

.PP
Définition à la ligne 1166 du fichier dri_interface\&.h\&.
.SS "\fBint\fP(* __DRI2configQueryExtensionRec::configQueryb) (\fB__DRIscreen\fP *screen, \fBconst\fP char *var, \fBGLboolean\fP *\fBval\fP)"

.PP
Définition à la ligne 1168 du fichier dri_interface\&.h\&.
.SS "\fBint\fP(* __DRI2configQueryExtensionRec::configQueryf) (\fB__DRIscreen\fP *screen, \fBconst\fP char *var, \fBGLfloat\fP *\fBval\fP)"

.PP
Définition à la ligne 1170 du fichier dri_interface\&.h\&.
.SS "\fBint\fP(* __DRI2configQueryExtensionRec::configQueryi) (\fB__DRIscreen\fP *screen, \fBconst\fP char *var, \fBGLint\fP *\fBval\fP)"

.PP
Définition à la ligne 1169 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
