.TH "__DRIuseInvalidateExtensionRec" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIuseInvalidateExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 484 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIuseInvalidateExtensionRec::base"

.PP
Définition à la ligne 485 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
