.TH "__DRIcopySubBufferExtensionRec" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__DRIcopySubBufferExtensionRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dri_interface\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__DRIextension\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBcopySubBuffer\fP )(\fB__DRIdrawable\fP *drawable, \fBint\fP \fBx\fP, \fBint\fP \fBy\fP, \fBint\fP \fBw\fP, \fBint\fP \fBh\fP)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 135 du fichier dri_interface\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fB__DRIextension\fP __DRIcopySubBufferExtensionRec::base"

.PP
Définition à la ligne 136 du fichier dri_interface\&.h\&.
.SS "\fBvoid\fP(* __DRIcopySubBufferExtensionRec::copySubBuffer) (\fB__DRIdrawable\fP *drawable, \fBint\fP \fBx\fP, \fBint\fP \fBy\fP, \fBint\fP \fBw\fP, \fBint\fP \fBh\fP)"

.PP
Définition à la ligne 137 du fichier dri_interface\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
