.TH "__GLXdispatchConvolutionFilterHeader" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXdispatchConvolutionFilterHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_PIXEL_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_CONV_FILT_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1979 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXdispatchConvolutionFilterHeader::__GLX_CONV_FILT_HDR"

.PP
Définition à la ligne 1981 du fichier glxproto\&.h\&.
.SS "__GLXdispatchConvolutionFilterHeader::__GLX_PIXEL_HDR"

.PP
Définition à la ligne 1980 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
