.TH "__GLXcompressedTexSubImageHeader" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXcompressedTexSubImageHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_RENDER_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_COMPRESSED_TEXSUBIMAGE_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1812 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXcompressedTexSubImageHeader::__GLX_COMPRESSED_TEXSUBIMAGE_HDR"

.PP
Définition à la ligne 1814 du fichier glxproto\&.h\&.
.SS "__GLXcompressedTexSubImageHeader::__GLX_RENDER_HDR"

.PP
Définition à la ligne 1813 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
