.TH "__GLXvisualConfigRec" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXvisualConfigRec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxint\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "VisualID \fBvid\fP"
.br
.ti -1c
.RI "\fBint\fP \fBclass\fP"
.br
.ti -1c
.RI "Bool \fBrgba\fP"
.br
.ti -1c
.RI "\fBint\fP \fBredSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgreenSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBblueSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBalphaSize\fP"
.br
.ti -1c
.RI "unsigned long \fBredMask\fP"
.br
.ti -1c
.RI "unsigned long \fBgreenMask\fP"
.br
.ti -1c
.RI "unsigned long \fBblueMask\fP"
.br
.ti -1c
.RI "unsigned long \fBalphaMask\fP"
.br
.ti -1c
.RI "\fBint\fP \fBaccumRedSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBaccumGreenSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBaccumBlueSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBaccumAlphaSize\fP"
.br
.ti -1c
.RI "Bool \fBdoubleBuffer\fP"
.br
.ti -1c
.RI "Bool \fBstereo\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbufferSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdepthSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBstencilSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBauxBuffers\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlevel\fP"
.br
.ti -1c
.RI "\fBint\fP \fBvisualRating\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtransparentPixel\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtransparentRed\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtransparentGreen\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtransparentBlue\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtransparentAlpha\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtransparentIndex\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmultiSampleSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnMultiSampleBuffers\fP"
.br
.ti -1c
.RI "\fBint\fP \fBvisualSelectGroup\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 41 du fichier glxint\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP __GLXvisualConfigRec::accumAlphaSize"

.PP
Définition à la ligne 47 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::accumBlueSize"

.PP
Définition à la ligne 47 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::accumGreenSize"

.PP
Définition à la ligne 47 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::accumRedSize"

.PP
Définition à la ligne 47 du fichier glxint\&.h\&.
.SS "unsigned long __GLXvisualConfigRec::alphaMask"

.PP
Définition à la ligne 46 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::alphaSize"

.PP
Définition à la ligne 45 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::auxBuffers"

.PP
Définition à la ligne 53 du fichier glxint\&.h\&.
.SS "unsigned long __GLXvisualConfigRec::blueMask"

.PP
Définition à la ligne 46 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::blueSize"

.PP
Définition à la ligne 45 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::bufferSize"

.PP
Définition à la ligne 50 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::class"

.PP
Définition à la ligne 43 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::depthSize"

.PP
Définition à la ligne 51 du fichier glxint\&.h\&.
.SS "Bool __GLXvisualConfigRec::doubleBuffer"

.PP
Définition à la ligne 48 du fichier glxint\&.h\&.
.SS "unsigned long __GLXvisualConfigRec::greenMask"

.PP
Définition à la ligne 46 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::greenSize"

.PP
Définition à la ligne 45 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::level"

.PP
Définition à la ligne 54 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::multiSampleSize"

.PP
Définition à la ligne 61 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::nMultiSampleBuffers"

.PP
Définition à la ligne 62 du fichier glxint\&.h\&.
.SS "unsigned long __GLXvisualConfigRec::redMask"

.PP
Définition à la ligne 46 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::redSize"

.PP
Définition à la ligne 45 du fichier glxint\&.h\&.
.SS "Bool __GLXvisualConfigRec::rgba"

.PP
Définition à la ligne 44 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::stencilSize"

.PP
Définition à la ligne 52 du fichier glxint\&.h\&.
.SS "Bool __GLXvisualConfigRec::stereo"

.PP
Définition à la ligne 49 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::transparentAlpha"

.PP
Définition à la ligne 59 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::transparentBlue"

.PP
Définition à la ligne 59 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::transparentGreen"

.PP
Définition à la ligne 59 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::transparentIndex"

.PP
Définition à la ligne 60 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::transparentPixel"

.PP
Définition à la ligne 57 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::transparentRed"

.PP
Définition à la ligne 59 du fichier glxint\&.h\&.
.SS "VisualID __GLXvisualConfigRec::vid"

.PP
Définition à la ligne 42 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::visualRating"

.PP
Définition à la ligne 56 du fichier glxint\&.h\&.
.SS "\fBint\fP __GLXvisualConfigRec::visualSelectGroup"

.PP
Définition à la ligne 63 du fichier glxint\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
