.TH "__GLXrenderLargeHeader" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXrenderLargeHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_RENDER_LARGE_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1458 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXrenderLargeHeader::__GLX_RENDER_LARGE_HDR"

.PP
Définition à la ligne 1459 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
