.TH "__GLXdispatchTexImage3DHeader" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXdispatchTexImage3DHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_PIXEL_3D_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_TEXIMAGE_3D_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1641 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXdispatchTexImage3DHeader::__GLX_PIXEL_3D_HDR"

.PP
Définition à la ligne 1642 du fichier glxproto\&.h\&.
.SS "__GLXdispatchTexImage3DHeader::__GLX_TEXIMAGE_3D_HDR"

.PP
Définition à la ligne 1643 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
