.TH "__GLXdispatchDrawArraysComponentHeader" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXdispatchDrawArraysComponentHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_COMPONENT_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 2022 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXdispatchDrawArraysComponentHeader::__GLX_COMPONENT_HDR"

.PP
Définition à la ligne 2023 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
