.TH "__GLXdispatchCompressedTexSubImageHeader" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXdispatchCompressedTexSubImageHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_COMPRESSED_TEXSUBIMAGE_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1822 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXdispatchCompressedTexSubImageHeader::__GLX_COMPRESSED_TEXSUBIMAGE_HDR"

.PP
Définition à la ligne 1823 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
