.TH "__GLXdrawArraysHeader" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXdrawArraysHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_RENDER_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_DRAWARRAYS_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 2003 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXdrawArraysHeader::__GLX_DRAWARRAYS_HDR"

.PP
Définition à la ligne 2005 du fichier glxproto\&.h\&.
.SS "__GLXdrawArraysHeader::__GLX_RENDER_HDR"

.PP
Définition à la ligne 2004 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
