.TH "__GLXcompressedTexImage3DLargeHeader" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXcompressedTexImage3DLargeHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_RENDER_LARGE_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_COMPRESSED_TEXIMAGE_3D_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1856 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXcompressedTexImage3DLargeHeader::__GLX_COMPRESSED_TEXIMAGE_3D_HDR"

.PP
Définition à la ligne 1858 du fichier glxproto\&.h\&.
.SS "__GLXcompressedTexImage3DLargeHeader::__GLX_RENDER_LARGE_HDR"

.PP
Définition à la ligne 1857 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
