.TH "__GLXtexSubImage3DHeader" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXtexSubImage3DHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_RENDER_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_PIXEL_3D_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_TEXSUBIMAGE_3D_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1724 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXtexSubImage3DHeader::__GLX_PIXEL_3D_HDR"

.PP
Définition à la ligne 1726 du fichier glxproto\&.h\&.
.SS "__GLXtexSubImage3DHeader::__GLX_RENDER_HDR"

.PP
Définition à la ligne 1725 du fichier glxproto\&.h\&.
.SS "__GLXtexSubImage3DHeader::__GLX_TEXSUBIMAGE_3D_HDR"

.PP
Définition à la ligne 1727 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
