.TH "__GLXtexSubImageHeader" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXtexSubImageHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_RENDER_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_PIXEL_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_TEXSUBIMAGE_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1674 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXtexSubImageHeader::__GLX_PIXEL_HDR"

.PP
Définition à la ligne 1676 du fichier glxproto\&.h\&.
.SS "__GLXtexSubImageHeader::__GLX_RENDER_HDR"

.PP
Définition à la ligne 1675 du fichier glxproto\&.h\&.
.SS "__GLXtexSubImageHeader::__GLX_TEXSUBIMAGE_HDR"

.PP
Définition à la ligne 1677 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
