.TH "__GLXEvent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glx\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBGLXPbufferClobberEvent\fP \fBglxpbufferclobber\fP"
.br
.ti -1c
.RI "\fBGLXBufferSwapComplete\fP \fBglxbufferswapcomplete\fP"
.br
.ti -1c
.RI "long \fBpad\fP [24]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 503 du fichier glx\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBGLXBufferSwapComplete\fP __GLXEvent::glxbufferswapcomplete"

.PP
Définition à la ligne 505 du fichier glx\&.h\&.
.SS "\fBGLXPbufferClobberEvent\fP __GLXEvent::glxpbufferclobber"

.PP
Définition à la ligne 504 du fichier glx\&.h\&.
.SS "long __GLXEvent::pad[24]"

.PP
Définition à la ligne 506 du fichier glx\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
