.TH "__GLXcompressedTexImage3DHeader" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__GLXcompressedTexImage3DHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fB__GLX_RENDER_HDR\fP"
.br
.ti -1c
.RI "\fB__GLX_COMPRESSED_TEXIMAGE_3D_HDR\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1851 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "__GLXcompressedTexImage3DHeader::__GLX_COMPRESSED_TEXIMAGE_3D_HDR"

.PP
Définition à la ligne 1853 du fichier glxproto\&.h\&.
.SS "__GLXcompressedTexImage3DHeader::__GLX_RENDER_HDR"

.PP
Définition à la ligne 1852 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
