.TH "_GPU_DEVICE" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GPU_DEVICE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wglext\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "DWORD \fBcb\fP"
.br
.ti -1c
.RI "CHAR \fBDeviceName\fP [32]"
.br
.ti -1c
.RI "CHAR \fBDeviceString\fP [128]"
.br
.ti -1c
.RI "DWORD \fBFlags\fP"
.br
.ti -1c
.RI "RECT \fBrcVirtualScreen\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 438 du fichier wglext\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "DWORD _GPU_DEVICE::cb"

.PP
Définition à la ligne 439 du fichier wglext\&.h\&.
.SS "CHAR _GPU_DEVICE::DeviceName[32]"

.PP
Définition à la ligne 440 du fichier wglext\&.h\&.
.SS "CHAR _GPU_DEVICE::DeviceString[128]"

.PP
Définition à la ligne 441 du fichier wglext\&.h\&.
.SS "DWORD _GPU_DEVICE::Flags"

.PP
Définition à la ligne 442 du fichier wglext\&.h\&.
.SS "RECT _GPU_DEVICE::rcVirtualScreen"

.PP
Définition à la ligne 443 du fichier wglext\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
