.TH "Répertoire de référence de /home/wery_a/rendu/CPP/cpp_arcade/inc/lib" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /home/wery_a/rendu/CPP/cpp_arcade/inc/lib \- 
.SH SYNOPSIS
.br
.PP
.SS "Répertoires"

.in +1c
.ti -1c
.RI "répertoire \fBncurses\fP"
.br
.ti -1c
.RI "répertoire \fBopenGL\fP"
.br
.ti -1c
.RI "répertoire \fBsdl2\fP"
.br
.in -1c
