.TH "Répertoire de référence de /home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include \- 
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBbegin_code\&.h\fP"
.br
.ti -1c
.RI "fichier \fBclose_code\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_assert\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_atomic\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_audio\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_bits\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_blendmode\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_clipboard\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_config\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_cpuinfo\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_egl\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_endian\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_error\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_events\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_filesystem\&.h\fP"
.br
.RI "\fIInclude file for filesystem SDL API functions\&. \fP"
.ti -1c
.RI "fichier \fBSDL_gamecontroller\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_gesture\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_haptic\&.h\fP"
.br
.RI "\fIThe SDL Haptic subsystem allows you to control haptic (force feedback) devices\&. \fP"
.ti -1c
.RI "fichier \fBSDL_hints\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_image\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_joystick\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_keyboard\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_keycode\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_loadso\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_log\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_main\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_messagebox\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_mouse\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_mutex\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_name\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_opengl\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_opengl_glext\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_opengles\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_opengles2\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_opengles2_gl2\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_opengles2_gl2ext\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_opengles2_gl2platform\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_opengles2_khrplatform\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_pixels\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_platform\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_power\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_quit\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_rect\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_render\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_revision\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_rwops\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_scancode\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_shape\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_stdinc\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_surface\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_system\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_syswm\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_assert\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_common\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_compare\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_crc32\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_font\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_fuzzer\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_harness\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_images\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_log\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_md5\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_test_random\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_thread\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_timer\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_touch\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_ttf\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_types\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_version\&.h\fP"
.br
.ti -1c
.RI "fichier \fBSDL_video\&.h\fP"
.br
.in -1c
