.TH "Répertoire de référence de /home/wery_a/rendu/CPP/cpp_arcade/inc/lib/sdl2" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de /home/wery_a/rendu/CPP/cpp_arcade/inc/lib/sdl2 \- 
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBSdl2\&.hpp\fP"
.br
.in -1c
