.TH "_PAGE" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PAGE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <form\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "short \fBpmin\fP"
.br
.ti -1c
.RI "short \fBpmax\fP"
.br
.ti -1c
.RI "short \fBsmin\fP"
.br
.ti -1c
.RI "short \fBsmax\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 61 du fichier form\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "short _PAGE::pmax"

.PP
Définition à la ligne 63 du fichier form\&.h\&.
.SS "short _PAGE::pmin"

.PP
Définition à la ligne 62 du fichier form\&.h\&.
.SS "short _PAGE::smax"

.PP
Définition à la ligne 65 du fichier form\&.h\&.
.SS "short _PAGE::smin"

.PP
Définition à la ligne 64 du fichier form\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
