.TH "_win_st::pdat" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_win_st::pdat \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <curses\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBNCURSES_SIZE_T\fP \fB_pad_y\fP"
.br
.ti -1c
.RI "\fBNCURSES_SIZE_T\fP \fB_pad_x\fP"
.br
.ti -1c
.RI "\fBNCURSES_SIZE_T\fP \fB_pad_top\fP"
.br
.ti -1c
.RI "\fBNCURSES_SIZE_T\fP \fB_pad_left\fP"
.br
.ti -1c
.RI "\fBNCURSES_SIZE_T\fP \fB_pad_bottom\fP"
.br
.ti -1c
.RI "\fBNCURSES_SIZE_T\fP \fB_pad_right\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 452 du fichier curses\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBNCURSES_SIZE_T\fP _win_st::pdat::_pad_bottom"

.PP
Définition à la ligne 456 du fichier curses\&.h\&.
.SS "\fBNCURSES_SIZE_T\fP _win_st::pdat::_pad_left"

.PP
Définition à la ligne 455 du fichier curses\&.h\&.
.SS "\fBNCURSES_SIZE_T\fP _win_st::pdat::_pad_right"

.PP
Définition à la ligne 456 du fichier curses\&.h\&.
.SS "\fBNCURSES_SIZE_T\fP _win_st::pdat::_pad_top"

.PP
Définition à la ligne 455 du fichier curses\&.h\&.
.SS "\fBNCURSES_SIZE_T\fP _win_st::pdat::_pad_x"

.PP
Définition à la ligne 454 du fichier curses\&.h\&.
.SS "\fBNCURSES_SIZE_T\fP _win_st::pdat::_pad_y"

.PP
Définition à la ligne 454 du fichier curses\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
