.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/AComponent.hpp" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/AComponent.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Vector2\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAComponent\fP"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBComponentColor\fP { \fBBLACK\fP, \fBRED\fP, \fBGREEN\fP, \fBBLUE\fP, \fBYELLOW\fP, \fBMAGENTA\fP, \fBCYAN\fP, \fBWHITE\fP }"
.br
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBComponentColor\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIBLACK \fP\fP
.TP
\fB\fIRED \fP\fP
.TP
\fB\fIGREEN \fP\fP
.TP
\fB\fIBLUE \fP\fP
.TP
\fB\fIYELLOW \fP\fP
.TP
\fB\fIMAGENTA \fP\fP
.TP
\fB\fICYAN \fP\fP
.TP
\fB\fIWHITE \fP\fP
.PP
Définition à la ligne 16 du fichier AComponent\&.hpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
