.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/AGame.hpp" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/AGame.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stack>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'AComponent\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGame\fP"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBkeys\fP { \fBESC\fP = 1, \fBUP\fP, \fBDOWN\fP, \fBLEFT\fP, \fBRIGHT\fP, \fBKEY_0\fP, \fBKEY_1\fP, \fBKEY_2\fP, \fBKEY_3\fP, \fBKEY_4\fP, \fBKEY_5\fP, \fBKEY_6\fP, \fBKEY_7\fP, \fBKEY_8\fP, \fBKEY_9\fP }"
.br
.in -1c
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBkeys\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIESC \fP\fP
.TP
\fB\fIUP \fP\fP
.TP
\fB\fIDOWN \fP\fP
.TP
\fB\fILEFT \fP\fP
.TP
\fB\fIRIGHT \fP\fP
.TP
\fB\fIKEY_0 \fP\fP
.TP
\fB\fIKEY_1 \fP\fP
.TP
\fB\fIKEY_2 \fP\fP
.TP
\fB\fIKEY_3 \fP\fP
.TP
\fB\fIKEY_4 \fP\fP
.TP
\fB\fIKEY_5 \fP\fP
.TP
\fB\fIKEY_6 \fP\fP
.TP
\fB\fIKEY_7 \fP\fP
.TP
\fB\fIKEY_8 \fP\fP
.TP
\fB\fIKEY_9 \fP\fP
.PP
Définition à la ligne 8 du fichier AGame\&.hpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
