.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/AGame.hpp" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/AGame.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stack>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'AComponent\&.hpp'\fP
.br
\fC#include 'ArcadeSystem\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAGame\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
