.TH "alias" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alias \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tic\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBconst\fP char * \fBfrom\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBto\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBsource\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 213 du fichier tic\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBconst\fP char* alias::from"

.PP
Définition à la ligne 215 du fichier tic\&.h\&.
.SS "\fBconst\fP char* alias::source"

.PP
Définition à la ligne 217 du fichier tic\&.h\&.
.SS "\fBconst\fP char* alias::to"

.PP
Définition à la ligne 216 du fichier tic\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
