.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/Arcade.hpp" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/Arcade.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dlfcn\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'Utils\&.hpp'\fP
.br
\fC#include 'Interfaces\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBarcade::Arcade\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBarcade\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSAGE\fP   'USAGE : \&./arcade [LIB_PATH\&.so]'"
.br
.ti -1c
.RI "#define \fBERROR\fP(msg,  ret)   ({std::cerr << msg << std::endl;return (ret);})"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBSOTYPE\fP { \fBGRAPH\fP, \fBGAME\fP }"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define ERROR(msg, ret)   ({std::cerr << msg << std::endl;return (ret);})"

.PP
Définition à la ligne 20 du fichier Arcade\&.hpp\&.
.SS "#define USAGE   'USAGE : \&./arcade [LIB_PATH\&.so]'"

.PP
Définition à la ligne 19 du fichier Arcade\&.hpp\&.
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBSOTYPE\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIGRAPH \fP\fP
.TP
\fB\fIGAME \fP\fP
.PP
Définition à la ligne 17 du fichier Arcade\&.hpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
