.TH "arcade::WhereAmI" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::WhereAmI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Protocol\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBCommandType\fP \fBtype\fP"
.br
.ti -1c
.RI "uint16_t \fBlenght\fP"
.br
.ti -1c
.RI "\fBPosition\fP \fBposition\fP [0]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 53 du fichier Protocol\&.hpp\&.
.SH "Documentation des données membres"
.PP 
.SS "uint16_t arcade::WhereAmI::lenght"

.PP
Définition à la ligne 56 du fichier Protocol\&.hpp\&.
.SS "\fBPosition\fP arcade::WhereAmI::position[0]"

.PP
Définition à la ligne 57 du fichier Protocol\&.hpp\&.
.SS "\fBCommandType\fP arcade::WhereAmI::type"

.PP
Définition à la ligne 55 du fichier Protocol\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
