.TH "arcade::Position" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::Position \- The format is length, length * \fBPosition\fP quantity of TileType\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Protocol\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "uint16_t \fBx\fP"
.br
.ti -1c
.RI "uint16_t \fBy\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
The format is length, length * \fBPosition\fP quantity of TileType\&. 
.PP
Définition à la ligne 48 du fichier Protocol\&.hpp\&.
.SH "Documentation des données membres"
.PP 
.SS "uint16_t arcade::Position::x"

.PP
Définition à la ligne 50 du fichier Protocol\&.hpp\&.
.SS "uint16_t arcade::Position::y"

.PP
Définition à la ligne 51 du fichier Protocol\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
