.TH "arcade::GetMap" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::GetMap \- The format is width, height, and width * height * sizeof(TileType) quantity of TileType\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Protocol\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBCommandType\fP \fBtype\fP"
.br
.ti -1c
.RI "uint16_t \fBwidth\fP"
.br
.ti -1c
.RI "uint16_t \fBheight\fP"
.br
.ti -1c
.RI "\fBTileType\fP \fBtile\fP [0]"
.br
.in -1c
.SH "Description détaillée"
.PP 
The format is width, height, and width * height * sizeof(TileType) quantity of TileType\&. 
.PP
Définition à la ligne 40 du fichier Protocol\&.hpp\&.
.SH "Documentation des données membres"
.PP 
.SS "uint16_t arcade::GetMap::height"

.PP
Définition à la ligne 44 du fichier Protocol\&.hpp\&.
.SS "\fBTileType\fP arcade::GetMap::tile[0]"

.PP
Définition à la ligne 45 du fichier Protocol\&.hpp\&.
.SS "\fBCommandType\fP arcade::GetMap::type"

.PP
Définition à la ligne 42 du fichier Protocol\&.hpp\&.
.SS "uint16_t arcade::GetMap::width"

.PP
Définition à la ligne 43 du fichier Protocol\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
