.TH "arcade::Arcade" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arcade::Arcade \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Arcade\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBArcade\fP ()"
.br
.ti -1c
.RI "virtual \fB~Arcade\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBrun\fP (\fBconst\fP \fBstd::string\fP &graph)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinitSo\fP (\fBstd::string\fP \fBconst\fP &, \fBSOTYPE\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrefresh_lib\fP (\fBstd::string\fP \fBconst\fP &folder, \fBSOTYPE\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBclean\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 24 du fichier Arcade\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "arcade::Arcade::Arcade ()"

.PP
Définition à la ligne 3 du fichier Arcade\&.cpp\&.
.SS "arcade::Arcade::~Arcade ()\fC [virtual]\fP"

.PP
Définition à la ligne 9 du fichier Arcade\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP arcade::Arcade::clean ()"

.PP
Définition à la ligne 83 du fichier Arcade\&.cpp\&.
.SS "\fBvoid\fP arcade::Arcade::initSo (\fBstd::string\fP \fBconst\fP & name, \fBSOTYPE\fP type)"

.PP
Définition à la ligne 34 du fichier Arcade\&.cpp\&.
.SS "\fBvoid\fP arcade::Arcade::refresh_lib (\fBstd::string\fP \fBconst\fP & folder, \fBSOTYPE\fP type)"

.PP
Définition à la ligne 11 du fichier Arcade\&.cpp\&.
.SS "\fBbool\fP arcade::Arcade::run (\fBconst\fP \fBstd::string\fP & graph)"

.PP
Définition à la ligne 92 du fichier Arcade\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
