.TH "BackgroundComponent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BackgroundComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BackgroundComponent\&.hpp>\fP
.PP
Est dérivée de \fBAComponent\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBBackgroundComponent\fP (\fBVector2\fP< \fBint\fP > pos, \fBVector2\fP< \fBint\fP > \fBsize\fP, \fBComponentColor\fP \fBcolor\fP, \fBstd::string\fP \fBconst\fP &sprite2D)"
.br
.ti -1c
.RI "virtual \fB~BackgroundComponent\fP ()"
.br
.ti -1c
.RI "\fBstd::string\fP \fBconst\fP & \fBgetSprite2D\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBsetSprite2D\fP (\fBconst\fP \fBstd::string\fP &sprite2D)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 18 du fichier BackgroundComponent\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "BackgroundComponent::BackgroundComponent (\fBVector2\fP< \fBint\fP > pos, \fBVector2\fP< \fBint\fP > size, \fBComponentColor\fP color, \fBstd::string\fP \fBconst\fP & sprite2D)"

.PP
Définition à la ligne 13 du fichier BackgroundComponent\&.cpp\&.
.SS "BackgroundComponent::~BackgroundComponent ()\fC [virtual]\fP"

.PP
Définition à la ligne 19 du fichier BackgroundComponent\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBstd::string\fP \fBconst\fP & BackgroundComponent::getSprite2D () const"

.PP
Définition à la ligne 22 du fichier BackgroundComponent\&.cpp\&.
.SS "\fBvoid\fP BackgroundComponent::setSprite2D (\fBconst\fP \fBstd::string\fP & sprite2D)"

.PP
Définition à la ligne 27 du fichier BackgroundComponent\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
