.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/begin_code.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/begin_code.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_begin_code_h\fP"
.br
.ti -1c
.RI "#define \fBSDL_DEPRECATED\fP"
.br
.ti -1c
.RI "#define \fBSDL_UNUSED\fP"
.br
.ti -1c
.RI "#define \fBDECLSPEC\fP"
.br
.ti -1c
.RI "#define \fBSDLCALL\fP"
.br
.ti -1c
.RI "#define \fBSDL_INLINE\fP   inline"
.br
.ti -1c
.RI "#define \fB__inline__\fP   inline"
.br
.ti -1c
.RI "#define \fBSDL_FORCE_INLINE\fP   static \fBSDL_INLINE\fP"
.br
.ti -1c
.RI "#define \fBNULL\fP   ((\fBvoid\fP *)0)"
.br
.in -1c
.SH "Description détaillée"
.PP 
This file sets things up for C dynamic library function definitions, static inlined functions, and structures aligned at 4-byte alignment\&. If you don't like ugly C preprocessor code, don't look at this file\&. :) 
.PP
Définition dans le fichier \fBbegin_code\&.h\fP\&.
.SH "Documentation des macros"
.PP 
.SS "#define __inline__   inline"

.PP
Définition à la ligne 122 du fichier begin_code\&.h\&.
.SS "#define _begin_code_h"

.PP
Définition à la ligne 34 du fichier begin_code\&.h\&.
.SS "#define DECLSPEC"

.PP
Définition à la ligne 68 du fichier begin_code\&.h\&.
.SS "#define NULL   ((\fBvoid\fP *)0)"

.PP
Définition à la ligne 143 du fichier begin_code\&.h\&.
.SS "#define SDL_DEPRECATED"

.PP
Définition à la ligne 40 du fichier begin_code\&.h\&.
.SS "#define SDL_FORCE_INLINE   static \fBSDL_INLINE\fP"

.PP
Définition à la ligne 133 du fichier begin_code\&.h\&.
.SS "#define SDL_INLINE   inline"

.PP
Définition à la ligne 120 du fichier begin_code\&.h\&.
.SS "#define SDL_UNUSED"

.PP
Définition à la ligne 48 du fichier begin_code\&.h\&.
.SS "#define SDLCALL"

.PP
Définition à la ligne 78 du fichier begin_code\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
