.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/close_code.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/close_code.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Description détaillée"
.PP 
This file reverses the effects of begin_code\&.h and should be included after you finish any function and structure declarations in your headers 
.PP
Définition dans le fichier \fBclose_code\&.h\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
