.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/cursesf.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/cursesf.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses/cursesp\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ncurses/form\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNCursesFieldType\fP"
.br
.ti -1c
.RI "class \fBNCursesFormField\fP"
.br
.ti -1c
.RI "class \fBNCursesForm\fP"
.br
.ti -1c
.RI "class \fBNCursesUserField< T >\fP"
.br
.ti -1c
.RI "class \fBNCursesUserForm< T >\fP"
.br
.ti -1c
.RI "class \fBAlpha_Field\fP"
.br
.ti -1c
.RI "class \fBAlphanumeric_Field\fP"
.br
.ti -1c
.RI "class \fBInteger_Field\fP"
.br
.ti -1c
.RI "class \fBNumeric_Field\fP"
.br
.ti -1c
.RI "class \fBRegular_Expression_Field\fP"
.br
.ti -1c
.RI "class \fBEnumeration_Field\fP"
.br
.ti -1c
.RI "class \fBIPV4_Address_Field\fP"
.br
.ti -1c
.RI "class \fBUserDefinedFieldType\fP"
.br
.ti -1c
.RI "class \fBUserDefinedFieldType_With_Choice\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fB_nc_xx_frm_init\fP (\fBFORM\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_nc_xx_frm_term\fP (\fBFORM\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_nc_xx_fld_init\fP (\fBFORM\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_nc_xx_fld_term\fP (\fBFORM\fP *)"
.br
.ti -1c
.RI "\fBbool\fP \fB_nc_xx_fld_fcheck\fP (\fBFIELD\fP *, \fBconst\fP \fBvoid\fP *)"
.br
.ti -1c
.RI "\fBbool\fP \fB_nc_xx_fld_ccheck\fP (\fBint\fP \fBc\fP, \fBconst\fP \fBvoid\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP * \fB_nc_xx_fld_makearg\fP (\fBva_list\fP *)"
.br
.ti -1c
.RI "\fBbool\fP \fB_nc_xx_next_choice\fP (\fBFIELD\fP *, \fBconst\fP \fBvoid\fP *)"
.br
.ti -1c
.RI "\fBbool\fP \fB_nc_xx_prev_choice\fP (\fBFIELD\fP *, \fBconst\fP \fBvoid\fP *)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class \fBNCURSES_IMPEXP\fP \fBNCursesFormField\fP"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "\fBbool\fP _nc_xx_fld_ccheck (\fBint\fP c, \fBconst\fP \fBvoid\fP *)"

.SS "\fBbool\fP _nc_xx_fld_fcheck (\fBFIELD\fP *, \fBconst\fP \fBvoid\fP *)"

.SS "\fBvoid\fP _nc_xx_fld_init (\fBFORM\fP *)"

.SS "\fBvoid\fP* _nc_xx_fld_makearg (\fBva_list\fP *)"

.SS "\fBvoid\fP _nc_xx_fld_term (\fBFORM\fP *)"

.SS "\fBvoid\fP _nc_xx_frm_init (\fBFORM\fP *)"

.SS "\fBvoid\fP _nc_xx_frm_term (\fBFORM\fP *)"

.SS "\fBbool\fP _nc_xx_next_choice (\fBFIELD\fP *, \fBconst\fP \fBvoid\fP *)"

.SS "\fBbool\fP _nc_xx_prev_choice (\fBFIELD\fP *, \fBconst\fP \fBvoid\fP *)"

.SH "Documentation des variables"
.PP 
.SS "class \fBNCURSES_IMPEXP\fP \fBNCursesFormField\fP"

.PP
Définition à la ligne 53 du fichier cursesf\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
