.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/cursesm.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/cursesm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses/cursesp\&.h>\fP
.br
\fC#include <ncurses/menu\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNCursesMenuItem\fP"
.br
.ti -1c
.RI "class \fBNCursesMenuCallbackItem\fP"
.br
.ti -1c
.RI "class \fBNCursesMenu\fP"
.br
.ti -1c
.RI "class \fBNCursesUserItem< T >\fP"
.br
.ti -1c
.RI "class \fBNCursesUserMenu< T >\fP"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef \fBbool\fP \fBITEMCALLBACK\fP(\fBNCursesMenuItem\fP &)"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fB_nc_xx_mnu_init\fP (\fBMENU\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_nc_xx_mnu_term\fP (\fBMENU\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_nc_xx_itm_init\fP (\fBMENU\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_nc_xx_itm_term\fP (\fBMENU\fP *)"
.br
.in -1c
.SH "Documentation des définitions de type"
.PP 
.SS "typedef \fBbool\fP ITEMCALLBACK(\fBNCursesMenuItem\fP &)"

.PP
Définition à la ligne 150 du fichier cursesm\&.h\&.
.SH "Documentation des fonctions"
.PP 
.SS "\fBvoid\fP _nc_xx_itm_init (\fBMENU\fP *)"

.SS "\fBvoid\fP _nc_xx_itm_term (\fBMENU\fP *)"

.SS "\fBvoid\fP _nc_xx_mnu_init (\fBMENU\fP *)"

.SS "\fBvoid\fP _nc_xx_mnu_term (\fBMENU\fP *)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
