.TH "Enumeration_Field" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enumeration_Field \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursesf\&.h>\fP
.PP
Est dérivée de \fBNCursesFieldType\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBEnumeration_Field\fP (\fBconst\fP char *enums[], \fBbool\fP case_sens=\fBFALSE\fP, \fBbool\fP non_unique=\fBFALSE\fP)"
.br
.ti -1c
.RI "\fBEnumeration_Field\fP & \fBoperator=\fP (\fBconst\fP \fBEnumeration_Field\fP &rhs)"
.br
.ti -1c
.RI "\fBEnumeration_Field\fP (\fBconst\fP \fBEnumeration_Field\fP &rhs)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 836 du fichier cursesf\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Enumeration_Field::Enumeration_Field (\fBconst\fP char * enums[], \fBbool\fP case_sens = \fC\fBFALSE\fP\fP, \fBbool\fP non_unique = \fC\fBFALSE\fP\fP)\fC [inline]\fP"

.PP
Définition à la ligne 848 du fichier cursesf\&.h\&.
.SS "Enumeration_Field::Enumeration_Field (\fBconst\fP \fBEnumeration_Field\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 866 du fichier cursesf\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBEnumeration_Field\fP& Enumeration_Field::operator= (\fBconst\fP \fBEnumeration_Field\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 857 du fichier cursesf\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
