.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/eti.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/eti.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBE_OK\fP   (0)"
.br
.ti -1c
.RI "#define \fBE_SYSTEM_ERROR\fP   (\-1)"
.br
.ti -1c
.RI "#define \fBE_BAD_ARGUMENT\fP   (\-2)"
.br
.ti -1c
.RI "#define \fBE_POSTED\fP   (\-3)"
.br
.ti -1c
.RI "#define \fBE_CONNECTED\fP   (\-4)"
.br
.ti -1c
.RI "#define \fBE_BAD_STATE\fP   (\-5)"
.br
.ti -1c
.RI "#define \fBE_NO_ROOM\fP   (\-6)"
.br
.ti -1c
.RI "#define \fBE_NOT_POSTED\fP   (\-7)"
.br
.ti -1c
.RI "#define \fBE_UNKNOWN_COMMAND\fP   (\-8)"
.br
.ti -1c
.RI "#define \fBE_NO_MATCH\fP   (\-9)"
.br
.ti -1c
.RI "#define \fBE_NOT_SELECTABLE\fP   (\-10)"
.br
.ti -1c
.RI "#define \fBE_NOT_CONNECTED\fP   (\-11)"
.br
.ti -1c
.RI "#define \fBE_REQUEST_DENIED\fP   (\-12)"
.br
.ti -1c
.RI "#define \fBE_INVALID_FIELD\fP   (\-13)"
.br
.ti -1c
.RI "#define \fBE_CURRENT\fP   (\-14)"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define E_BAD_ARGUMENT   (\-2)"

.PP
Définition à la ligne 40 du fichier eti\&.h\&.
.SS "#define E_BAD_STATE   (\-5)"

.PP
Définition à la ligne 43 du fichier eti\&.h\&.
.SS "#define E_CONNECTED   (\-4)"

.PP
Définition à la ligne 42 du fichier eti\&.h\&.
.SS "#define E_CURRENT   (\-14)"

.PP
Définition à la ligne 52 du fichier eti\&.h\&.
.SS "#define E_INVALID_FIELD   (\-13)"

.PP
Définition à la ligne 51 du fichier eti\&.h\&.
.SS "#define E_NO_MATCH   (\-9)"

.PP
Définition à la ligne 47 du fichier eti\&.h\&.
.SS "#define E_NO_ROOM   (\-6)"

.PP
Définition à la ligne 44 du fichier eti\&.h\&.
.SS "#define E_NOT_CONNECTED   (\-11)"

.PP
Définition à la ligne 49 du fichier eti\&.h\&.
.SS "#define E_NOT_POSTED   (\-7)"

.PP
Définition à la ligne 45 du fichier eti\&.h\&.
.SS "#define E_NOT_SELECTABLE   (\-10)"

.PP
Définition à la ligne 48 du fichier eti\&.h\&.
.SS "#define E_OK   (0)"

.PP
Définition à la ligne 38 du fichier eti\&.h\&.
.SS "#define E_POSTED   (\-3)"

.PP
Définition à la ligne 41 du fichier eti\&.h\&.
.SS "#define E_REQUEST_DENIED   (\-12)"

.PP
Définition à la ligne 50 du fichier eti\&.h\&.
.SS "#define E_SYSTEM_ERROR   (\-1)"

.PP
Définition à la ligne 39 du fichier eti\&.h\&.
.SS "#define E_UNKNOWN_COMMAND   (\-8)"

.PP
Définition à la ligne 46 du fichier eti\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
