.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/Games.hpp" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/Games.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Snake\&.hpp'\fP
.br

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
