.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/openGL/include/internal/glcore.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/openGL/include/internal/glcore.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__GLcontextModesRec\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGL_CORE_SGI\fP   1"
.br
.ti -1c
.RI "#define \fBGL_CORE_MESA\fP   2"
.br
.ti -1c
.RI "#define \fBGL_CORE_APPLE\fP   4"
.br
.ti -1c
.RI "#define \fBGL_CORE_WINDOWS\fP   8"
.br
.ti -1c
.RI "#define \fBGLX_NONE\fP   0x8000"
.br
.ti -1c
.RI "#define \fBGLX_SLOW_CONFIG\fP   0x8001"
.br
.ti -1c
.RI "#define \fBGLX_TRUE_COLOR\fP   0x8002"
.br
.ti -1c
.RI "#define \fBGLX_DIRECT_COLOR\fP   0x8003"
.br
.ti -1c
.RI "#define \fBGLX_PSEUDO_COLOR\fP   0x8004"
.br
.ti -1c
.RI "#define \fBGLX_STATIC_COLOR\fP   0x8005"
.br
.ti -1c
.RI "#define \fBGLX_GRAY_SCALE\fP   0x8006"
.br
.ti -1c
.RI "#define \fBGLX_STATIC_GRAY\fP   0x8007"
.br
.ti -1c
.RI "#define \fBGLX_TRANSPARENT_RGB\fP   0x8008"
.br
.ti -1c
.RI "#define \fBGLX_TRANSPARENT_INDEX\fP   0x8009"
.br
.ti -1c
.RI "#define \fBGLX_NON_CONFORMANT_CONFIG\fP   0x800D"
.br
.ti -1c
.RI "#define \fBGLX_SWAP_EXCHANGE_OML\fP   0x8061"
.br
.ti -1c
.RI "#define \fBGLX_SWAP_COPY_OML\fP   0x8062"
.br
.ti -1c
.RI "#define \fBGLX_SWAP_UNDEFINED_OML\fP   0x8063"
.br
.ti -1c
.RI "#define \fBGLX_DONT_CARE\fP   0xFFFFFFFF"
.br
.ti -1c
.RI "#define \fBGLX_RGBA_BIT\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBGLX_COLOR_INDEX_BIT\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBGLX_WINDOW_BIT\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBGLX_PIXMAP_BIT\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBGLX_PBUFFER_BIT\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBGLX_BIND_TO_TEXTURE_RGB_EXT\fP   0x20D0"
.br
.ti -1c
.RI "#define \fBGLX_BIND_TO_TEXTURE_RGBA_EXT\fP   0x20D1"
.br
.ti -1c
.RI "#define \fBGLX_BIND_TO_MIPMAP_TEXTURE_EXT\fP   0x20D2"
.br
.ti -1c
.RI "#define \fBGLX_BIND_TO_TEXTURE_TARGETS_EXT\fP   0x20D3"
.br
.ti -1c
.RI "#define \fBGLX_Y_INVERTED_EXT\fP   0x20D4"
.br
.ti -1c
.RI "#define \fBGLX_TEXTURE_1D_BIT_EXT\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBGLX_TEXTURE_2D_BIT_EXT\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBGLX_TEXTURE_RECTANGLE_BIT_EXT\fP   0x00000004"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct __GLcontextRec \fB__GLcontext\fP"
.br
.ti -1c
.RI "typedef struct \fB__GLcontextModesRec\fP \fB__GLcontextModes\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define GL_CORE_APPLE   4"

.PP
Définition à la ligne 40 du fichier glcore\&.h\&.
.SS "#define GL_CORE_MESA   2"

.PP
Définition à la ligne 39 du fichier glcore\&.h\&.
.SS "#define GL_CORE_SGI   1"

.PP
Définition à la ligne 38 du fichier glcore\&.h\&.
.SS "#define GL_CORE_WINDOWS   8"

.PP
Définition à la ligne 41 du fichier glcore\&.h\&.
.SS "#define GLX_BIND_TO_MIPMAP_TEXTURE_EXT   0x20D2"

.PP
Définition à la ligne 173 du fichier glcore\&.h\&.
.SS "#define GLX_BIND_TO_TEXTURE_RGB_EXT   0x20D0"

.PP
Définition à la ligne 171 du fichier glcore\&.h\&.
.SS "#define GLX_BIND_TO_TEXTURE_RGBA_EXT   0x20D1"

.PP
Définition à la ligne 172 du fichier glcore\&.h\&.
.SS "#define GLX_BIND_TO_TEXTURE_TARGETS_EXT   0x20D3"

.PP
Définition à la ligne 174 du fichier glcore\&.h\&.
.SS "#define GLX_COLOR_INDEX_BIT   0x00000002"

.PP
Définition à la ligne 166 du fichier glcore\&.h\&.
.SS "#define GLX_DIRECT_COLOR   0x8003"

.PP
Définition à la ligne 151 du fichier glcore\&.h\&.
.SS "#define GLX_DONT_CARE   0xFFFFFFFF"

.PP
Définition à la ligne 163 du fichier glcore\&.h\&.
.SS "#define GLX_GRAY_SCALE   0x8006"

.PP
Définition à la ligne 154 du fichier glcore\&.h\&.
.SS "#define GLX_NON_CONFORMANT_CONFIG   0x800D"

.PP
Définition à la ligne 158 du fichier glcore\&.h\&.
.SS "#define GLX_NONE   0x8000"

.PP
Définition à la ligne 148 du fichier glcore\&.h\&.
.SS "#define GLX_PBUFFER_BIT   0x00000004"

.PP
Définition à la ligne 169 du fichier glcore\&.h\&.
.SS "#define GLX_PIXMAP_BIT   0x00000002"

.PP
Définition à la ligne 168 du fichier glcore\&.h\&.
.SS "#define GLX_PSEUDO_COLOR   0x8004"

.PP
Définition à la ligne 152 du fichier glcore\&.h\&.
.SS "#define GLX_RGBA_BIT   0x00000001"

.PP
Définition à la ligne 165 du fichier glcore\&.h\&.
.SS "#define GLX_SLOW_CONFIG   0x8001"

.PP
Définition à la ligne 149 du fichier glcore\&.h\&.
.SS "#define GLX_STATIC_COLOR   0x8005"

.PP
Définition à la ligne 153 du fichier glcore\&.h\&.
.SS "#define GLX_STATIC_GRAY   0x8007"

.PP
Définition à la ligne 155 du fichier glcore\&.h\&.
.SS "#define GLX_SWAP_COPY_OML   0x8062"

.PP
Définition à la ligne 160 du fichier glcore\&.h\&.
.SS "#define GLX_SWAP_EXCHANGE_OML   0x8061"

.PP
Définition à la ligne 159 du fichier glcore\&.h\&.
.SS "#define GLX_SWAP_UNDEFINED_OML   0x8063"

.PP
Définition à la ligne 161 du fichier glcore\&.h\&.
.SS "#define GLX_TEXTURE_1D_BIT_EXT   0x00000001"

.PP
Définition à la ligne 177 du fichier glcore\&.h\&.
.SS "#define GLX_TEXTURE_2D_BIT_EXT   0x00000002"

.PP
Définition à la ligne 178 du fichier glcore\&.h\&.
.SS "#define GLX_TEXTURE_RECTANGLE_BIT_EXT   0x00000004"

.PP
Définition à la ligne 179 du fichier glcore\&.h\&.
.SS "#define GLX_TRANSPARENT_INDEX   0x8009"

.PP
Définition à la ligne 157 du fichier glcore\&.h\&.
.SS "#define GLX_TRANSPARENT_RGB   0x8008"

.PP
Définition à la ligne 156 du fichier glcore\&.h\&.
.SS "#define GLX_TRUE_COLOR   0x8002"

.PP
Définition à la ligne 150 du fichier glcore\&.h\&.
.SS "#define GLX_WINDOW_BIT   0x00000001"

.PP
Définition à la ligne 167 du fichier glcore\&.h\&.
.SS "#define GLX_Y_INVERTED_EXT   0x20D4"

.PP
Définition à la ligne 175 du fichier glcore\&.h\&.
.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct __GLcontextRec \fB__GLcontext\fP"

.PP
Définition à la ligne 43 du fichier glcore\&.h\&.
.SS "typedef struct \fB__GLcontextModesRec\fP  \fB__GLcontextModes\fP"
Mode and limit information for a context\&. This information is kept around in the context so that values can be used during command execution, and for returning information about the context to the application\&.
.PP
Instances of this structure are shared by the driver and the loader\&. To maintain binary compatability, new fields \fBmust\fP be added only to the end of the structure\&.
.PP
\fBVoir également:\fP
.RS 4
_gl_context_modes_create 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
