.TH "GLXBufferSwapComplete" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXBufferSwapComplete \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glx\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBint\fP \fBtype\fP"
.br
.ti -1c
.RI "unsigned long \fBserial\fP"
.br
.ti -1c
.RI "Bool \fBsend_event\fP"
.br
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP \fBdrawable\fP"
.br
.ti -1c
.RI "\fBint\fP \fBevent_type\fP"
.br
.ti -1c
.RI "int64_t \fBust\fP"
.br
.ti -1c
.RI "int64_t \fBmsc\fP"
.br
.ti -1c
.RI "int64_t \fBsbc\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 491 du fichier glx\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "Display* GLXBufferSwapComplete::display"

.PP
Définition à la ligne 495 du fichier glx\&.h\&.
.SS "\fBGLXDrawable\fP GLXBufferSwapComplete::drawable"

.PP
Définition à la ligne 496 du fichier glx\&.h\&.
.SS "\fBint\fP GLXBufferSwapComplete::event_type"

.PP
Définition à la ligne 497 du fichier glx\&.h\&.
.SS "int64_t GLXBufferSwapComplete::msc"

.PP
Définition à la ligne 499 du fichier glx\&.h\&.
.SS "int64_t GLXBufferSwapComplete::sbc"

.PP
Définition à la ligne 500 du fichier glx\&.h\&.
.SS "Bool GLXBufferSwapComplete::send_event"

.PP
Définition à la ligne 494 du fichier glx\&.h\&.
.SS "unsigned long GLXBufferSwapComplete::serial"

.PP
Définition à la ligne 493 du fichier glx\&.h\&.
.SS "\fBint\fP GLXBufferSwapComplete::type"

.PP
Définition à la ligne 492 du fichier glx\&.h\&.
.SS "int64_t GLXBufferSwapComplete::ust"

.PP
Définition à la ligne 498 du fichier glx\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
