.TH "GLXBindSwapBarrierSGIX" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXBindSwapBarrierSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 unused \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP drawable \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBbarrier\fP \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1120 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXBindSwapBarrierSGIX::B16"

.PP
Définition à la ligne 1123 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXBindSwapBarrierSGIX::B32"

.PP
Définition à la ligne 1124 du fichier glxproto\&.h\&.
.SS "CARD32 unused GLXBindSwapBarrierSGIX::B32"

.PP
Définition à la ligne 1125 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP drawable GLXBindSwapBarrierSGIX::B32"

.PP
Définition à la ligne 1126 du fichier glxproto\&.h\&.
.SS "CARD32 \fBbarrier\fP GLXBindSwapBarrierSGIX::B32"

.PP
Définition à la ligne 1127 du fichier glxproto\&.h\&.
.SS "CARD8 GLXBindSwapBarrierSGIX::glxCode"

.PP
Définition à la ligne 1122 du fichier glxproto\&.h\&.
.SS "CARD8 GLXBindSwapBarrierSGIX::reqType"

.PP
Définition à la ligne 1121 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
