.TH "GLXCreatePbuffer" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCreatePbuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXFBConfigID\fP fbconfig \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXPbuffer\fP pbuffer \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numAttribs \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 486 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCreatePbuffer::B16"

.PP
Définition à la ligne 489 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXCreatePbuffer::B32"

.PP
Définition à la ligne 490 du fichier glxproto\&.h\&.
.SS "\fBGLXFBConfigID\fP fbconfig GLXCreatePbuffer::B32"

.PP
Définition à la ligne 491 du fichier glxproto\&.h\&.
.SS "\fBGLXPbuffer\fP pbuffer GLXCreatePbuffer::B32"

.PP
Définition à la ligne 492 du fichier glxproto\&.h\&.
.SS "CARD32 numAttribs GLXCreatePbuffer::B32"

.PP
Définition à la ligne 493 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreatePbuffer::glxCode"

.PP
Définition à la ligne 488 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreatePbuffer::reqType"

.PP
Définition à la ligne 487 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
