.TH "GLXCopyContext" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCopyContext \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP \fBsource\fP \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP dest \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBmask\fP \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 260 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCopyContext::B16"

.PP
Définition à la ligne 263 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP \fBsource\fP GLXCopyContext::B32"

.PP
Définition à la ligne 264 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP dest GLXCopyContext::B32"

.PP
Définition à la ligne 265 du fichier glxproto\&.h\&.
.SS "CARD32 \fBmask\fP GLXCopyContext::B32"

.PP
Définition à la ligne 266 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag GLXCopyContext::B32"

.PP
Définition à la ligne 267 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCopyContext::glxCode"

.PP
Définition à la ligne 262 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCopyContext::reqType"

.PP
Définition à la ligne 261 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
