.TH "GLXClientInfo" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXClientInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 major \fBB32\fP"
.br
.ti -1c
.RI "CARD32 minor \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numbytes \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 390 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXClientInfo::B16"

.PP
Définition à la ligne 393 du fichier glxproto\&.h\&.
.SS "CARD32 major GLXClientInfo::B32"

.PP
Définition à la ligne 394 du fichier glxproto\&.h\&.
.SS "CARD32 minor GLXClientInfo::B32"

.PP
Définition à la ligne 395 du fichier glxproto\&.h\&.
.SS "CARD32 numbytes GLXClientInfo::B32"

.PP
Définition à la ligne 396 du fichier glxproto\&.h\&.
.SS "CARD8 GLXClientInfo::glxCode"

.PP
Définition à la ligne 392 du fichier glxproto\&.h\&.
.SS "CARD8 GLXClientInfo::reqType"

.PP
Définition à la ligne 391 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
