.TH "GLXCreateGLXPixmapWithConfigSGIX" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCreateGLXPixmapWithConfigSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXFBConfigID\fP fbconfig \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pixmap \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXPixmap\fP glxpixmap \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1014 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCreateGLXPixmapWithConfigSGIX::B16"

.PP
Définition à la ligne 1017 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXCreateGLXPixmapWithConfigSGIX::B32"

.PP
Définition à la ligne 1018 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXCreateGLXPixmapWithConfigSGIX::B32"

.PP
Définition à la ligne 1019 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXCreateGLXPixmapWithConfigSGIX::B32"

.PP
Définition à la ligne 1020 du fichier glxproto\&.h\&.
.SS "\fBGLXFBConfigID\fP fbconfig GLXCreateGLXPixmapWithConfigSGIX::B32"

.PP
Définition à la ligne 1021 du fichier glxproto\&.h\&.
.SS "CARD32 pixmap GLXCreateGLXPixmapWithConfigSGIX::B32"

.PP
Définition à la ligne 1022 du fichier glxproto\&.h\&.
.SS "\fBGLXPixmap\fP glxpixmap GLXCreateGLXPixmapWithConfigSGIX::B32"

.PP
Définition à la ligne 1023 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateGLXPixmapWithConfigSGIX::glxCode"

.PP
Définition à la ligne 1016 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateGLXPixmapWithConfigSGIX::reqType"

.PP
Définition à la ligne 1015 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
