.TH "GLXChangeDrawableAttributesSGIX" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXChangeDrawableAttributesSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP drawable \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numAttribs \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1061 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXChangeDrawableAttributesSGIX::B16"

.PP
Définition à la ligne 1064 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXChangeDrawableAttributesSGIX::B32"

.PP
Définition à la ligne 1065 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXChangeDrawableAttributesSGIX::B32"

.PP
Définition à la ligne 1066 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP drawable GLXChangeDrawableAttributesSGIX::B32"

.PP
Définition à la ligne 1067 du fichier glxproto\&.h\&.
.SS "CARD32 numAttribs GLXChangeDrawableAttributesSGIX::B32"

.PP
Définition à la ligne 1068 du fichier glxproto\&.h\&.
.SS "CARD8 GLXChangeDrawableAttributesSGIX::glxCode"

.PP
Définition à la ligne 1063 du fichier glxproto\&.h\&.
.SS "CARD8 GLXChangeDrawableAttributesSGIX::reqType"

.PP
Définition à la ligne 1062 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
