.TH "GLXCreatePixmap" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCreatePixmap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXFBConfigID\fP fbconfig \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pixmap \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXPixmap\fP glxpixmap \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numAttribs \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 416 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCreatePixmap::B16"

.PP
Définition à la ligne 419 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXCreatePixmap::B32"

.PP
Définition à la ligne 420 du fichier glxproto\&.h\&.
.SS "\fBGLXFBConfigID\fP fbconfig GLXCreatePixmap::B32"

.PP
Définition à la ligne 421 du fichier glxproto\&.h\&.
.SS "CARD32 pixmap GLXCreatePixmap::B32"

.PP
Définition à la ligne 422 du fichier glxproto\&.h\&.
.SS "\fBGLXPixmap\fP glxpixmap GLXCreatePixmap::B32"

.PP
Définition à la ligne 423 du fichier glxproto\&.h\&.
.SS "CARD32 numAttribs GLXCreatePixmap::B32"

.PP
Définition à la ligne 424 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreatePixmap::glxCode"

.PP
Définition à la ligne 418 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreatePixmap::reqType"

.PP
Définition à la ligne 417 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
