.TH "GLXChangeDrawableAttributes" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXChangeDrawableAttributes \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP drawable \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numAttribs \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 523 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXChangeDrawableAttributes::B16"

.PP
Définition à la ligne 526 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP drawable GLXChangeDrawableAttributes::B32"

.PP
Définition à la ligne 527 du fichier glxproto\&.h\&.
.SS "CARD32 numAttribs GLXChangeDrawableAttributes::B32"

.PP
Définition à la ligne 528 du fichier glxproto\&.h\&.
.SS "CARD8 GLXChangeDrawableAttributes::glxCode"

.PP
Définition à la ligne 525 du fichier glxproto\&.h\&.
.SS "CARD8 GLXChangeDrawableAttributes::reqType"

.PP
Définition à la ligne 524 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
