.TH "GLXCreateContextWithConfigSGIX" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCreateContextWithConfigSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP context \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXFBConfigID\fP fbconfig \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBrenderType\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP shareList \fBB32\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBisDirect\fP"
.br
.ti -1c
.RI "CARD8 \fBreserved1\fP"
.br
.ti -1c
.RI "CARD16 reserved2 \fBB16\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 993 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCreateContextWithConfigSGIX::B16"

.PP
Définition à la ligne 996 du fichier glxproto\&.h\&.
.SS "CARD16 reserved2 GLXCreateContextWithConfigSGIX::B16"

.PP
Définition à la ligne 1006 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXCreateContextWithConfigSGIX::B32"

.PP
Définition à la ligne 997 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXCreateContextWithConfigSGIX::B32"

.PP
Définition à la ligne 998 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP context GLXCreateContextWithConfigSGIX::B32"

.PP
Définition à la ligne 999 du fichier glxproto\&.h\&.
.SS "\fBGLXFBConfigID\fP fbconfig GLXCreateContextWithConfigSGIX::B32"

.PP
Définition à la ligne 1000 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXCreateContextWithConfigSGIX::B32"

.PP
Définition à la ligne 1001 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP shareList GLXCreateContextWithConfigSGIX::B32"

.PP
Définition à la ligne 1003 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateContextWithConfigSGIX::glxCode"

.PP
Définition à la ligne 995 du fichier glxproto\&.h\&.
.SS "\fBBOOL\fP GLXCreateContextWithConfigSGIX::isDirect"

.PP
Définition à la ligne 1004 du fichier glxproto\&.h\&.
.SS "CARD32 GLXCreateContextWithConfigSGIX::renderType"

.PP
Définition à la ligne 1002 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateContextWithConfigSGIX::reqType"

.PP
Définition à la ligne 994 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateContextWithConfigSGIX::reserved1"

.PP
Définition à la ligne 1005 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
