.TH "GLXCreateWindow" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCreateWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXFBConfigID\fP fbconfig \fBB32\fP"
.br
.ti -1c
.RI "CARD32 window \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXWindow\fP glxwindow \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numAttribs \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 536 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCreateWindow::B16"

.PP
Définition à la ligne 539 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXCreateWindow::B32"

.PP
Définition à la ligne 540 du fichier glxproto\&.h\&.
.SS "\fBGLXFBConfigID\fP fbconfig GLXCreateWindow::B32"

.PP
Définition à la ligne 541 du fichier glxproto\&.h\&.
.SS "CARD32 window GLXCreateWindow::B32"

.PP
Définition à la ligne 542 du fichier glxproto\&.h\&.
.SS "\fBGLXWindow\fP glxwindow GLXCreateWindow::B32"

.PP
Définition à la ligne 543 du fichier glxproto\&.h\&.
.SS "CARD32 numAttribs GLXCreateWindow::B32"

.PP
Définition à la ligne 544 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateWindow::glxCode"

.PP
Définition à la ligne 538 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateWindow::reqType"

.PP
Définition à la ligne 537 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
