.TH "GLXCreateContextAttribsARB" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCreateContextAttribsARB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP context \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXFBConfigID\fP fbconfig \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBscreen\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP shareList \fBB32\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBisDirect\fP"
.br
.ti -1c
.RI "CARD8 \fBreserved1\fP"
.br
.ti -1c
.RI "CARD16 reserved2 \fBB16\fP"
.br
.ti -1c
.RI "CARD32 numAttribs \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Protocol head for glXCreateContextAttribsARB
.PP
This protocol replaces \fC\fBGLXCreateContext\fP\fP, \fC\fBGLXCreateNewContext\fP\fP, and \fC\fBGLXCreateContextWithConfigSGIX\fP\fP\&. 
.PP
Définition à la ligne 1340 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCreateContextAttribsARB::B16"

.PP
Définition à la ligne 1343 du fichier glxproto\&.h\&.
.SS "CARD16 reserved2 GLXCreateContextAttribsARB::B16"

.PP
Définition à la ligne 1350 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP context GLXCreateContextAttribsARB::B32"

.PP
Définition à la ligne 1344 du fichier glxproto\&.h\&.
.SS "\fBGLXFBConfigID\fP fbconfig GLXCreateContextAttribsARB::B32"

.PP
Définition à la ligne 1345 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP shareList GLXCreateContextAttribsARB::B32"

.PP
Définition à la ligne 1347 du fichier glxproto\&.h\&.
.SS "CARD32 numAttribs GLXCreateContextAttribsARB::B32"

.PP
Définition à la ligne 1351 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateContextAttribsARB::glxCode"

.PP
Définition à la ligne 1342 du fichier glxproto\&.h\&.
.SS "\fBBOOL\fP GLXCreateContextAttribsARB::isDirect"

.PP
Définition à la ligne 1348 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateContextAttribsARB::reqType"

.PP
Définition à la ligne 1341 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateContextAttribsARB::reserved1"

.PP
Définition à la ligne 1349 du fichier glxproto\&.h\&.
.SS "CARD32 GLXCreateContextAttribsARB::screen"

.PP
Définition à la ligne 1346 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
