.TH "GLXCreateNewContext" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCreateNewContext \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP context \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXFBConfigID\fP fbconfig \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBrenderType\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP shareList \fBB32\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBisDirect\fP"
.br
.ti -1c
.RI "CARD8 \fBreserved1\fP"
.br
.ti -1c
.RI "CARD16 reserved2 \fBB16\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 443 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCreateNewContext::B16"

.PP
Définition à la ligne 446 du fichier glxproto\&.h\&.
.SS "CARD16 reserved2 GLXCreateNewContext::B16"

.PP
Définition à la ligne 454 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP context GLXCreateNewContext::B32"

.PP
Définition à la ligne 447 du fichier glxproto\&.h\&.
.SS "\fBGLXFBConfigID\fP fbconfig GLXCreateNewContext::B32"

.PP
Définition à la ligne 448 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXCreateNewContext::B32"

.PP
Définition à la ligne 449 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP shareList GLXCreateNewContext::B32"

.PP
Définition à la ligne 451 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateNewContext::glxCode"

.PP
Définition à la ligne 445 du fichier glxproto\&.h\&.
.SS "\fBBOOL\fP GLXCreateNewContext::isDirect"

.PP
Définition à la ligne 452 du fichier glxproto\&.h\&.
.SS "CARD32 GLXCreateNewContext::renderType"

.PP
Définition à la ligne 450 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateNewContext::reqType"

.PP
Définition à la ligne 444 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateNewContext::reserved1"

.PP
Définition à la ligne 453 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
