.TH "GLXCreateContext" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCreateContext \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP context \fBB32\fP"
.br
.ti -1c
.RI "CARD32 visual \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP shareList \fBB32\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBisDirect\fP"
.br
.ti -1c
.RI "CARD8 \fBreserved1\fP"
.br
.ti -1c
.RI "CARD16 reserved2 \fBB16\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 197 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCreateContext::B16"

.PP
Définition à la ligne 200 du fichier glxproto\&.h\&.
.SS "CARD16 reserved2 GLXCreateContext::B16"

.PP
Définition à la ligne 207 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP context GLXCreateContext::B32"

.PP
Définition à la ligne 201 du fichier glxproto\&.h\&.
.SS "CARD32 visual GLXCreateContext::B32"

.PP
Définition à la ligne 202 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXCreateContext::B32"

.PP
Définition à la ligne 203 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP shareList GLXCreateContext::B32"

.PP
Définition à la ligne 204 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateContext::glxCode"

.PP
Définition à la ligne 199 du fichier glxproto\&.h\&.
.SS "\fBBOOL\fP GLXCreateContext::isDirect"

.PP
Définition à la ligne 205 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateContext::reqType"

.PP
Définition à la ligne 198 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateContext::reserved1"

.PP
Définition à la ligne 206 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
