.TH "GLXCreateGLXPbufferSGIX" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXCreateGLXPbufferSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXFBConfigID\fP fbconfig \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXPbuffer\fP pbuffer \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBwidth\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBheight\fP \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1030 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXCreateGLXPbufferSGIX::B16"

.PP
Définition à la ligne 1033 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXCreateGLXPbufferSGIX::B32"

.PP
Définition à la ligne 1034 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXCreateGLXPbufferSGIX::B32"

.PP
Définition à la ligne 1035 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXCreateGLXPbufferSGIX::B32"

.PP
Définition à la ligne 1036 du fichier glxproto\&.h\&.
.SS "\fBGLXFBConfigID\fP fbconfig GLXCreateGLXPbufferSGIX::B32"

.PP
Définition à la ligne 1037 du fichier glxproto\&.h\&.
.SS "\fBGLXPbuffer\fP pbuffer GLXCreateGLXPbufferSGIX::B32"

.PP
Définition à la ligne 1038 du fichier glxproto\&.h\&.
.SS "CARD32 \fBwidth\fP GLXCreateGLXPbufferSGIX::B32"

.PP
Définition à la ligne 1039 du fichier glxproto\&.h\&.
.SS "CARD32 \fBheight\fP GLXCreateGLXPbufferSGIX::B32"

.PP
Définition à la ligne 1040 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateGLXPbufferSGIX::glxCode"

.PP
Définition à la ligne 1032 du fichier glxproto\&.h\&.
.SS "CARD8 GLXCreateGLXPbufferSGIX::reqType"

.PP
Définition à la ligne 1031 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
