.TH "GLXDestroyHyperpipeConfigSGIX" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXDestroyHyperpipeConfigSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "CARD32 hpId \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1191 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXDestroyHyperpipeConfigSGIX::B16"

.PP
Définition à la ligne 1194 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXDestroyHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1195 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXDestroyHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1196 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXDestroyHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1197 du fichier glxproto\&.h\&.
.SS "CARD32 hpId GLXDestroyHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1198 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 GLXDestroyHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1199 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 GLXDestroyHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1200 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 GLXDestroyHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1201 du fichier glxproto\&.h\&.
.SS "CARD8 GLXDestroyHyperpipeConfigSGIX::glxCode"

.PP
Définition à la ligne 1193 du fichier glxproto\&.h\&.
.SS "CARD8 GLXDestroyHyperpipeConfigSGIX::reqType"

.PP
Définition à la ligne 1192 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
