.TH "GLXDestroyGLXPbuffer" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXDestroyGLXPbuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXPbuffer\fP pbuffer \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1048 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXDestroyGLXPbuffer::B16"

.PP
Définition à la ligne 1051 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXDestroyGLXPbuffer::B32"

.PP
Définition à la ligne 1052 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXDestroyGLXPbuffer::B32"

.PP
Définition à la ligne 1053 du fichier glxproto\&.h\&.
.SS "\fBGLXPbuffer\fP pbuffer GLXDestroyGLXPbuffer::B32"

.PP
Définition à la ligne 1054 du fichier glxproto\&.h\&.
.SS "CARD8 GLXDestroyGLXPbuffer::glxCode"

.PP
Définition à la ligne 1050 du fichier glxproto\&.h\&.
.SS "CARD8 GLXDestroyGLXPbuffer::reqType"

.PP
Définition à la ligne 1049 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
