.TH "GLXDestroyGLXPixmap" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXDestroyGLXPixmap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXPixmap\fP glxpixmap \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 315 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXDestroyGLXPixmap::B16"

.PP
Définition à la ligne 318 du fichier glxproto\&.h\&.
.SS "\fBGLXPixmap\fP glxpixmap GLXDestroyGLXPixmap::B32"

.PP
Définition à la ligne 319 du fichier glxproto\&.h\&.
.SS "CARD8 GLXDestroyGLXPixmap::glxCode"

.PP
Définition à la ligne 317 du fichier glxproto\&.h\&.
.SS "CARD8 GLXDestroyGLXPixmap::reqType"

.PP
Définition à la ligne 316 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
