.TH "GLXDestroyPbuffer" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXDestroyPbuffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXPbuffer\fP pbuffer \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 501 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXDestroyPbuffer::B16"

.PP
Définition à la ligne 504 du fichier glxproto\&.h\&.
.SS "\fBGLXPbuffer\fP pbuffer GLXDestroyPbuffer::B32"

.PP
Définition à la ligne 505 du fichier glxproto\&.h\&.
.SS "CARD8 GLXDestroyPbuffer::glxCode"

.PP
Définition à la ligne 503 du fichier glxproto\&.h\&.
.SS "CARD8 GLXDestroyPbuffer::reqType"

.PP
Définition à la ligne 502 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
