.TH "GLXGetFBConfigs" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXGetFBConfigs \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 405 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXGetFBConfigs::B16"

.PP
Définition à la ligne 408 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXGetFBConfigs::B32"

.PP
Définition à la ligne 409 du fichier glxproto\&.h\&.
.SS "CARD8 GLXGetFBConfigs::glxCode"

.PP
Définition à la ligne 407 du fichier glxproto\&.h\&.
.SS "CARD8 GLXGetFBConfigs::reqType"

.PP
Définition à la ligne 406 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
