.TH "GLXGetFBConfigsSGIX" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXGetFBConfigsSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 979 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXGetFBConfigsSGIX::B16"

.PP
Définition à la ligne 982 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXGetFBConfigsSGIX::B32"

.PP
Définition à la ligne 983 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXGetFBConfigsSGIX::B32"

.PP
Définition à la ligne 984 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXGetFBConfigsSGIX::B32"

.PP
Définition à la ligne 985 du fichier glxproto\&.h\&.
.SS "CARD8 GLXGetFBConfigsSGIX::glxCode"

.PP
Définition à la ligne 981 du fichier glxproto\&.h\&.
.SS "CARD8 GLXGetFBConfigsSGIX::reqType"

.PP
Définition à la ligne 980 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
