.TH "GLXGetDrawableAttributes" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXGetDrawableAttributes \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP drawable \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 512 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXGetDrawableAttributes::B16"

.PP
Définition à la ligne 515 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP drawable GLXGetDrawableAttributes::B32"

.PP
Définition à la ligne 516 du fichier glxproto\&.h\&.
.SS "CARD8 GLXGetDrawableAttributes::glxCode"

.PP
Définition à la ligne 514 du fichier glxproto\&.h\&.
.SS "CARD8 GLXGetDrawableAttributes::reqType"

.PP
Définition à la ligne 513 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
