.TH "GLXHyperpipeConfigSGIX" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXHyperpipeConfigSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxext\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBchannel\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBparticipationType\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtimeSlice\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 841 du fichier glxext\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP GLXHyperpipeConfigSGIX::channel"

.PP
Définition à la ligne 843 du fichier glxext\&.h\&.
.SS "unsigned \fBint\fP GLXHyperpipeConfigSGIX::participationType"

.PP
Définition à la ligne 845 du fichier glxext\&.h\&.
.SS "char GLXHyperpipeConfigSGIX::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Définition à la ligne 842 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXHyperpipeConfigSGIX::timeSlice"

.PP
Définition à la ligne 846 du fichier glxext\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
