.TH "GLXHyperpipeNetworkSGIX" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXHyperpipeNetworkSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxext\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBnetworkId\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 836 du fichier glxext\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP GLXHyperpipeNetworkSGIX::networkId"

.PP
Définition à la ligne 838 du fichier glxext\&.h\&.
.SS "char GLXHyperpipeNetworkSGIX::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Définition à la ligne 837 du fichier glxext\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
