.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/openGL/include/glxint.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/openGL/include/glxint.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <X11/X\&.h>\fP
.br
\fC#include <X11/Xdefs\&.h>\fP
.br
\fC#include 'GL/gl\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__GLXvisualConfigRec\fP"
.br
.ti -1c
.RI "struct \fB__GLXFBConfigRec\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__GLX_MIN_CONFIG_PROPS\fP   18"
.br
.ti -1c
.RI "#define \fB__GLX_MAX_CONFIG_PROPS\fP   500"
.br
.ti -1c
.RI "#define \fB__GLX_EXT_CONFIG_PROPS\fP   10"
.br
.ti -1c
.RI "#define \fB__GLX_TOTAL_CONFIG\fP"
.br
.ti -1c
.RI "#define \fB__GLX_TOTAL_FBCONFIG_PROPS\fP   35"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fB__GLXvisualConfigRec\fP \fB__GLXvisualConfig\fP"
.br
.ti -1c
.RI "typedef struct \fB__GLXFBConfigRec\fP \fB__GLXFBConfig\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define __GLX_EXT_CONFIG_PROPS   10"

.PP
Définition à la ligne 69 du fichier glxint\&.h\&.
.SS "#define __GLX_MAX_CONFIG_PROPS   500"

.PP
Définition à la ligne 67 du fichier glxint\&.h\&.
.SS "#define __GLX_MIN_CONFIG_PROPS   18"

.PP
Définition à la ligne 66 du fichier glxint\&.h\&.
.SS "#define __GLX_TOTAL_CONFIG"
\fBValeur :\fP
.PP
.nf
(__GLX_MIN_CONFIG_PROPS +      \
                                    2 * __GLX_EXT_CONFIG_PROPS)
.fi
.PP
Définition à la ligne 78 du fichier glxint\&.h\&.
.SS "#define __GLX_TOTAL_FBCONFIG_PROPS   35"

.PP
Définition à la ligne 135 du fichier glxint\&.h\&.
.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fB__GLXFBConfigRec\fP \fB__GLXFBConfig\fP"

.PP
Définition à la ligne 39 du fichier glxint\&.h\&.
.SS "typedef struct \fB__GLXvisualConfigRec\fP \fB__GLXvisualConfig\fP"

.PP
Définition à la ligne 38 du fichier glxint\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
