.TH "GLXJoinSwapGroupSGIX" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXJoinSwapGroupSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 unused \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP drawable \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP member \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1106 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXJoinSwapGroupSGIX::B16"

.PP
Définition à la ligne 1109 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXJoinSwapGroupSGIX::B32"

.PP
Définition à la ligne 1110 du fichier glxproto\&.h\&.
.SS "CARD32 unused GLXJoinSwapGroupSGIX::B32"

.PP
Définition à la ligne 1111 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP drawable GLXJoinSwapGroupSGIX::B32"

.PP
Définition à la ligne 1112 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP member GLXJoinSwapGroupSGIX::B32"

.PP
Définition à la ligne 1113 du fichier glxproto\&.h\&.
.SS "CARD8 GLXJoinSwapGroupSGIX::glxCode"

.PP
Définition à la ligne 1108 du fichier glxproto\&.h\&.
.SS "CARD8 GLXJoinSwapGroupSGIX::reqType"

.PP
Définition à la ligne 1107 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
