.TH "GLXMakeCurrentReadSGI" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXMakeCurrentReadSGI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP oldContextTag \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP drawable \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP readable \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP context \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 950 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXMakeCurrentReadSGI::B16"

.PP
Définition à la ligne 953 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXMakeCurrentReadSGI::B32"

.PP
Définition à la ligne 954 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP oldContextTag GLXMakeCurrentReadSGI::B32"

.PP
Définition à la ligne 955 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP drawable GLXMakeCurrentReadSGI::B32"

.PP
Définition à la ligne 956 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP readable GLXMakeCurrentReadSGI::B32"

.PP
Définition à la ligne 957 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP context GLXMakeCurrentReadSGI::B32"

.PP
Définition à la ligne 958 du fichier glxproto\&.h\&.
.SS "CARD8 GLXMakeCurrentReadSGI::glxCode"

.PP
Définition à la ligne 952 du fichier glxproto\&.h\&.
.SS "CARD8 GLXMakeCurrentReadSGI::reqType"

.PP
Définition à la ligne 951 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
