.TH "GLXMakeContextCurrent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXMakeContextCurrent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP oldContextTag \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP drawable \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP readdrawable \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP context \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 472 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXMakeContextCurrent::B16"

.PP
Définition à la ligne 475 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP oldContextTag GLXMakeContextCurrent::B32"

.PP
Définition à la ligne 476 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP drawable GLXMakeContextCurrent::B32"

.PP
Définition à la ligne 477 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP readdrawable GLXMakeContextCurrent::B32"

.PP
Définition à la ligne 478 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP context GLXMakeContextCurrent::B32"

.PP
Définition à la ligne 479 du fichier glxproto\&.h\&.
.SS "CARD8 GLXMakeContextCurrent::glxCode"

.PP
Définition à la ligne 474 du fichier glxproto\&.h\&.
.SS "CARD8 GLXMakeContextCurrent::reqType"

.PP
Définition à la ligne 473 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
