.TH "GLXMakeCurrent" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXMakeCurrent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP drawable \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP context \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP oldContextTag \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 225 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXMakeCurrent::B16"

.PP
Définition à la ligne 228 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP drawable GLXMakeCurrent::B32"

.PP
Définition à la ligne 229 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP context GLXMakeCurrent::B32"

.PP
Définition à la ligne 230 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP oldContextTag GLXMakeCurrent::B32"

.PP
Définition à la ligne 231 du fichier glxproto\&.h\&.
.SS "CARD8 GLXMakeCurrent::glxCode"

.PP
Définition à la ligne 227 du fichier glxproto\&.h\&.
.SS "CARD8 GLXMakeCurrent::reqType"

.PP
Définition à la ligne 226 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
