.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/openGL/include/glxmd.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/openGL/include/glxmd.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF32\fP"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef float \fBFLOAT32\fP"
.br
.ti -1c
.RI "typedef double \fBFLOAT64\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define F32"

.PP
Définition à la ligne 52 du fichier glxmd\&.h\&.
.SH "Documentation des définitions de type"
.PP 
.SS "typedef float \fBFLOAT32\fP"

.PP
Définition à la ligne 42 du fichier glxmd\&.h\&.
.SS "typedef double \fBFLOAT64\fP"

.PP
Définition à la ligne 43 du fichier glxmd\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
