.TH "GLXPbufferClobberEvent" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPbufferClobberEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glx\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBint\fP \fBevent_type\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdraw_type\fP"
.br
.ti -1c
.RI "unsigned long \fBserial\fP"
.br
.ti -1c
.RI "Bool \fBsend_event\fP"
.br
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP \fBdrawable\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBbuffer_mask\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBaux_buffer\fP"
.br
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcount\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 477 du fichier glx\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "unsigned \fBint\fP GLXPbufferClobberEvent::aux_buffer"

.PP
Définition à la ligne 485 du fichier glx\&.h\&.
.SS "unsigned \fBint\fP GLXPbufferClobberEvent::buffer_mask"

.PP
Définition à la ligne 484 du fichier glx\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::count"

.PP
Définition à la ligne 488 du fichier glx\&.h\&.
.SS "Display* GLXPbufferClobberEvent::display"

.PP
Définition à la ligne 482 du fichier glx\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::draw_type"

.PP
Définition à la ligne 479 du fichier glx\&.h\&.
.SS "\fBGLXDrawable\fP GLXPbufferClobberEvent::drawable"

.PP
Définition à la ligne 483 du fichier glx\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::event_type"

.PP
Définition à la ligne 478 du fichier glx\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::height"

.PP
Définition à la ligne 487 du fichier glx\&.h\&.
.SS "Bool GLXPbufferClobberEvent::send_event"

.PP
Définition à la ligne 481 du fichier glx\&.h\&.
.SS "unsigned long GLXPbufferClobberEvent::serial"

.PP
Définition à la ligne 480 du fichier glx\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::width"

.PP
Définition à la ligne 487 du fichier glx\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::x"

.PP
Définition à la ligne 486 du fichier glx\&.h\&.
.SS "\fBint\fP GLXPbufferClobberEvent::y"

.PP
Définition à la ligne 486 du fichier glx\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
