.TH "GLXPipeRect" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRect \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxext\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBsrcXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestHeight\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 849 du fichier glxext\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP GLXPipeRect::destHeight"

.PP
Définition à la ligne 852 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRect::destWidth"

.PP
Définition à la ligne 852 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRect::destXOrigin"

.PP
Définition à la ligne 852 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRect::destYOrigin"

.PP
Définition à la ligne 852 du fichier glxext\&.h\&.
.SS "char GLXPipeRect::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Définition à la ligne 850 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcHeight"

.PP
Définition à la ligne 851 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcWidth"

.PP
Définition à la ligne 851 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcXOrigin"

.PP
Définition à la ligne 851 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRect::srcYOrigin"

.PP
Définition à la ligne 851 du fichier glxext\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
