.TH "GLXPipeRectLimits" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRectLimits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxext\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"
.br
.ti -1c
.RI "\fBint\fP \fBXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaxHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaxWidth\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 855 du fichier glxext\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP GLXPipeRectLimits::maxHeight"

.PP
Définition à la ligne 857 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRectLimits::maxWidth"

.PP
Définition à la ligne 857 du fichier glxext\&.h\&.
.SS "char GLXPipeRectLimits::pipeName[\fBGLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX\fP]"

.PP
Définition à la ligne 856 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRectLimits::XOrigin"

.PP
Définition à la ligne 857 du fichier glxext\&.h\&.
.SS "\fBint\fP GLXPipeRectLimits::YOrigin"

.PP
Définition à la ligne 857 du fichier glxext\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
