.TH "GLXQueryContext" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXQueryContext \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP context \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 461 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXQueryContext::B16"

.PP
Définition à la ligne 464 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP context GLXQueryContext::B32"

.PP
Définition à la ligne 465 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryContext::glxCode"

.PP
Définition à la ligne 463 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryContext::reqType"

.PP
Définition à la ligne 462 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
