.TH "GLXQueryHyperpipeConfigSGIX" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXQueryHyperpipeConfigSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "CARD32 hpId \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1225 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXQueryHyperpipeConfigSGIX::B16"

.PP
Définition à la ligne 1228 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXQueryHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1229 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXQueryHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1230 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXQueryHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1231 du fichier glxproto\&.h\&.
.SS "CARD32 hpId GLXQueryHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1232 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 GLXQueryHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1233 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 GLXQueryHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1234 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 GLXQueryHyperpipeConfigSGIX::B32"

.PP
Définition à la ligne 1235 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryHyperpipeConfigSGIX::glxCode"

.PP
Définition à la ligne 1227 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryHyperpipeConfigSGIX::reqType"

.PP
Définition à la ligne 1226 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
