.TH "GLXQueryServerString" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXQueryServerString \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBname\fP \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 378 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXQueryServerString::B16"

.PP
Définition à la ligne 381 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXQueryServerString::B32"

.PP
Définition à la ligne 382 du fichier glxproto\&.h\&.
.SS "CARD32 \fBname\fP GLXQueryServerString::B32"

.PP
Définition à la ligne 383 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryServerString::glxCode"

.PP
Définition à la ligne 380 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryServerString::reqType"

.PP
Définition à la ligne 379 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
