.TH "GLXQueryVersion" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXQueryVersion \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 majorVersion \fBB32\fP"
.br
.ti -1c
.RI "CARD32 minorVersion \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 174 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXQueryVersion::B16"

.PP
Définition à la ligne 177 du fichier glxproto\&.h\&.
.SS "CARD32 majorVersion GLXQueryVersion::B32"

.PP
Définition à la ligne 178 du fichier glxproto\&.h\&.
.SS "CARD32 minorVersion GLXQueryVersion::B32"

.PP
Définition à la ligne 179 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryVersion::glxCode"

.PP
Définition à la ligne 176 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryVersion::reqType"

.PP
Définition à la ligne 175 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
