.TH "GLXQueryMaxSwapBarriersSGIX" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXQueryMaxSwapBarriersSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 unused \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1134 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXQueryMaxSwapBarriersSGIX::B16"

.PP
Définition à la ligne 1137 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXQueryMaxSwapBarriersSGIX::B32"

.PP
Définition à la ligne 1138 du fichier glxproto\&.h\&.
.SS "CARD32 unused GLXQueryMaxSwapBarriersSGIX::B32"

.PP
Définition à la ligne 1139 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXQueryMaxSwapBarriersSGIX::B32"

.PP
Définition à la ligne 1140 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryMaxSwapBarriersSGIX::glxCode"

.PP
Définition à la ligne 1136 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryMaxSwapBarriersSGIX::reqType"

.PP
Définition à la ligne 1135 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
