.TH "GLXQueryContextInfoEXT" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXQueryContextInfoEXT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextID\fP context \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 920 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXQueryContextInfoEXT::B16"

.PP
Définition à la ligne 923 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXQueryContextInfoEXT::B32"

.PP
Définition à la ligne 924 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXQueryContextInfoEXT::B32"

.PP
Définition à la ligne 925 du fichier glxproto\&.h\&.
.SS "\fBGLXContextID\fP context GLXQueryContextInfoEXT::B32"

.PP
Définition à la ligne 926 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryContextInfoEXT::glxCode"

.PP
Définition à la ligne 922 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryContextInfoEXT::reqType"

.PP
Définition à la ligne 921 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
