.TH "GLXQueryHyperpipeNetworkSGIX" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXQueryHyperpipeNetworkSGIX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1161 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXQueryHyperpipeNetworkSGIX::B16"

.PP
Définition à la ligne 1164 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode GLXQueryHyperpipeNetworkSGIX::B32"

.PP
Définition à la ligne 1165 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 GLXQueryHyperpipeNetworkSGIX::B32"

.PP
Définition à la ligne 1166 du fichier glxproto\&.h\&.
.SS "CARD32 screen GLXQueryHyperpipeNetworkSGIX::B32"

.PP
Définition à la ligne 1167 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryHyperpipeNetworkSGIX::glxCode"

.PP
Définition à la ligne 1163 du fichier glxproto\&.h\&.
.SS "CARD8 GLXQueryHyperpipeNetworkSGIX::reqType"

.PP
Définition à la ligne 1162 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
