.TH "GLXRender" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXRender \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 127 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXRender::B16"

.PP
Définition à la ligne 130 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag GLXRender::B32"

.PP
Définition à la ligne 131 du fichier glxproto\&.h\&.
.SS "CARD8 GLXRender::glxCode"

.PP
Définition à la ligne 129 du fichier glxproto\&.h\&.
.SS "CARD8 GLXRender::reqType"

.PP
Définition à la ligne 128 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
