.TH "GLXRenderLarge" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXRenderLarge \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.ti -1c
.RI "CARD16 requestNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD16 requestTotal \fBB16\fP"
.br
.ti -1c
.RI "CARD32 dataBytes \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 147 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXRenderLarge::B16"

.PP
Définition à la ligne 150 du fichier glxproto\&.h\&.
.SS "CARD16 requestNumber GLXRenderLarge::B16"

.PP
Définition à la ligne 152 du fichier glxproto\&.h\&.
.SS "CARD16 requestTotal GLXRenderLarge::B16"

.PP
Définition à la ligne 153 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag GLXRenderLarge::B32"

.PP
Définition à la ligne 151 du fichier glxproto\&.h\&.
.SS "CARD32 dataBytes GLXRenderLarge::B32"

.PP
Définition à la ligne 154 du fichier glxproto\&.h\&.
.SS "CARD8 GLXRenderLarge::glxCode"

.PP
Définition à la ligne 149 du fichier glxproto\&.h\&.
.SS "CARD8 GLXRenderLarge::reqType"

.PP
Définition à la ligne 148 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
