.TH "GLXSingle" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXSingle \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 163 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXSingle::B16"

.PP
Définition à la ligne 166 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag GLXSingle::B32"

.PP
Définition à la ligne 167 du fichier glxproto\&.h\&.
.SS "CARD8 GLXSingle::glxCode"

.PP
Définition à la ligne 165 du fichier glxproto\&.h\&.
.SS "CARD8 GLXSingle::reqType"

.PP
Définition à la ligne 164 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
