.TH "GLXSwapBuffers" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXSwapBuffers \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXDrawable\fP drawable \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 274 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXSwapBuffers::B16"

.PP
Définition à la ligne 277 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag GLXSwapBuffers::B32"

.PP
Définition à la ligne 278 du fichier glxproto\&.h\&.
.SS "\fBGLXDrawable\fP drawable GLXSwapBuffers::B32"

.PP
Définition à la ligne 279 du fichier glxproto\&.h\&.
.SS "CARD8 GLXSwapBuffers::glxCode"

.PP
Définition à la ligne 276 du fichier glxproto\&.h\&.
.SS "CARD8 GLXSwapBuffers::reqType"

.PP
Définition à la ligne 275 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
