.TH "GLXUseXFont" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXUseXFont \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.ti -1c
.RI "CARD32 font \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBfirst\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBcount\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 listBase \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 286 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXUseXFont::B16"

.PP
Définition à la ligne 289 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag GLXUseXFont::B32"

.PP
Définition à la ligne 290 du fichier glxproto\&.h\&.
.SS "CARD32 font GLXUseXFont::B32"

.PP
Définition à la ligne 291 du fichier glxproto\&.h\&.
.SS "CARD32 \fBfirst\fP GLXUseXFont::B32"

.PP
Définition à la ligne 292 du fichier glxproto\&.h\&.
.SS "CARD32 \fBcount\fP GLXUseXFont::B32"

.PP
Définition à la ligne 293 du fichier glxproto\&.h\&.
.SS "CARD32 listBase GLXUseXFont::B32"

.PP
Définition à la ligne 294 du fichier glxproto\&.h\&.
.SS "CARD8 GLXUseXFont::glxCode"

.PP
Définition à la ligne 288 du fichier glxproto\&.h\&.
.SS "CARD8 GLXUseXFont::reqType"

.PP
Définition à la ligne 287 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
