.TH "GLXWaitGL" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXWaitGL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 238 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP GLXWaitGL::B16"

.PP
Définition à la ligne 241 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag GLXWaitGL::B32"

.PP
Définition à la ligne 242 du fichier glxproto\&.h\&.
.SS "CARD8 GLXWaitGL::glxCode"

.PP
Définition à la ligne 240 du fichier glxproto\&.h\&.
.SS "CARD8 GLXWaitGL::reqType"

.PP
Définition à la ligne 239 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
