.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/HighScore.hpp" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/HighScore.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBs_header\fP"
.br
.ti -1c
.RI "struct \fBs_highScore\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAGICNBR\fP   1996"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBs_header\fP \fBt_header\fP"
.br
.ti -1c
.RI "typedef struct \fBs_highScore\fP \fBt_highScore\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define MAGICNBR   1996"

.PP
Définition à la ligne 14 du fichier HighScore\&.hpp\&.
.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fBs_header\fP		 \fBt_header\fP"

.SS "typedef struct \fBs_highScore\fP		 \fBt_highScore\fP"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
