.TH "Integer_Field" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Integer_Field \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursesf\&.h>\fP
.PP
Est dérivée de \fBNCursesFieldType\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBInteger_Field\fP (\fBint\fP prec, long low=0L, long high=0L)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 755 du fichier cursesf\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Integer_Field::Integer_Field (\fBint\fP prec, long low = \fC0L\fP, long high = \fC0L\fP)\fC [inline]\fP"

.PP
Définition à la ligne 767 du fichier cursesf\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
