.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/LoadHighScore.hpp" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/LoadHighScore.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <sys/mman\&.h>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include 'HighScore\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLoadHighScore\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &ostream, \fBLoadHighScore\fP \fBconst\fP &highScore)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "std::ostream& operator<< (std::ostream & ostream, \fBLoadHighScore\fP \fBconst\fP & highScore)"

.PP
Définition à la ligne 104 du fichier LoadHighScore\&.cpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
