.TH "md__home_wery_a_rendu__c_p_p_cpp_arcade__r_e_a_d_m_e" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_wery_a_rendu__c_p_p_cpp_arcade__r_e_a_d_m_e \- README 
#CPP_ARCADE \fBCore\fP
.PP
\fBLib Interface\fP
.IP "1." 4
\fBIGraph\fP \fBIGraph()\fP; ~IGraph(); void eventManagement(); void \fBrefresh()\fP; int getKey();
.PP
.PP
\fBLib Games\fP
.IP "1." 4
\fBAGame\fP \fBAGame()\fP; ~AGame(); void init(); void update(); 
.PP

