.TH "MEVENT" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MEVENT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <curses\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "short \fBid\fP"
.br
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.ti -1c
.RI "\fBint\fP \fBz\fP"
.br
.ti -1c
.RI "\fBmmask_t\fP \fBbstate\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1606 du fichier curses\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBmmask_t\fP MEVENT::bstate"

.PP
Définition à la ligne 1610 du fichier curses\&.h\&.
.SS "short MEVENT::id"

.PP
Définition à la ligne 1608 du fichier curses\&.h\&.
.SS "\fBint\fP MEVENT::x"

.PP
Définition à la ligne 1609 du fichier curses\&.h\&.
.SS "\fBint\fP MEVENT::y"

.PP
Définition à la ligne 1609 du fichier curses\&.h\&.
.SS "\fBint\fP MEVENT::z"

.PP
Définition à la ligne 1609 du fichier curses\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
