.TH "NCursesFormException" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NCursesFormException \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <etip\&.h>\fP
.PP
Est dérivée de \fBNCursesException\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBNCursesFormException\fP (\fBconst\fP char *msg, \fBint\fP err)"
.br
.ti -1c
.RI "\fBNCursesFormException\fP (\fBconst\fP \fBNCursesForm\fP *form, \fBconst\fP char *msg, \fBint\fP err)"
.br
.ti -1c
.RI "\fBNCursesFormException\fP (\fBint\fP err)"
.br
.ti -1c
.RI "\fBNCursesFormException\fP (\fBconst\fP \fBNCursesForm\fP *form, \fBint\fP err)"
.br
.ti -1c
.RI "\fBNCursesFormException\fP & \fBoperator=\fP (\fBconst\fP \fBNCursesFormException\fP &rhs)"
.br
.ti -1c
.RI "\fBNCursesFormException\fP (\fBconst\fP \fBNCursesFormException\fP &rhs)"
.br
.ti -1c
.RI "virtual \fBconst\fP char * \fBclassname\fP () \fBconst\fP "
.br
.ti -1c
.RI "virtual \fB~NCursesFormException\fP ()"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBNCursesForm\fP * \fBf\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 282 du fichier etip\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "NCursesFormException::NCursesFormException (\fBconst\fP char * msg, \fBint\fP err)\fC [inline]\fP"

.PP
Définition à la ligne 287 du fichier etip\&.h\&.
.SS "NCursesFormException::NCursesFormException (\fBconst\fP \fBNCursesForm\fP * form, \fBconst\fP char * msg, \fBint\fP err)\fC [inline]\fP"

.PP
Définition à la ligne 292 du fichier etip\&.h\&.
.SS "NCursesFormException::NCursesFormException (\fBint\fP err)\fC [inline]\fP"

.PP
Définition à la ligne 299 du fichier etip\&.h\&.
.SS "NCursesFormException::NCursesFormException (\fBconst\fP \fBNCursesForm\fP * form, \fBint\fP err)\fC [inline]\fP"

.PP
Définition à la ligne 304 du fichier etip\&.h\&.
.SS "NCursesFormException::NCursesFormException (\fBconst\fP \fBNCursesFormException\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 319 du fichier etip\&.h\&.
.SS "virtual NCursesFormException::~NCursesFormException ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 328 du fichier etip\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "virtual \fBconst\fP char* NCursesFormException::classname () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBNCursesException\fP\&.
.PP
Définition à la ligne 324 du fichier etip\&.h\&.
.SS "\fBNCursesFormException\fP& NCursesFormException::operator= (\fBconst\fP \fBNCursesFormException\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 310 du fichier etip\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBconst\fP \fBNCursesForm\fP* NCursesFormException::f"

.PP
Définition à la ligne 285 du fichier etip\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
