.TH "NCursesColorWindow" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NCursesColorWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursesw\&.h>\fP
.PP
Est dérivée de \fBNCursesWindow\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBNCursesColorWindow\fP (\fBWINDOW\fP *&window)"
.br
.ti -1c
.RI "\fBNCursesColorWindow\fP (\fBint\fP nlines, \fBint\fP ncols, \fBint\fP begin_y, \fBint\fP begin_x)"
.br
.ti -1c
.RI "\fBNCursesColorWindow\fP (\fBNCursesWindow\fP &parentWin, \fBint\fP nlines, \fBint\fP ncols, \fBint\fP begin_y, \fBint\fP begin_x, char absrel= '\fBa\fP')"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 1367 du fichier cursesw\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "NCursesColorWindow::NCursesColorWindow (\fBWINDOW\fP *& window)\fC [inline]\fP"

.PP
Définition à la ligne 1370 du fichier cursesw\&.h\&.
.SS "NCursesColorWindow::NCursesColorWindow (\fBint\fP nlines, \fBint\fP ncols, \fBint\fP begin_y, \fBint\fP begin_x)\fC [inline]\fP"

.PP
Définition à la ligne 1374 du fichier cursesw\&.h\&.
.SS "NCursesColorWindow::NCursesColorWindow (\fBNCursesWindow\fP & parentWin, \fBint\fP nlines, \fBint\fP ncols, \fBint\fP begin_y, \fBint\fP begin_x, char absrel = \fC'\fBa\fP'\fP)\fC [inline]\fP"

.PP
Définition à la ligne 1381 du fichier cursesw\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
