.TH "NCursesUserField< T >" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NCursesUserField< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursesf\&.h>\fP
.PP
Est dérivée de \fBNCursesFormField\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBNCursesUserField\fP (\fBint\fP rows, \fBint\fP ncols, \fBint\fP first_row=0, \fBint\fP first_col=0, \fBconst\fP T *p_UserData=\fBSTATIC_CAST\fP(T *)(0), \fBint\fP offscreen_rows=0, \fBint\fP additional_buffers=0)"
.br
.ti -1c
.RI "virtual \fB~NCursesUserField\fP ()"
.br
.ti -1c
.RI "\fBconst\fP T * \fBUserData\fP (\fBvoid\fP) \fBconst\fP "
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBsetUserData\fP (\fBconst\fP T *p_UserData)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 

.SS "template<class T>class NCursesUserField< T >"

.PP
Définition à la ligne 631 du fichier cursesf\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "template<class T > \fBNCursesUserField\fP< T >::\fBNCursesUserField\fP (\fBint\fP rows, \fBint\fP ncols, \fBint\fP first_row = \fC0\fP, \fBint\fP first_col = \fC0\fP, \fBconst\fP T * p_UserData = \fC\fBSTATIC_CAST\fP(T*)(0)\fP, \fBint\fP offscreen_rows = \fC0\fP, \fBint\fP additional_buffers = \fC0\fP)\fC [inline]\fP"

.PP
Définition à la ligne 634 du fichier cursesf\&.h\&.
.SS "template<class T > virtual \fBNCursesUserField\fP< T >::~\fBNCursesUserField\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 648 du fichier cursesf\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "template<class T > virtual \fBvoid\fP \fBNCursesUserField\fP< T >::setUserData (\fBconst\fP T * p_UserData)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 654 du fichier cursesf\&.h\&.
.SS "template<class T > \fBconst\fP T* \fBNCursesUserField\fP< T >::UserData (\fBvoid\fP) const\fC [inline]\fP"

.PP
Définition à la ligne 650 du fichier cursesf\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
