.TH "ncurses::Window" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ncurses::Window \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Window\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBWindow\fP (\fBVector2\fP< double > &\fBs\fP, \fBVector2\fP< double > &\fBp\fP, \fBWINDOW\fP *pa)"
.br
.ti -1c
.RI "virtual \fB~Window\fP ()"
.br
.ti -1c
.RI "\fBVector2\fP< double > \fBgetSize\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBsetSize\fP ()"
.br
.ti -1c
.RI "\fBVector2\fP< double > \fBgetPos\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBsetPos\fP ()"
.br
.ti -1c
.RI "\fBWINDOW\fP * \fBgetWind\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBclose\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetWind\fP (\fBVector2\fP< double > &\fBs\fP, \fBVector2\fP< double > &\fBp\fP, \fBWINDOW\fP *pa)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 8 du fichier Window\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "ncurses::Window::Window (\fBVector2\fP< double > & s, \fBVector2\fP< double > & p, \fBWINDOW\fP * pa)"

.PP
Définition à la ligne 4 du fichier Window\&.cpp\&.
.SS "ncurses::Window::~Window ()\fC [virtual]\fP"

.PP
Définition à la ligne 10 du fichier Window\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP ncurses::Window::close ()"

.PP
Définition à la ligne 49 du fichier Window\&.cpp\&.
.SS "\fBVector2\fP< double > ncurses::Window::getPos () const"

.PP
Définition à la ligne 24 du fichier Window\&.cpp\&.
.SS "\fBVector2\fP< double > ncurses::Window::getSize () const"

.PP
Définition à la ligne 16 du fichier Window\&.cpp\&.
.SS "\fBWINDOW\fP * ncurses::Window::getWind () const"

.PP
Définition à la ligne 45 du fichier Window\&.cpp\&.
.SS "\fBvoid\fP ncurses::Window::setPos ()"

.PP
Définition à la ligne 29 du fichier Window\&.cpp\&.
.SS "\fBvoid\fP ncurses::Window::setSize ()"

.PP
Définition à la ligne 21 du fichier Window\&.cpp\&.
.SS "\fBvoid\fP ncurses::Window::setWind (\fBVector2\fP< double > & s, \fBVector2\fP< double > & p, \fBWINDOW\fP * pa)"

.PP
Définition à la ligne 32 du fichier Window\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
