.TH "NCursesUserItem< T >" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NCursesUserItem< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursesm\&.h>\fP
.PP
Est dérivée de \fBNCursesMenuItem\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBNCursesUserItem\fP (\fBconst\fP char *p_name, \fBconst\fP char *p_descript=\fBNULL\fP, \fBconst\fP T *p_UserData=\fBSTATIC_CAST\fP(T *)(0))"
.br
.ti -1c
.RI "virtual \fB~NCursesUserItem\fP ()"
.br
.ti -1c
.RI "\fBconst\fP T * \fBUserData\fP (\fBvoid\fP) \fBconst\fP "
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBsetUserData\fP (\fBconst\fP T *p_UserData)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 

.SS "template<class T>class NCursesUserItem< T >"

.PP
Définition à la ligne 598 du fichier cursesm\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "template<class T > \fBNCursesUserItem\fP< T >::\fBNCursesUserItem\fP (\fBconst\fP char * p_name, \fBconst\fP char * p_descript = \fC\fBNULL\fP\fP, \fBconst\fP T * p_UserData = \fC\fBSTATIC_CAST\fP(T*)(0)\fP)\fC [inline]\fP"

.PP
Définition à la ligne 601 du fichier cursesm\&.h\&.
.SS "template<class T > virtual \fBNCursesUserItem\fP< T >::~\fBNCursesUserItem\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 609 du fichier cursesm\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "template<class T > virtual \fBvoid\fP \fBNCursesUserItem\fP< T >::setUserData (\fBconst\fP T * p_UserData)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 615 du fichier cursesm\&.h\&.
.SS "template<class T > \fBconst\fP T* \fBNCursesUserItem\fP< T >::UserData (\fBvoid\fP) const\fC [inline]\fP"

.PP
Définition à la ligne 611 du fichier cursesm\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
