.TH "NCursesUserPanel< T >" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NCursesUserPanel< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursesp\&.h>\fP
.PP
Est dérivée de \fBNCursesPanel\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBNCursesUserPanel\fP (\fBint\fP nlines, \fBint\fP ncols, \fBint\fP begin_y=0, \fBint\fP begin_x=0, \fBconst\fP T *p_UserData=\fBSTATIC_CAST\fP(T *)(0))"
.br
.ti -1c
.RI "\fBNCursesUserPanel\fP (\fBconst\fP T *p_UserData=\fBSTATIC_CAST\fP(T *)(0))"
.br
.ti -1c
.RI "virtual \fB~NCursesUserPanel\fP ()"
.br
.ti -1c
.RI "T * \fBUserData\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBsetUserData\fP (\fBconst\fP T *p_UserData)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 

.SS "template<class T>class NCursesUserPanel< T >"

.PP
Définition à la ligne 228 du fichier cursesp\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "template<class T > \fBNCursesUserPanel\fP< T >::\fBNCursesUserPanel\fP (\fBint\fP nlines, \fBint\fP ncols, \fBint\fP begin_y = \fC0\fP, \fBint\fP begin_x = \fC0\fP, \fBconst\fP T * p_UserData = \fC\fBSTATIC_CAST\fP(T*)(0)\fP)\fC [inline]\fP"

.PP
Définition à la ligne 231 du fichier cursesp\&.h\&.
.SS "template<class T > \fBNCursesUserPanel\fP< T >::\fBNCursesUserPanel\fP (\fBconst\fP T * p_UserData = \fC\fBSTATIC_CAST\fP(T*)(0)\fP)\fC [inline]\fP"

.PP
Définition à la ligne 245 du fichier cursesp\&.h\&.
.SS "template<class T > virtual \fBNCursesUserPanel\fP< T >::~\fBNCursesUserPanel\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 253 du fichier cursesp\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "template<class T > virtual \fBvoid\fP \fBNCursesUserPanel\fP< T >::setUserData (\fBconst\fP T * p_UserData)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 261 du fichier cursesp\&.h\&.
.SS "template<class T > T* \fBNCursesUserPanel\fP< T >::UserData (\fBvoid\fP)\fC [inline]\fP"

.PP
Définition à la ligne 255 du fichier cursesp\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
