.TH "NCursesApplication::_slk_link" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NCursesApplication::_slk_link \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursesapp\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "struct \fB_slk_link\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBSoft_Label_Key_Set\fP * \fBSLKs\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 43 du fichier cursesapp\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "struct \fB_slk_link\fP* NCursesApplication::_slk_link::prev"

.PP
Définition à la ligne 44 du fichier cursesapp\&.h\&.
.SS "\fBSoft_Label_Key_Set\fP* NCursesApplication::_slk_link::SLKs"

.PP
Définition à la ligne 45 du fichier cursesapp\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
