.TH "NCursesMenuException" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NCursesMenuException \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <etip\&.h>\fP
.PP
Est dérivée de \fBNCursesException\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBNCursesMenuException\fP (\fBconst\fP char *msg, \fBint\fP err)"
.br
.ti -1c
.RI "\fBNCursesMenuException\fP (\fBconst\fP \fBNCursesMenu\fP *menu, \fBconst\fP char *msg, \fBint\fP err)"
.br
.ti -1c
.RI "\fBNCursesMenuException\fP (\fBint\fP err)"
.br
.ti -1c
.RI "\fBNCursesMenuException\fP (\fBconst\fP \fBNCursesMenu\fP *menu, \fBint\fP err)"
.br
.ti -1c
.RI "\fBNCursesMenuException\fP & \fBoperator=\fP (\fBconst\fP \fBNCursesMenuException\fP &rhs)"
.br
.ti -1c
.RI "\fBNCursesMenuException\fP (\fBconst\fP \fBNCursesMenuException\fP &rhs)"
.br
.ti -1c
.RI "virtual \fBconst\fP char * \fBclassname\fP () \fBconst\fP "
.br
.ti -1c
.RI "virtual \fB~NCursesMenuException\fP ()"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBNCursesMenu\fP * \fBm\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 231 du fichier etip\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "NCursesMenuException::NCursesMenuException (\fBconst\fP char * msg, \fBint\fP err)\fC [inline]\fP"

.PP
Définition à la ligne 236 du fichier etip\&.h\&.
.SS "NCursesMenuException::NCursesMenuException (\fBconst\fP \fBNCursesMenu\fP * menu, \fBconst\fP char * msg, \fBint\fP err)\fC [inline]\fP"

.PP
Définition à la ligne 241 du fichier etip\&.h\&.
.SS "NCursesMenuException::NCursesMenuException (\fBint\fP err)\fC [inline]\fP"

.PP
Définition à la ligne 248 du fichier etip\&.h\&.
.SS "NCursesMenuException::NCursesMenuException (\fBconst\fP \fBNCursesMenu\fP * menu, \fBint\fP err)\fC [inline]\fP"

.PP
Définition à la ligne 253 du fichier etip\&.h\&.
.SS "NCursesMenuException::NCursesMenuException (\fBconst\fP \fBNCursesMenuException\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 268 du fichier etip\&.h\&.
.SS "virtual NCursesMenuException::~NCursesMenuException ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Définition à la ligne 277 du fichier etip\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "virtual \fBconst\fP char* NCursesMenuException::classname () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Réimplémentée à partir de \fBNCursesException\fP\&.
.PP
Définition à la ligne 273 du fichier etip\&.h\&.
.SS "\fBNCursesMenuException\fP& NCursesMenuException::operator= (\fBconst\fP \fBNCursesMenuException\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 259 du fichier etip\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBconst\fP \fBNCursesMenu\fP* NCursesMenuException::m"

.PP
Définition à la ligne 234 du fichier etip\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
