.TH "OpenGL" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenGL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenGL\&.hpp>\fP
.PP
Est dérivée de \fBIGraph\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBOpenGL\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "virtual \fB~OpenGL\fP ()"
.br
.ti -1c
.RI "virtual \fBint\fP \fBeventManagment\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBdisplay\fP (std::stack< \fBAComponent\fP * >)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBinit\fP (\fBconst\fP \fBstd::string\fP &\fBname\fP, \fBVector2\fP< \fBint\fP > \fBsize\fP, std::stack< \fBAComponent\fP * > cache)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBinit\fP (\fBconst\fP \fBstd::string\fP &\fBname\fP, \fBVector2\fP< \fBint\fP > \fBsize\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBdestroy\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 23 du fichier OpenGL\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "OpenGL::OpenGL (\fBvoid\fP)"

.PP
Définition à la ligne 4 du fichier OpenGL\&.cpp\&.
.SS "OpenGL::~OpenGL ()\fC [virtual]\fP"

.PP
Définition à la ligne 16 du fichier OpenGL\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP OpenGL::destroy ()\fC [virtual]\fP"

.PP
Implémente \fBIGraph\fP\&.
.PP
Définition à la ligne 73 du fichier OpenGL\&.cpp\&.
.SS "\fBvoid\fP OpenGL::display (std::stack< \fBAComponent\fP * > components)\fC [virtual]\fP"

.PP
Implémente \fBIGraph\fP\&.
.PP
Définition à la ligne 131 du fichier OpenGL\&.cpp\&.
.SS "\fBint\fP OpenGL::eventManagment ()\fC [virtual]\fP"

.PP
Implémente \fBIGraph\fP\&.
.PP
Définition à la ligne 80 du fichier OpenGL\&.cpp\&.
.SS "\fBvoid\fP OpenGL::init (\fBconst\fP \fBstd::string\fP & name, \fBVector2\fP< \fBint\fP > size, std::stack< \fBAComponent\fP * > cache)\fC [virtual]\fP"

.PP
Implémente \fBIGraph\fP\&.
.PP
Définition à la ligne 30 du fichier OpenGL\&.cpp\&.
.SS "\fBvoid\fP OpenGL::init (\fBconst\fP \fBstd::string\fP & name, \fBVector2\fP< \fBint\fP > size)\fC [virtual]\fP"

.PP
Définition à la ligne 52 du fichier OpenGL\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
