.TH "Pacman" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pacman \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pacman\&.hpp>\fP
.PP
Est dérivée de \fBAGame\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBPacman\fP ()"
.br
.ti -1c
.RI "virtual \fB~Pacman\fP ()"
.br
.ti -1c
.RI "virtual std::stack< \fBAComponent\fP * > \fBcompute\fP (\fBint\fP)"
.br
.ti -1c
.RI "virtual std::stack< \fBAComponent\fP * > \fBgetInfos\fP ()"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBrestart\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBchangeDirection\fP (\fBint\fP key)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBeat\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 26 du fichier Pacman\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Pacman::Pacman ()"

.PP
Définition à la ligne 3 du fichier Pacman\&.cpp\&.
.SS "Pacman::~Pacman ()\fC [virtual]\fP"

.PP
Définition à la ligne 34 du fichier Pacman\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP Pacman::changeDirection (\fBint\fP key)"

.PP
Définition à la ligne 46 du fichier Pacman\&.cpp\&.
.SS "std::stack< \fBAComponent\fP * > Pacman::compute (\fBint\fP key)\fC [virtual]\fP"

.PP
Implémente \fBAGame\fP\&.
.PP
Définition à la ligne 136 du fichier Pacman\&.cpp\&.
.SS "\fBvoid\fP Pacman::eat ()"

.PP
Définition à la ligne 127 du fichier Pacman\&.cpp\&.
.SS "std::stack< \fBAComponent\fP * > Pacman::getInfos (\fBvoid\fP)\fC [virtual]\fP"

.PP
Implémente \fBAGame\fP\&.
.PP
Définition à la ligne 154 du fichier Pacman\&.cpp\&.
.SS "\fBvoid\fP Pacman::move ()"

.PP
Définition à la ligne 98 du fichier Pacman\&.cpp\&.
.SS "\fBvoid\fP Pacman::restart (\fBvoid\fP)\fC [virtual]\fP"

.PP
Implémente \fBAGame\fP\&.
.PP
Définition à la ligne 169 du fichier Pacman\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
