.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/panel.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/panel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses/curses\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpanel\fP"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBpanel\fP \fBPANEL\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBNCURSES_EXPORT\fP (\fBWINDOW\fP *) panel_window(\fBconst\fP \fBPANEL\fP *)"
.br
.ti -1c
.RI "\fBNCURSES_EXPORT\fP (\fBvoid\fP) update_panels(\fBvoid\fP)"
.br
.ti -1c
.RI "\fBNCURSES_EXPORT\fP (\fBint\fP) hide_panel(\fBPANEL\fP *)"
.br
.ti -1c
.RI "\fBNCURSES_EXPORT\fP (\fBPANEL\fP *) new _panel(\fBWINDOW\fP *)"
.br
.ti -1c
.RI "\fBNCURSES_CONST\fP \fBvoid\fP * \fBNCURSES_EXPORT\fP (\fBNCURSES_CONST\fP \fBvoid\fP *) panel_userptr(\fBconst\fP \fBPANEL\fP *)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBint\fP"
.br
.in -1c
.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fBpanel\fP  \fBPANEL\fP"

.SH "Documentation des fonctions"
.PP 
.SS "NCURSES_EXPORT (\fBWINDOW\fP *) const"

.SS "NCURSES_EXPORT (\fBvoid\fP)"

.SS "NCURSES_EXPORT (\fBint\fP)"

.SS "NCURSES_EXPORT (\fBPANEL\fP *)\fC [new]\fP"

.SS "\fBNCURSES_CONST\fP \fBvoid\fP* NCURSES_EXPORT (\fBNCURSES_CONST\fP \fBvoid\fP *) const"

.SH "Documentation des variables"
.PP 
.SS "int"

.PP
Définition à la ligne 68 du fichier panel\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
