.TH "panel" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
panel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <panel\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBWINDOW\fP * \fBwin\fP"
.br
.ti -1c
.RI "struct \fBpanel\fP * \fBbelow\fP"
.br
.ti -1c
.RI "struct \fBpanel\fP * \fBabove\fP"
.br
.ti -1c
.RI "\fBNCURSES_CONST\fP \fBvoid\fP * \fBuser\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 44 du fichier panel\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "struct \fBpanel\fP* panel::above"

.PP
Définition à la ligne 48 du fichier panel\&.h\&.
.SS "struct \fBpanel\fP* panel::below"

.PP
Définition à la ligne 47 du fichier panel\&.h\&.
.SS "\fBNCURSES_CONST\fP \fBvoid\fP* panel::user"

.PP
Définition à la ligne 49 du fichier panel\&.h\&.
.SS "\fBWINDOW\fP* panel::win"

.PP
Définition à la ligne 46 du fichier panel\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
