.TH "Regular_Expression_Field" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Regular_Expression_Field \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursesf\&.h>\fP
.PP
Est dérivée de \fBNCursesFieldType\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBRegular_Expression_Field\fP (\fBconst\fP char *expr)"
.br
.ti -1c
.RI "\fBRegular_Expression_Field\fP & \fBoperator=\fP (\fBconst\fP \fBRegular_Expression_Field\fP &rhs)"
.br
.ti -1c
.RI "\fBRegular_Expression_Field\fP (\fBconst\fP \fBRegular_Expression_Field\fP &rhs)"
.br
.ti -1c
.RI "\fB~Regular_Expression_Field\fP ()"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 791 du fichier cursesf\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Regular_Expression_Field::Regular_Expression_Field (\fBconst\fP char * expr)\fC [inline]\fP"

.PP
Définition à la ligne 807 du fichier cursesf\&.h\&.
.SS "Regular_Expression_Field::Regular_Expression_Field (\fBconst\fP \fBRegular_Expression_Field\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 824 du fichier cursesf\&.h\&.
.SS "Regular_Expression_Field::~Regular_Expression_Field ()\fC [inline]\fP"

.PP
Définition à la ligne 831 du fichier cursesf\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBRegular_Expression_Field\fP& Regular_Expression_Field::operator= (\fBconst\fP \fBRegular_Expression_Field\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 814 du fichier cursesf\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
