.TH "s_header" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScoreComponent\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmagicNbr\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheaderSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBfileSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnbrHighScore\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 21 du fichier ScoreComponent\&.hpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP s_header::fileSize"

.PP
Définition à la ligne 24 du fichier ScoreComponent\&.hpp\&.
.SS "\fBint\fP s_header::headerSize"

.PP
Définition à la ligne 23 du fichier ScoreComponent\&.hpp\&.
.SS "\fBint\fP s_header::magicNbr"

.PP
Définition à la ligne 22 du fichier ScoreComponent\&.hpp\&.
.SS "\fBint\fP s_header::nbrHighScore"

.PP
Définition à la ligne 25 du fichier ScoreComponent\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
