.TH "s_highScore" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_highScore \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScoreComponent\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char \fBname\fP [20]"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBscore\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 28 du fichier ScoreComponent\&.hpp\&.
.SH "Documentation des données membres"
.PP 
.SS "char s_highScore::name[20]"

.PP
Définition à la ligne 29 du fichier ScoreComponent\&.hpp\&.
.SS "unsigned \fBint\fP s_highScore::score"

.PP
Définition à la ligne 30 du fichier ScoreComponent\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
