.TH "s_phantom" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_phantom \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pacman\&.hpp>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBdirection\fP \fBdir\fP"
.br
.ti -1c
.RI "\fBGameComponent\fP \fBg\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 27 du fichier Pacman\&.hpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBdirection\fP s_phantom::dir"

.PP
Définition à la ligne 28 du fichier Pacman\&.hpp\&.
.SS "\fBGameComponent\fP s_phantom::g"

.PP
Définition à la ligne 29 du fichier Pacman\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
