.TH "ScoreComponent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScoreComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScoreComponent\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBScoreComponent\fP (\fBconst\fP \fBstd::string\fP &game)"
.br
.ti -1c
.RI "virtual \fB~ScoreComponent\fP ()"
.br
.ti -1c
.RI "size_t \fBgetScore\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBUIComponent\fP * \fBgetScoreUI\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetScore\fP (size_t score)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwriteScore\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 33 du fichier ScoreComponent\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "ScoreComponent::ScoreComponent (\fBconst\fP \fBstd::string\fP & game)"

.PP
Définition à la ligne 13 du fichier ScoreComponent\&.cpp\&.
.SS "ScoreComponent::~ScoreComponent ()\fC [virtual]\fP"

.PP
Définition à la ligne 31 du fichier ScoreComponent\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "size_t ScoreComponent::getScore () const"

.PP
Définition à la ligne 36 du fichier ScoreComponent\&.cpp\&.
.SS "\fBUIComponent\fP * ScoreComponent::getScoreUI ()"

.PP
Définition à la ligne 41 du fichier ScoreComponent\&.cpp\&.
.SS "\fBvoid\fP ScoreComponent::setScore (size_t score)"

.PP
Définition à la ligne 47 du fichier ScoreComponent\&.cpp\&.
.SS "\fBvoid\fP ScoreComponent::writeScore ()"

.PP
Définition à la ligne 52 du fichier ScoreComponent\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
