.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/lib/sdl2/Sdl2.hpp" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/lib/sdl2/Sdl2.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL\&.h'\fP
.br
\fC#include 'SDL_image\&.h'\fP
.br
\fC#include 'SDL_ttf\&.h'\fP
.br
\fC#include <exception>\fP
.br
\fC#include <stack>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'IGraph\&.hpp'\fP
.br
\fC#include 'GameComponent\&.hpp'\fP
.br
\fC#include 'UIComponent\&.hpp'\fP
.br
\fC#include 'BackgroundComponent\&.hpp'\fP
.br
\fC#include 'UIAdvanceComponent\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSdl2\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTEP\fP   30"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBIGraph\fP * \fBloadLib\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBinitLib\fP (\fBIGraph\fP *graph, \fBconst\fP \fBstd::string\fP &\fBname\fP, \fBVector2\fP< double > \fBsize\fP, std::stack< \fBAComponent\fP * > cache)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdestroyLib\fP (\fBIGraph\fP *graph)"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define STEP   30"

.PP
Définition à la ligne 19 du fichier Sdl2\&.hpp\&.
.SH "Documentation des fonctions"
.PP 
.SS "\fBvoid\fP destroyLib (\fBIGraph\fP * graph)"

.PP
Définition à la ligne 86 du fichier Sdl2\&.hpp\&.
.SS "\fBvoid\fP initLib (\fBIGraph\fP * graph, \fBconst\fP \fBstd::string\fP & name, \fBVector2\fP< double > size, std::stack< \fBAComponent\fP * > cache)"

.PP
Définition à la ligne 81 du fichier Sdl2\&.hpp\&.
.SS "\fBIGraph\fP* loadLib ()"

.PP
Définition à la ligne 76 du fichier Sdl2\&.hpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
