.TH "SDL_MessageBoxColorScheme" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxColorScheme \- A set of colors to use for message box dialogs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBSDL_MessageBoxColor\fP \fBcolors\fP [\fBSDL_MESSAGEBOX_COLOR_MAX\fP]"
.br
.in -1c
.SH "Description détaillée"
.PP 
A set of colors to use for message box dialogs\&. 
.PP
Définition à la ligne 84 du fichier SDL_messagebox\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBSDL_MessageBoxColor\fP SDL_MessageBoxColorScheme::colors[\fBSDL_MESSAGEBOX_COLOR_MAX\fP]"

.PP
Définition à la ligne 86 du fichier SDL_messagebox\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
