.TH "SDL_Finger" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Finger \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_touch\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBSDL_FingerID\fP \fBid\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBpressure\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 44 du fichier SDL_touch\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBSDL_FingerID\fP SDL_Finger::id"

.PP
Définition à la ligne 46 du fichier SDL_touch\&.h\&.
.SS "float SDL_Finger::pressure"

.PP
Définition à la ligne 49 du fichier SDL_touch\&.h\&.
.SS "float SDL_Finger::x"

.PP
Définition à la ligne 47 du fichier SDL_touch\&.h\&.
.SS "float SDL_Finger::y"

.PP
Définition à la ligne 48 du fichier SDL_touch\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
