.TH "SDL_OSEvent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_OSEvent \- OS Specific event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBtimestamp\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
OS Specific event\&. 
.PP
Définition à la ligne 482 du fichier SDL_events\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBUint32\fP SDL_OSEvent::timestamp"

.PP
Définition à la ligne 485 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_OSEvent::type"
\fBSDL_QUIT\fP 
.PP
Définition à la ligne 484 du fichier SDL_events\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
