.TH "SDL_atomic_t" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_atomic_t \- A type representing an atomic integer value\&. It is a struct so people don't accidentally use numeric operations on it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_atomic\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBint\fP \fBvalue\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
A type representing an atomic integer value\&. It is a struct so people don't accidentally use numeric operations on it\&. 
.PP
Définition à la ligne 189 du fichier SDL_atomic\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP SDL_atomic_t::value"

.PP
Définition à la ligne 189 du fichier SDL_atomic\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
