.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_test_log.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_test_log.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBSDLTest_Log\fP (\fBSDL_PRINTF_FORMAT_STRING\fP \fBconst\fP char *fmt,\&.\&.\&.) \fBSDL_PRINTF_VARARG_FUNC\fP(1)"
.br
.RI "\fIPrints given message with a timestamp in the TEST category and INFO priority\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBSDLTest_LogError\fP (\fBSDL_PRINTF_FORMAT_STRING\fP \fBconst\fP char *fmt,\&.\&.\&.) \fBSDL_PRINTF_VARARG_FUNC\fP(1)"
.br
.RI "\fIPrints given message with a timestamp in the TEST category and the ERROR priority\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Include file for SDL test framework\&.
.PP
This code is a part of the SDL2_test library, not the main SDL library\&. 
.PP
Définition dans le fichier \fBSDL_test_log\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "\fBvoid\fP SDLTest_Log (\fBSDL_PRINTF_FORMAT_STRING\fP \fBconst\fP char * fmt,  \&.\&.\&.)"

.PP
Prints given message with a timestamp in the TEST category and INFO priority\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIfmt\fP Message to be logged 
.RE
.PP

.SS "\fBvoid\fP SDLTest_LogError (\fBSDL_PRINTF_FORMAT_STRING\fP \fBconst\fP char * fmt,  \&.\&.\&.)"

.PP
Prints given message with a timestamp in the TEST category and the ERROR priority\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIfmt\fP Message to be logged 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
