.TH "SDL_MessageBoxColor" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxColor \- RGB value used in a message box color scheme\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBr\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBg\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBb\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
RGB value used in a message box color scheme\&. 
.PP
Définition à la ligne 66 du fichier SDL_messagebox\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBUint8\fP SDL_MessageBoxColor::b"

.PP
Définition à la ligne 68 du fichier SDL_messagebox\&.h\&.
.SS "\fBUint8\fP SDL_MessageBoxColor::g"

.PP
Définition à la ligne 68 du fichier SDL_messagebox\&.h\&.
.SS "\fBUint8\fP SDL_MessageBoxColor::r"

.PP
Définition à la ligne 68 du fichier SDL_messagebox\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
