.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_types.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_stdinc\&.h'\fP
.br

.SH "Description détaillée"
.PP 

.PP
\fBObsolète\fP
.RS 4

.RE
.PP

.PP
Définition dans le fichier \fBSDL_types\&.h\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
