.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_platform.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_platform.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBDECLSPEC\fP \fBconst\fP char *\fBSDLCALL\fP \fBSDL_GetPlatform\fP (\fBvoid\fP)"
.br
.RI "\fIGets the name of the platform\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Try to get a standard set of platform defines\&. 
.PP
Définition dans le fichier \fBSDL_platform\&.h\fP\&.
.SH "Documentation des fonctions"
.PP 
.SS "\fBDECLSPEC\fP \fBconst\fP char* \fBSDLCALL\fP SDL_GetPlatform (\fBvoid\fP)"

.PP
Gets the name of the platform\&. 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
