.TH "SDL_MouseMotionEvent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MouseMotionEvent \- Mouse motion event structure (event\&.motion\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBwindowID\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBwhich\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBSint32\fP \fBx\fP"
.br
.ti -1c
.RI "\fBSint32\fP \fBy\fP"
.br
.ti -1c
.RI "\fBSint32\fP \fBxrel\fP"
.br
.ti -1c
.RI "\fBSint32\fP \fByrel\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Mouse motion event structure (event\&.motion\&.*) 
.PP
Définition à la ligne 229 du fichier SDL_events\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBUint32\fP SDL_MouseMotionEvent::state"
The current button state 
.PP
Définition à la ligne 235 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_MouseMotionEvent::timestamp"

.PP
Définition à la ligne 232 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_MouseMotionEvent::type"
\fBSDL_MOUSEMOTION\fP 
.PP
Définition à la ligne 231 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_MouseMotionEvent::which"
The mouse instance id, or SDL_TOUCH_MOUSEID 
.PP
Définition à la ligne 234 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_MouseMotionEvent::windowID"
The window with mouse focus, if any 
.PP
Définition à la ligne 233 du fichier SDL_events\&.h\&.
.SS "\fBSint32\fP SDL_MouseMotionEvent::x"
X coordinate, relative to window 
.PP
Définition à la ligne 236 du fichier SDL_events\&.h\&.
.SS "\fBSint32\fP SDL_MouseMotionEvent::xrel"
The relative motion in the X direction 
.PP
Définition à la ligne 238 du fichier SDL_events\&.h\&.
.SS "\fBSint32\fP SDL_MouseMotionEvent::y"
Y coordinate, relative to window 
.PP
Définition à la ligne 237 du fichier SDL_events\&.h\&.
.SS "\fBSint32\fP SDL_MouseMotionEvent::yrel"
The relative motion in the Y direction 
.PP
Définition à la ligne 239 du fichier SDL_events\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
