.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_test.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_test.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL\&.h'\fP
.br
\fC#include 'SDL_test_common\&.h'\fP
.br
\fC#include 'SDL_test_font\&.h'\fP
.br
\fC#include 'SDL_test_random\&.h'\fP
.br
\fC#include 'SDL_test_fuzzer\&.h'\fP
.br
\fC#include 'SDL_test_crc32\&.h'\fP
.br
\fC#include 'SDL_test_md5\&.h'\fP
.br
\fC#include 'SDL_test_log\&.h'\fP
.br
\fC#include 'SDL_test_assert\&.h'\fP
.br
\fC#include 'SDL_test_harness\&.h'\fP
.br
\fC#include 'SDL_test_images\&.h'\fP
.br
\fC#include 'SDL_test_compare\&.h'\fP
.br
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDLTEST_MAX_LOGMESSAGE_LENGTH\fP   3584"
.br
.in -1c
.SH "Description détaillée"
.PP 
Include file for SDL test framework\&.
.PP
This code is a part of the SDL2_test library, not the main SDL library\&. 
.PP
Définition dans le fichier \fBSDL_test\&.h\fP\&.
.SH "Documentation des macros"
.PP 
.SS "#define SDLTEST_MAX_LOGMESSAGE_LENGTH   3584"

.PP
Définition à la ligne 58 du fichier SDL_test\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
