.TH "SDL_MessageBoxButtonData" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxButtonData \- Individual button data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBint\fP \fBbuttonid\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBtext\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Individual button data\&. 
.PP
Définition à la ligne 56 du fichier SDL_messagebox\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP SDL_MessageBoxButtonData::buttonid"
User defined button id (value returned via SDL_ShowMessageBox) 
.PP
Définition à la ligne 59 du fichier SDL_messagebox\&.h\&.
.SS "\fBUint32\fP SDL_MessageBoxButtonData::flags"
\fBSDL_MessageBoxButtonFlags\fP 
.PP
Définition à la ligne 58 du fichier SDL_messagebox\&.h\&.
.SS "\fBconst\fP char* SDL_MessageBoxButtonData::text"
The UTF-8 button text 
.PP
Définition à la ligne 60 du fichier SDL_messagebox\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
