.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_config.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_config.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_platform\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZEOF_VOIDP\fP   4"
.br
.ti -1c
.RI "#define \fBHAVE_GCC_ATOMICS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIBC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ALLOCA_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDIO_H\fP   1"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDARG_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MALLOC_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CTYPE_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MATH_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ICONV_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIGNAL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIBUDEV_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_REALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FREE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ALLOCA\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PUTENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNSETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_QSORT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_BCOPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMMOVE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLEN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRDUP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRSTR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOUL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOLL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOULL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOD\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOI\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRNCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRNCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VSSCANF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VSNPRINTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_M_PI\fP"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN2\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ACOS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ASIN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CEIL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COPYSIGN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COSF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FLOOR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LOG\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_POW\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SCALBN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SINF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TAN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_TANF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FSEEKO\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FSEEKO64\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIGACTION\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SA_SIGACTION\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETJMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_NANOSLEEP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYSCONF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CLOCK_GETTIME\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MPROTECT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ICONV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PTHREAD_SETNAME_NP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SEM_TIMEDWAIT\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_ALSA\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_ALSA_DYNAMIC\fP   'libasound\&.so\&.2'"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DISK\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_OSS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_INPUT_LINUXEV\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_INPUT_LINUXKD\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_LINUX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_HAPTIC_LINUX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_LOADSO_DLOPEN\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_PTHREAD\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_PTHREAD_RECURSIVE_MUTEX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_TIMER_UNIX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_WAYLAND\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_WAYLAND_QT_TOUCH\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_WAYLAND_DYNAMIC\fP   'libwayland\-client\&.so\&.0'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_EGL\fP   'libwayland\-egl\&.so\&.1'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_CURSOR\fP   'libwayland\-cursor\&.so\&.0'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_XKBCOMMON\fP   'libxkbcommon\&.so\&.0'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC\fP   'libX11\&.so\&.6'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT\fP   'libXext\&.so\&.6'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR\fP   'libXcursor\&.so\&.1'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XINERAMA\fP   'libXinerama\&.so\&.1'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2\fP   'libXi\&.so\&.6'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR\fP   'libXrandr\&.so\&.2'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XSS\fP   'libXss\&.so\&.1'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_DYNAMIC_XVIDMODE\fP   'libXxf86vm\&.so\&.1'"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XCURSOR\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XDBE\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XINERAMA\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XINPUT2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XRANDR\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XSCRNSAVER\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XSHAPE\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_XVIDMODE\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_CONST_PARAM_XEXTADDDISPLAY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_OGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_OGL_ES2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_ES2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_EGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_GLX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_POWER_LINUX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_FILESYSTEM_UNIX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_ASSEMBLY_ROUTINES\fP   1"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define HAVE_ABS   1"

.PP
Définition à la ligne 100 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ACOS   1"

.PP
Définition à la ligne 144 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ALLOCA   1"

.PP
Définition à la ligne 92 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ALLOCA_H   1"

.PP
Définition à la ligne 65 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ASIN   1"

.PP
Définition à la ligne 145 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ATAN   1"

.PP
Définition à la ligne 142 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ATAN2   1"

.PP
Définition à la ligne 143 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ATOF   1"

.PP
Définition à la ligne 130 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ATOI   1"

.PP
Définition à la ligne 129 du fichier SDL_config\&.h\&.
.SS "#define HAVE_BCOPY   1"

.PP
Définition à la ligne 101 du fichier SDL_config\&.h\&.
.SS "#define HAVE_CALLOC   1"

.PP
Définition à la ligne 89 du fichier SDL_config\&.h\&.
.SS "#define HAVE_CEIL   1"

.PP
Définition à la ligne 146 du fichier SDL_config\&.h\&.
.SS "#define HAVE_CLOCK_GETTIME   1"

.PP
Définition à la ligne 169 du fichier SDL_config\&.h\&.
.SS "#define HAVE_COPYSIGN   1"

.PP
Définition à la ligne 147 du fichier SDL_config\&.h\&.
.SS "#define HAVE_COS   1"

.PP
Définition à la ligne 148 du fichier SDL_config\&.h\&.
.SS "#define HAVE_COSF   1"

.PP
Définition à la ligne 149 du fichier SDL_config\&.h\&.
.SS "#define HAVE_CTYPE_H   1"

.PP
Définition à la ligne 77 du fichier SDL_config\&.h\&.
.SS "#define HAVE_FABS   1"

.PP
Définition à la ligne 150 du fichier SDL_config\&.h\&.
.SS "#define HAVE_FLOOR   1"

.PP
Définition à la ligne 151 du fichier SDL_config\&.h\&.
.SS "#define HAVE_FREE   1"

.PP
Définition à la ligne 91 du fichier SDL_config\&.h\&.
.SS "#define HAVE_FSEEKO   1"

.PP
Définition à la ligne 161 du fichier SDL_config\&.h\&.
.SS "#define HAVE_FSEEKO64   1"

.PP
Définition à la ligne 162 du fichier SDL_config\&.h\&.
.SS "#define HAVE_GCC_ATOMICS   1"

.PP
Définition à la ligne 51 du fichier SDL_config\&.h\&.
.SS "#define HAVE_GETENV   1"

.PP
Définition à la ligne 94 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ICONV   1"

.PP
Définition à la ligne 172 du fichier SDL_config\&.h\&.
.SS "#define HAVE_ICONV_H   1"

.PP
Définition à la ligne 79 du fichier SDL_config\&.h\&.
.SS "#define HAVE_INTTYPES_H   1"

.PP
Définition à la ligne 75 du fichier SDL_config\&.h\&.
.SS "#define HAVE_LIBC   1"

.PP
Définition à la ligne 61 du fichier SDL_config\&.h\&.
.SS "#define HAVE_LIBUDEV_H   1"

.PP
Définition à la ligne 83 du fichier SDL_config\&.h\&.
.SS "#define HAVE_LOG   1"

.PP
Définition à la ligne 152 du fichier SDL_config\&.h\&.
.SS "#define HAVE_M_PI"

.PP
Définition à la ligne 141 du fichier SDL_config\&.h\&.
.SS "#define HAVE_MALLOC   1"

.PP
Définition à la ligne 88 du fichier SDL_config\&.h\&.
.SS "#define HAVE_MALLOC_H   1"

.PP
Définition à la ligne 71 du fichier SDL_config\&.h\&.
.SS "#define HAVE_MATH_H   1"

.PP
Définition à la ligne 78 du fichier SDL_config\&.h\&.
.SS "#define HAVE_MEMCMP   1"

.PP
Définition à la ligne 105 du fichier SDL_config\&.h\&.
.SS "#define HAVE_MEMCPY   1"

.PP
Définition à la ligne 103 du fichier SDL_config\&.h\&.
.SS "#define HAVE_MEMMOVE   1"

.PP
Définition à la ligne 104 du fichier SDL_config\&.h\&.
.SS "#define HAVE_MEMORY_H   1"

.PP
Définition à la ligne 72 du fichier SDL_config\&.h\&.
.SS "#define HAVE_MEMSET   1"

.PP
Définition à la ligne 102 du fichier SDL_config\&.h\&.
.SS "#define HAVE_MPROTECT   1"

.PP
Définition à la ligne 171 du fichier SDL_config\&.h\&.
.SS "#define HAVE_NANOSLEEP   1"

.PP
Définition à la ligne 166 du fichier SDL_config\&.h\&.
.SS "#define HAVE_POW   1"

.PP
Définition à la ligne 153 du fichier SDL_config\&.h\&.
.SS "#define HAVE_PTHREAD_SETNAME_NP   1"

.PP
Définition à la ligne 173 du fichier SDL_config\&.h\&.
.SS "#define HAVE_PUTENV   1"

.PP
Définition à la ligne 96 du fichier SDL_config\&.h\&.
.SS "#define HAVE_QSORT   1"

.PP
Définition à la ligne 99 du fichier SDL_config\&.h\&.
.SS "#define HAVE_REALLOC   1"

.PP
Définition à la ligne 90 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SA_SIGACTION   1"

.PP
Définition à la ligne 164 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SCALBN   1"

.PP
Définition à la ligne 154 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SEM_TIMEDWAIT   1"

.PP
Définition à la ligne 175 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SETENV   1"

.PP
Définition à la ligne 95 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SETJMP   1"

.PP
Définition à la ligne 165 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SIGACTION   1"

.PP
Définition à la ligne 163 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SIGNAL_H   1"

.PP
Définition à la ligne 80 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SIN   1"

.PP
Définition à la ligne 155 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SINF   1"

.PP
Définition à la ligne 156 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SQRT   1"

.PP
Définition à la ligne 157 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SQRTF   1"

.PP
Définition à la ligne 158 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STDARG_H   1"

.PP
Définition à la ligne 70 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STDINT_H   1"

.PP
Définition à la ligne 76 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STDIO_H   1"

.PP
Définition à la ligne 67 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STDLIB_H   1"

.PP
Définition à la ligne 69 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRCASECMP   1"

.PP
Définition à la ligne 134 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRCHR   1"

.PP
Définition à la ligne 115 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRCMP   1"

.PP
Définition à la ligne 131 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRDUP   1"

.PP
Définition à la ligne 109 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRING_H   1"

.PP
Définition à la ligne 73 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRINGS_H   1"

.PP
Définition à la ligne 74 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRLEN   1"

.PP
Définition à la ligne 106 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRNCASECMP   1"

.PP
Définition à la ligne 136 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRNCMP   1"

.PP
Définition à la ligne 132 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRRCHR   1"

.PP
Définition à la ligne 116 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRSTR   1"

.PP
Définition à la ligne 117 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRTOD   1"

.PP
Définition à la ligne 128 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRTOL   1"

.PP
Définition à la ligne 122 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRTOLL   1"

.PP
Définition à la ligne 126 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRTOUL   1"

.PP
Définition à la ligne 123 du fichier SDL_config\&.h\&.
.SS "#define HAVE_STRTOULL   1"

.PP
Définition à la ligne 127 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SYS_TYPES_H   1"

.PP
Définition à la ligne 66 du fichier SDL_config\&.h\&.
.SS "#define HAVE_SYSCONF   1"

.PP
Définition à la ligne 167 du fichier SDL_config\&.h\&.
.SS "#define HAVE_TAN   1"

.PP
Définition à la ligne 159 du fichier SDL_config\&.h\&.
.SS "#define HAVE_TANF   1"

.PP
Définition à la ligne 160 du fichier SDL_config\&.h\&.
.SS "#define HAVE_UNSETENV   1"

.PP
Définition à la ligne 97 du fichier SDL_config\&.h\&.
.SS "#define HAVE_VSNPRINTF   1"

.PP
Définition à la ligne 140 du fichier SDL_config\&.h\&.
.SS "#define HAVE_VSSCANF   1"

.PP
Définition à la ligne 138 du fichier SDL_config\&.h\&.
.SS "#define SDL_ASSEMBLY_ROUTINES   1"

.PP
Définition à la ligne 357 du fichier SDL_config\&.h\&.
.SS "#define SDL_AUDIO_DRIVER_ALSA   1"

.PP
Définition à la ligne 203 du fichier SDL_config\&.h\&.
.SS "#define SDL_AUDIO_DRIVER_ALSA_DYNAMIC   'libasound\&.so\&.2'"

.PP
Définition à la ligne 204 du fichier SDL_config\&.h\&.
.SS "#define SDL_AUDIO_DRIVER_DISK   1"

.PP
Définition à la ligne 212 du fichier SDL_config\&.h\&.
.SS "#define SDL_AUDIO_DRIVER_DUMMY   1"

.PP
Définition à la ligne 213 du fichier SDL_config\&.h\&.
.SS "#define SDL_AUDIO_DRIVER_OSS   1"

.PP
Définition à la ligne 224 du fichier SDL_config\&.h\&.
.SS "#define SDL_FILESYSTEM_UNIX   1"

.PP
Définition à la ligne 350 du fichier SDL_config\&.h\&.
.SS "#define SDL_HAPTIC_LINUX   1"

.PP
Définition à la ligne 250 du fichier SDL_config\&.h\&.
.SS "#define SDL_INPUT_LINUXEV   1"

.PP
Définition à la ligne 235 du fichier SDL_config\&.h\&.
.SS "#define SDL_INPUT_LINUXKD   1"

.PP
Définition à la ligne 236 du fichier SDL_config\&.h\&.
.SS "#define SDL_JOYSTICK_LINUX   1"

.PP
Définition à la ligne 243 du fichier SDL_config\&.h\&.
.SS "#define SDL_LOADSO_DLOPEN   1"

.PP
Définition à la ligne 257 du fichier SDL_config\&.h\&.
.SS "#define SDL_POWER_LINUX   1"

.PP
Définition à la ligne 338 du fichier SDL_config\&.h\&.
.SS "#define SDL_THREAD_PTHREAD   1"

.PP
Définition à la ligne 263 du fichier SDL_config\&.h\&.
.SS "#define SDL_THREAD_PTHREAD_RECURSIVE_MUTEX   1"

.PP
Définition à la ligne 264 du fichier SDL_config\&.h\&.
.SS "#define SDL_TIMER_UNIX   1"

.PP
Définition à la ligne 271 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_DUMMY   1"

.PP
Définition à la ligne 279 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_WAYLAND   1"

.PP
Définition à la ligne 281 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC   'libwayland\-client\&.so\&.0'"

.PP
Définition à la ligne 283 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_CURSOR   'libwayland\-cursor\&.so\&.0'"

.PP
Définition à la ligne 285 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_EGL   'libwayland\-egl\&.so\&.1'"

.PP
Définition à la ligne 284 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_XKBCOMMON   'libxkbcommon\&.so\&.0'"

.PP
Définition à la ligne 286 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_WAYLAND_QT_TOUCH   1"

.PP
Définition à la ligne 282 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11   1"

.PP
Définition à la ligne 290 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_CONST_PARAM_XEXTADDDISPLAY   1"

.PP
Définition à la ligne 312 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC   'libX11\&.so\&.6'"

.PP
Définition à la ligne 294 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR   'libXcursor\&.so\&.1'"

.PP
Définition à la ligne 296 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT   'libXext\&.so\&.6'"

.PP
Définition à la ligne 295 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XINERAMA   'libXinerama\&.so\&.1'"

.PP
Définition à la ligne 297 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2   'libXi\&.so\&.6'"

.PP
Définition à la ligne 298 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR   'libXrandr\&.so\&.2'"

.PP
Définition à la ligne 299 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XSS   'libXss\&.so\&.1'"

.PP
Définition à la ligne 300 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XVIDMODE   'libXxf86vm\&.so\&.1'"

.PP
Définition à la ligne 301 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM   1"

.PP
Définition à la ligne 313 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS   1"

.PP
Définition à la ligne 311 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_XCURSOR   1"

.PP
Définition à la ligne 302 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_XDBE   1"

.PP
Définition à la ligne 303 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_XINERAMA   1"

.PP
Définition à la ligne 304 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_XINPUT2   1"

.PP
Définition à la ligne 305 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH   1"

.PP
Définition à la ligne 306 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_XRANDR   1"

.PP
Définition à la ligne 307 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_XSCRNSAVER   1"

.PP
Définition à la ligne 308 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_XSHAPE   1"

.PP
Définition à la ligne 309 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_DRIVER_X11_XVIDMODE   1"

.PP
Définition à la ligne 310 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_OPENGL   1"

.PP
Définition à la ligne 326 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_OPENGL_EGL   1"

.PP
Définition à la ligne 331 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_OPENGL_ES2   1"

.PP
Définition à la ligne 328 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_OPENGL_GLX   1"

.PP
Définition à la ligne 332 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_RENDER_OGL   1"

.PP
Définition à la ligne 320 du fichier SDL_config\&.h\&.
.SS "#define SDL_VIDEO_RENDER_OGL_ES2   1"

.PP
Définition à la ligne 322 du fichier SDL_config\&.h\&.
.SS "#define SIZEOF_VOIDP   4"

.PP
Définition à la ligne 49 du fichier SDL_config\&.h\&.
.SS "#define STDC_HEADERS   1"

.PP
Définition à la ligne 68 du fichier SDL_config\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
