.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_name.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_name.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDL_NAME\fP(X)   SDL_##X"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define SDL_NAME(X)   SDL_##X"

.PP
Définition à la ligne 29 du fichier SDL_name\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
