.TH "SDL_Palette" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Palette \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_pixels\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBint\fP \fBncolors\fP"
.br
.ti -1c
.RI "\fBSDL_Color\fP * \fBcolors\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBversion\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrefcount\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 288 du fichier SDL_pixels\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBSDL_Color\fP* SDL_Palette::colors"

.PP
Définition à la ligne 291 du fichier SDL_pixels\&.h\&.
.SS "\fBint\fP SDL_Palette::ncolors"

.PP
Définition à la ligne 290 du fichier SDL_pixels\&.h\&.
.SS "\fBint\fP SDL_Palette::refcount"

.PP
Définition à la ligne 293 du fichier SDL_pixels\&.h\&.
.SS "\fBUint32\fP SDL_Palette::version"

.PP
Définition à la ligne 292 du fichier SDL_pixels\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
