.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_opengles2_khrplatform.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_opengles2_khrplatform.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKHRONOS_APICALL\fP"
.br
.ti -1c
.RI "#define \fBKHRONOS_APIENTRY\fP"
.br
.ti -1c
.RI "#define \fBKHRONOS_APIATTRIBUTES\fP"
.br
.ti -1c
.RI "#define \fBKHRONOS_SUPPORT_INT64\fP   1"
.br
.ti -1c
.RI "#define \fBKHRONOS_SUPPORT_FLOAT\fP   1"
.br
.ti -1c
.RI "#define \fBKHRONOS_MAX_ENUM\fP   0x7FFFFFFF"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef int32_t \fBkhronos_int32_t\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBkhronos_uint32_t\fP"
.br
.ti -1c
.RI "typedef int64_t \fBkhronos_int64_t\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBkhronos_uint64_t\fP"
.br
.ti -1c
.RI "typedef signed char \fBkhronos_int8_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBkhronos_uint8_t\fP"
.br
.ti -1c
.RI "typedef signed short \fBint\fP \fBkhronos_int16_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBint\fP \fBkhronos_uint16_t\fP"
.br
.ti -1c
.RI "typedef signed long \fBint\fP \fBkhronos_intptr_t\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBint\fP \fBkhronos_uintptr_t\fP"
.br
.ti -1c
.RI "typedef signed long \fBint\fP \fBkhronos_ssize_t\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBint\fP \fBkhronos_usize_t\fP"
.br
.ti -1c
.RI "typedef float \fBkhronos_float_t\fP"
.br
.ti -1c
.RI "typedef \fBkhronos_uint64_t\fP \fBkhronos_utime_nanoseconds_t\fP"
.br
.ti -1c
.RI "typedef \fBkhronos_int64_t\fP \fBkhronos_stime_nanoseconds_t\fP"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBkhronos_boolean_enum_t\fP { \fBKHRONOS_FALSE\fP = 0, \fBKHRONOS_TRUE\fP = 1, \fBKHRONOS_BOOLEAN_ENUM_FORCE_SIZE\fP = KHRONOS_MAX_ENUM }"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define KHRONOS_APIATTRIBUTES"

.PP
Définition à la ligne 129 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "#define KHRONOS_APICALL"

.PP
Définition à la ligne 105 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "#define KHRONOS_APIENTRY"

.PP
Définition à la ligne 118 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "#define KHRONOS_MAX_ENUM   0x7FFFFFFF"

.PP
Définition à la ligne 267 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "#define KHRONOS_SUPPORT_FLOAT   1"

.PP
Définition à la ligne 212 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "#define KHRONOS_SUPPORT_INT64   1"

.PP
Définition à la ligne 211 du fichier SDL_opengles2_khrplatform\&.h\&.
.SH "Documentation des définitions de type"
.PP 
.SS "typedef float \fBkhronos_float_t\fP"

.PP
Définition à la ligne 246 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef signed short \fBint\fP \fBkhronos_int16_t\fP"

.PP
Définition à la ligne 222 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef int32_t \fBkhronos_int32_t\fP"

.PP
Définition à la ligne 207 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef int64_t \fBkhronos_int64_t\fP"

.PP
Définition à la ligne 209 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef signed char \fBkhronos_int8_t\fP"

.PP
Définition à la ligne 220 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef signed long \fBint\fP \fBkhronos_intptr_t\fP"

.PP
Définition à la ligne 236 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef signed long \fBint\fP \fBkhronos_ssize_t\fP"

.PP
Définition à la ligne 238 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef \fBkhronos_int64_t\fP \fBkhronos_stime_nanoseconds_t\fP"

.PP
Définition à la ligne 260 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef unsigned short \fBint\fP \fBkhronos_uint16_t\fP"

.PP
Définition à la ligne 223 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef uint32_t \fBkhronos_uint32_t\fP"

.PP
Définition à la ligne 208 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef uint64_t \fBkhronos_uint64_t\fP"

.PP
Définition à la ligne 210 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef unsigned char \fBkhronos_uint8_t\fP"

.PP
Définition à la ligne 221 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef unsigned long \fBint\fP \fBkhronos_uintptr_t\fP"

.PP
Définition à la ligne 237 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef unsigned long \fBint\fP \fBkhronos_usize_t\fP"

.PP
Définition à la ligne 239 du fichier SDL_opengles2_khrplatform\&.h\&.
.SS "typedef \fBkhronos_uint64_t\fP \fBkhronos_utime_nanoseconds_t\fP"

.PP
Définition à la ligne 259 du fichier SDL_opengles2_khrplatform\&.h\&.
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBkhronos_boolean_enum_t\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIKHRONOS_FALSE \fP\fP
.TP
\fB\fIKHRONOS_TRUE \fP\fP
.TP
\fB\fIKHRONOS_BOOLEAN_ENUM_FORCE_SIZE \fP\fP
.PP
Définition à la ligne 276 du fichier SDL_opengles2_khrplatform\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
