.TH "SDL_JoystickGUID" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_JoystickGUID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_joystick\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBdata\fP [16]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 68 du fichier SDL_joystick\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBUint8\fP SDL_JoystickGUID::data[16]"

.PP
Définition à la ligne 69 du fichier SDL_joystick\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
