.TH "SDL_MultiGestureEvent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MultiGestureEvent \- Multiple Finger Gesture Event (event\&.mgesture\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBSDL_TouchID\fP \fBtouchId\fP"
.br
.ti -1c
.RI "float \fBdTheta\fP"
.br
.ti -1c
.RI "float \fBdDist\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "\fBUint16\fP \fBnumFingers\fP"
.br
.ti -1c
.RI "\fBUint16\fP \fBpadding\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Multiple Finger Gesture Event (event\&.mgesture\&.*) 
.PP
Définition à la ligne 427 du fichier SDL_events\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "float SDL_MultiGestureEvent::dDist"

.PP
Définition à la ligne 433 du fichier SDL_events\&.h\&.
.SS "float SDL_MultiGestureEvent::dTheta"

.PP
Définition à la ligne 432 du fichier SDL_events\&.h\&.
.SS "\fBUint16\fP SDL_MultiGestureEvent::numFingers"

.PP
Définition à la ligne 436 du fichier SDL_events\&.h\&.
.SS "\fBUint16\fP SDL_MultiGestureEvent::padding"

.PP
Définition à la ligne 437 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_MultiGestureEvent::timestamp"

.PP
Définition à la ligne 430 du fichier SDL_events\&.h\&.
.SS "\fBSDL_TouchID\fP SDL_MultiGestureEvent::touchId"
The touch device index 
.PP
Définition à la ligne 431 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_MultiGestureEvent::type"
\fBSDL_MULTIGESTURE\fP 
.PP
Définition à la ligne 429 du fichier SDL_events\&.h\&.
.SS "float SDL_MultiGestureEvent::x"

.PP
Définition à la ligne 434 du fichier SDL_events\&.h\&.
.SS "float SDL_MultiGestureEvent::y"

.PP
Définition à la ligne 435 du fichier SDL_events\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
