.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_test_common.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_test_common.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL\&.h'\fP
.br
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSDLTest_CommonState\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_WINDOW_WIDTH\fP   640"
.br
.ti -1c
.RI "#define \fBDEFAULT_WINDOW_HEIGHT\fP   480"
.br
.ti -1c
.RI "#define \fBVERBOSE_VIDEO\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBVERBOSE_MODES\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBVERBOSE_RENDER\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBVERBOSE_EVENT\fP   0x00000008"
.br
.ti -1c
.RI "#define \fBVERBOSE_AUDIO\fP   0x00000010"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBSDLTest_CommonState\fP * \fBSDLTest_CommonCreateState\fP (char **argv, \fBUint32\fP \fBflags\fP)"
.br
.RI "\fIParse command line parameters and create common state\&. \fP"
.ti -1c
.RI "\fBint\fP \fBSDLTest_CommonArg\fP (\fBSDLTest_CommonState\fP *state, \fBint\fP \fBindex\fP)"
.br
.RI "\fIProcess one common argument\&. \fP"
.ti -1c
.RI "\fBconst\fP char * \fBSDLTest_CommonUsage\fP (\fBSDLTest_CommonState\fP *state)"
.br
.RI "\fIReturns common usage information\&. \fP"
.ti -1c
.RI "\fBSDL_bool\fP \fBSDLTest_CommonInit\fP (\fBSDLTest_CommonState\fP *state)"
.br
.RI "\fIOpen test window\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBSDLTest_CommonEvent\fP (\fBSDLTest_CommonState\fP *state, \fBSDL_Event\fP *\fBevent\fP, \fBint\fP *done)"
.br
.RI "\fICommon event handler for test windows\&. \fP"
.ti -1c
.RI "\fBvoid\fP \fBSDLTest_CommonQuit\fP (\fBSDLTest_CommonState\fP *state)"
.br
.RI "\fIClose test window\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Include file for SDL test framework\&.
.PP
This code is a part of the SDL2_test library, not the main SDL library\&. 
.PP
Définition dans le fichier \fBSDL_test_common\&.h\fP\&.
.SH "Documentation des macros"
.PP 
.SS "#define DEFAULT_WINDOW_HEIGHT   480"

.PP
Définition à la ligne 42 du fichier SDL_test_common\&.h\&.
.SS "#define DEFAULT_WINDOW_WIDTH   640"

.PP
Définition à la ligne 41 du fichier SDL_test_common\&.h\&.
.SS "#define VERBOSE_AUDIO   0x00000010"

.PP
Définition à la ligne 49 du fichier SDL_test_common\&.h\&.
.SS "#define VERBOSE_EVENT   0x00000008"

.PP
Définition à la ligne 48 du fichier SDL_test_common\&.h\&.
.SS "#define VERBOSE_MODES   0x00000002"

.PP
Définition à la ligne 46 du fichier SDL_test_common\&.h\&.
.SS "#define VERBOSE_RENDER   0x00000004"

.PP
Définition à la ligne 47 du fichier SDL_test_common\&.h\&.
.SS "#define VERBOSE_VIDEO   0x00000001"

.PP
Définition à la ligne 45 du fichier SDL_test_common\&.h\&.
.SH "Documentation des fonctions"
.PP 
.SS "\fBint\fP SDLTest_CommonArg (\fBSDLTest_CommonState\fP * state, \fBint\fP index)"

.PP
Process one common argument\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIstate\fP The common state describing the test window to create\&. 
.br
\fIindex\fP The index of the argument to process in argv[]\&.
.RE
.PP
\fBRenvoie:\fP
.RS 4
The number of arguments processed (i\&.e\&. 1 for --fullscreen, 2 for --video [videodriver], or -1 on error\&. 
.RE
.PP

.SS "\fBSDLTest_CommonState\fP* SDLTest_CommonCreateState (char ** argv, \fBUint32\fP flags)"

.PP
Parse command line parameters and create common state\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIargv\fP Array of command line parameters 
.br
\fIflags\fP Flags indicating which subsystem to initialize (i\&.e\&. SDL_INIT_VIDEO | SDL_INIT_AUDIO)
.RE
.PP
\fBRenvoie:\fP
.RS 4
Returns a newly allocated common state object\&. 
.RE
.PP

.SS "\fBvoid\fP SDLTest_CommonEvent (\fBSDLTest_CommonState\fP * state, \fBSDL_Event\fP * event, \fBint\fP * done)"

.PP
Common event handler for test windows\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIstate\fP The common state used to create test window\&. 
.br
\fIevent\fP The event to handle\&. 
.br
\fIdone\fP Flag indicating we are done\&. 
.RE
.PP

.SS "\fBSDL_bool\fP SDLTest_CommonInit (\fBSDLTest_CommonState\fP * state)"

.PP
Open test window\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIstate\fP The common state describing the test window to create\&.
.RE
.PP
\fBRenvoie:\fP
.RS 4
True if initialization succeeded, false otherwise 
.RE
.PP

.SS "\fBvoid\fP SDLTest_CommonQuit (\fBSDLTest_CommonState\fP * state)"

.PP
Close test window\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIstate\fP The common state used to create test window\&. 
.RE
.PP

.SS "\fBconst\fP char* SDLTest_CommonUsage (\fBSDLTest_CommonState\fP * state)"

.PP
Returns common usage information\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIstate\fP The common state describing the test window to create\&.
.RE
.PP
\fBRenvoie:\fP
.RS 4
String with usage information 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
