.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_test_images.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_test_images.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL\&.h'\fP
.br
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSDLTest_SurfaceImage_s\fP"
.br
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBSDLTest_SurfaceImage_s\fP \fBSDLTest_SurfaceImage_t\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlit\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitColor\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitAlpha\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendAdd\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlend\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendMod\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendNone\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendAll\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageFace\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImagePrimitives\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImagePrimitivesBlend\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Include file for SDL test framework\&.
.PP
This code is a part of the SDL2_test library, not the main SDL library\&. 
.PP
Définition dans le fichier \fBSDL_test_images\&.h\fP\&.
.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fBSDLTest_SurfaceImage_s\fP  \fBSDLTest_SurfaceImage_t\fP"
Type for test images\&. 
.SH "Documentation des fonctions"
.PP 
.SS "\fBSDL_Surface\fP* SDLTest_ImageBlit ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImageBlitAlpha ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImageBlitBlend ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImageBlitBlendAdd ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImageBlitBlendAll ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImageBlitBlendMod ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImageBlitBlendNone ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImageBlitColor ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImageFace ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImagePrimitives ()"

.SS "\fBSDL_Surface\fP* SDLTest_ImagePrimitivesBlend ()"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
