.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_opengles2.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_opengles2.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GLES2/gl2platform\&.h>\fP
.br
\fC#include <GLES2/gl2\&.h>\fP
.br
\fC#include <GLES2/gl2ext\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAPIENTRY\fP   \fBGL_APIENTRY\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
This is a simple file to encapsulate the \fBOpenGL\fP ES 2\&.0 API headers\&. 
.PP
Définition dans le fichier \fBSDL_opengles2\&.h\fP\&.
.SH "Documentation des macros"
.PP 
.SS "#define APIENTRY   \fBGL_APIENTRY\fP"

.PP
Définition à la ligne 49 du fichier SDL_opengles2\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
