.TH "SDL_WindowShapeParams" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowShapeParams \- A union containing parameters for shaped windows\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_shape\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBbinarizationCutoff\fP"
.br
.RI "\fIa cutoff alpha value for binarization of the window shape's alpha channel\&. \fP"
.ti -1c
.RI "\fBSDL_Color\fP \fBcolorKey\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
A union containing parameters for shaped windows\&. 
.PP
Définition à la ligne 93 du fichier SDL_shape\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBUint8\fP SDL_WindowShapeParams::binarizationCutoff"

.PP
a cutoff alpha value for binarization of the window shape's alpha channel\&. 
.PP
Définition à la ligne 95 du fichier SDL_shape\&.h\&.
.SS "\fBSDL_Color\fP SDL_WindowShapeParams::colorKey"

.PP
Définition à la ligne 96 du fichier SDL_shape\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
