.TH "SDL_AssertData" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_AssertData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_assert\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBint\fP \fBalways_ignore\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBtrigger_count\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBcondition\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBfilename\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlinenum\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBfunction\fP"
.br
.ti -1c
.RI "\fBconst\fP struct \fBSDL_AssertData\fP * \fBnext\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 109 du fichier SDL_assert\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP SDL_AssertData::always_ignore"

.PP
Définition à la ligne 111 du fichier SDL_assert\&.h\&.
.SS "\fBconst\fP char* SDL_AssertData::condition"

.PP
Définition à la ligne 113 du fichier SDL_assert\&.h\&.
.SS "\fBconst\fP char* SDL_AssertData::filename"

.PP
Définition à la ligne 114 du fichier SDL_assert\&.h\&.
.SS "\fBconst\fP char* SDL_AssertData::function"

.PP
Définition à la ligne 116 du fichier SDL_assert\&.h\&.
.SS "\fBint\fP SDL_AssertData::linenum"

.PP
Définition à la ligne 115 du fichier SDL_assert\&.h\&.
.SS "\fBconst\fP struct \fBSDL_AssertData\fP* SDL_AssertData::next"

.PP
Définition à la ligne 117 du fichier SDL_assert\&.h\&.
.SS "unsigned \fBint\fP SDL_AssertData::trigger_count"

.PP
Définition à la ligne 112 du fichier SDL_assert\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
