.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_opengles.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_opengles.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GLES/gl\&.h>\fP
.br
\fC#include <GLES/glext\&.h>\fP
.br

.SH "Description détaillée"
.PP 
This is a simple file to encapsulate the \fBOpenGL\fP ES 1\&.X API headers\&. 
.PP
Définition dans le fichier \fBSDL_opengles\&.h\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
