.TH "SDL_WindowEvent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowEvent \- Window state change event data (event\&.window\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBwindowID\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBevent\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBpadding1\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBpadding2\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBpadding3\fP"
.br
.ti -1c
.RI "\fBSint32\fP \fBdata1\fP"
.br
.ti -1c
.RI "\fBSint32\fP \fBdata2\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Window state change event data (event\&.window\&.*) 
.PP
Définition à la ligne 171 du fichier SDL_events\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBSint32\fP SDL_WindowEvent::data1"
event dependent data 
.PP
Définition à la ligne 180 du fichier SDL_events\&.h\&.
.SS "\fBSint32\fP SDL_WindowEvent::data2"
event dependent data 
.PP
Définition à la ligne 181 du fichier SDL_events\&.h\&.
.SS "\fBUint8\fP SDL_WindowEvent::event"
\fBSDL_WindowEventID\fP 
.PP
Définition à la ligne 176 du fichier SDL_events\&.h\&.
.SS "\fBUint8\fP SDL_WindowEvent::padding1"

.PP
Définition à la ligne 177 du fichier SDL_events\&.h\&.
.SS "\fBUint8\fP SDL_WindowEvent::padding2"

.PP
Définition à la ligne 178 du fichier SDL_events\&.h\&.
.SS "\fBUint8\fP SDL_WindowEvent::padding3"

.PP
Définition à la ligne 179 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_WindowEvent::timestamp"

.PP
Définition à la ligne 174 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_WindowEvent::type"
\fBSDL_WINDOWEVENT\fP 
.PP
Définition à la ligne 173 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_WindowEvent::windowID"
The associated window 
.PP
Définition à la ligne 175 du fichier SDL_events\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
