.TH "SDL_QuitEvent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_QuitEvent \- The 'quit requested' event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBtimestamp\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
The 'quit requested' event\&. 
.PP
Définition à la ligne 473 du fichier SDL_events\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBUint32\fP SDL_QuitEvent::timestamp"

.PP
Définition à la ligne 476 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_QuitEvent::type"
\fBSDL_QUIT\fP 
.PP
Définition à la ligne 475 du fichier SDL_events\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
