.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_blendmode.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_blendmode.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBSDL_BlendMode\fP { \fBSDL_BLENDMODE_NONE\fP = 0x00000000, \fBSDL_BLENDMODE_BLEND\fP = 0x00000001, \fBSDL_BLENDMODE_ADD\fP = 0x00000002, \fBSDL_BLENDMODE_MOD\fP = 0x00000004 }
.RI "\fIThe blend mode used in \fBSDL_RenderCopy()\fP and drawing operations\&. \fP""
.br
.in -1c
.SH "Description détaillée"
.PP 
Header file declaring the SDL_BlendMode enumeration 
.PP
Définition dans le fichier \fBSDL_blendmode\&.h\fP\&.
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBSDL_BlendMode\fP"

.PP
The blend mode used in \fBSDL_RenderCopy()\fP and drawing operations\&. 
.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fISDL_BLENDMODE_NONE \fP\fP
no blending dstRGBA = srcRGBA 
.TP
\fB\fISDL_BLENDMODE_BLEND \fP\fP
alpha blending dstRGB = (srcRGB * srcA) + (dstRGB * (1-srcA)) dstA = srcA + (dstA * (1-srcA)) 
.TP
\fB\fISDL_BLENDMODE_ADD \fP\fP
additive blending dstRGB = (srcRGB * srcA) + dstRGB dstA = dstA 
.TP
\fB\fISDL_BLENDMODE_MOD \fP\fP
color modulate dstRGB = srcRGB * dstRGB dstA = dstA 
.PP
Définition à la ligne 40 du fichier SDL_blendmode\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
