.TH "SDL_Point" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Point \- The structure that defines a point\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_rect\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
The structure that defines a point\&. 


.PP
\fBVoir également:\fP
.RS 4
\fBSDL_EnclosePoints\fP 
.PP
\fBSDL_PointInRect\fP 
.RE
.PP

.PP
Définition à la ligne 48 du fichier SDL_rect\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP SDL_Point::x"

.PP
Définition à la ligne 50 du fichier SDL_rect\&.h\&.
.SS "\fBint\fP SDL_Point::y"

.PP
Définition à la ligne 51 du fichier SDL_rect\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
