.TH "SDL_WindowShapeMode" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowShapeMode \- A struct that tags the \fBSDL_WindowShapeParams\fP union with an enum describing the type of its contents\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_shape\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBWindowShapeMode\fP \fBmode\fP"
.br
.RI "\fIThe mode of these window-shape parameters\&. \fP"
.ti -1c
.RI "\fBSDL_WindowShapeParams\fP \fBparameters\fP"
.br
.RI "\fIWindow-shape parameters\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
A struct that tags the \fBSDL_WindowShapeParams\fP union with an enum describing the type of its contents\&. 
.PP
Définition à la ligne 100 du fichier SDL_shape\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBWindowShapeMode\fP SDL_WindowShapeMode::mode"

.PP
The mode of these window-shape parameters\&. 
.PP
Définition à la ligne 102 du fichier SDL_shape\&.h\&.
.SS "\fBSDL_WindowShapeParams\fP SDL_WindowShapeMode::parameters"

.PP
Window-shape parameters\&. 
.PP
Définition à la ligne 104 du fichier SDL_shape\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
