.TH "SDL_CommonEvent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_CommonEvent \- Fields shared by every event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBtimestamp\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Fields shared by every event\&. 
.PP
Définition à la ligne 162 du fichier SDL_events\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBUint32\fP SDL_CommonEvent::timestamp"

.PP
Définition à la ligne 165 du fichier SDL_events\&.h\&.
.SS "\fBUint32\fP SDL_CommonEvent::type"

.PP
Définition à la ligne 164 du fichier SDL_events\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
