.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_revision.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/sdl2/include/SDL_revision.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDL_REVISION\fP   'hg\-10001:e12c38730512'"
.br
.ti -1c
.RI "#define \fBSDL_REVISION_NUMBER\fP   10001"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define SDL_REVISION   'hg\-10001:e12c38730512'"

.PP
Définition à la ligne 1 du fichier SDL_revision\&.h\&.
.SS "#define SDL_REVISION_NUMBER   10001"

.PP
Définition à la ligne 2 du fichier SDL_revision\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
