.TH "SDLTest_TestCaseReference" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_TestCaseReference \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_harness\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBSDLTest_TestCaseFp\fP \fBtestCase\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBdescription\fP"
.br
.ti -1c
.RI "\fBint\fP \fBenabled\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Holds information about a single test case\&. 
.PP
Définition à la ligne 75 du fichier SDL_test_harness\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "char* SDLTest_TestCaseReference::description"

.PP
Définition à la ligne 81 du fichier SDL_test_harness\&.h\&.
.SS "\fBint\fP SDLTest_TestCaseReference::enabled"

.PP
Définition à la ligne 83 du fichier SDL_test_harness\&.h\&.
.SS "char* SDLTest_TestCaseReference::name"

.PP
Définition à la ligne 79 du fichier SDL_test_harness\&.h\&.
.SS "\fBSDLTest_TestCaseFp\fP SDLTest_TestCaseReference::testCase"

.PP
Définition à la ligne 77 du fichier SDL_test_harness\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
