.TH "SDLTest_Crc32Context" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_Crc32Context \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_crc32\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBCrcUint32\fP \fBcrc32_table\fP [256]"
.br
.in -1c
.SH "Description détaillée"
.PP 
Data structure for CRC32 (checksum) computation 
.PP
Définition à la ligne 66 du fichier SDL_test_crc32\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBCrcUint32\fP SDLTest_Crc32Context::crc32_table[256]"

.PP
Définition à la ligne 67 du fichier SDL_test_crc32\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
