.TH "SDLTest_SurfaceImage_s" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_SurfaceImage_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_images\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBbytes_per_pixel\fP"
.br
.ti -1c
.RI "\fBconst\fP char * \fBpixel_data\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Type for test images\&. 
.PP
Définition à la ligne 50 du fichier SDL_test_images\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "unsigned \fBint\fP SDLTest_SurfaceImage_s::bytes_per_pixel"

.PP
Définition à la ligne 53 du fichier SDL_test_images\&.h\&.
.SS "\fBint\fP SDLTest_SurfaceImage_s::height"

.PP
Définition à la ligne 52 du fichier SDL_test_images\&.h\&.
.SS "\fBconst\fP char* SDLTest_SurfaceImage_s::pixel_data"

.PP
Définition à la ligne 54 du fichier SDL_test_images\&.h\&.
.SS "\fBint\fP SDLTest_SurfaceImage_s::width"

.PP
Définition à la ligne 51 du fichier SDL_test_images\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
