.TH "SDLTest_TestSuiteReference" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_TestSuiteReference \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_harness\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBSDLTest_TestCaseSetUpFp\fP \fBtestSetUp\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBSDLTest_TestCaseReference\fP ** \fBtestCases\fP"
.br
.ti -1c
.RI "\fBSDLTest_TestCaseTearDownFp\fP \fBtestTearDown\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Holds information about a test suite (multiple test cases)\&. 
.PP
Définition à la ligne 89 du fichier SDL_test_harness\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "char* SDLTest_TestSuiteReference::name"

.PP
Définition à la ligne 91 du fichier SDL_test_harness\&.h\&.
.SS "\fBconst\fP \fBSDLTest_TestCaseReference\fP** SDLTest_TestSuiteReference::testCases"

.PP
Définition à la ligne 95 du fichier SDL_test_harness\&.h\&.
.SS "\fBSDLTest_TestCaseSetUpFp\fP SDLTest_TestSuiteReference::testSetUp"

.PP
Définition à la ligne 93 du fichier SDL_test_harness\&.h\&.
.SS "\fBSDLTest_TestCaseTearDownFp\fP SDLTest_TestSuiteReference::testTearDown"

.PP
Définition à la ligne 97 du fichier SDL_test_harness\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
