.TH "/home/wery_a/rendu/CPP/cpp_arcade/src/games/snake/Snake.cpp" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/src/games/snake/Snake.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Snake\&.hpp'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBPlay\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "\fBvoid\fP Play (\fBvoid\fP)"

.PP
Définition à la ligne 203 du fichier Snake\&.cpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
