.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/games/snake/Snake.hpp" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/games/snake/Snake.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'AGame\&.hpp'\fP
.br
\fC#include 'Utils\&.hpp'\fP
.br
\fC#include 'GameComponent\&.hpp'\fP
.br
\fC#include 'BackgroundComponent\&.hpp'\fP
.br
\fC#include 'UIComponent\&.hpp'\fP
.br
\fC#include 'AudioComponent\&.hpp'\fP
.br
\fC#include 'ScoreComponent\&.hpp'\fP
.br
\fC#include 'Protocol\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSnake\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIDTH\fP   50"
.br
.ti -1c
.RI "#define \fBHEIGHT\fP   30"
.br
.ti -1c
.RI "#define \fBSTEP\fP   1"
.br
.ti -1c
.RI "#define \fBSIZE\fP   3"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBdirection\fP { \fBDIR_LEFT\fP, \fBDIR_RIGHT\fP, \fBDIR_UP\fP, \fBDIR_DOWN\fP, \fBWAIT\fP, \fBDIR_LEFT\fP, \fBDIR_RIGHT\fP, \fBDIR_UP\fP, \fBDIR_DOWN\fP }"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBAGame\fP * \fBloadGame\fP ()"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define HEIGHT   30"

.PP
Définition à la ligne 25 du fichier Snake\&.hpp\&.
.SS "#define SIZE   3"

.PP
Définition à la ligne 27 du fichier Snake\&.hpp\&.
.SS "#define STEP   1"

.PP
Définition à la ligne 26 du fichier Snake\&.hpp\&.
.SS "#define WIDTH   50"

.PP
Définition à la ligne 24 du fichier Snake\&.hpp\&.
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBdirection\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIDIR_LEFT \fP\fP
.TP
\fB\fIDIR_RIGHT \fP\fP
.TP
\fB\fIDIR_UP \fP\fP
.TP
\fB\fIDIR_DOWN \fP\fP
.TP
\fB\fIWAIT \fP\fP
.TP
\fB\fIDIR_LEFT \fP\fP
.TP
\fB\fIDIR_RIGHT \fP\fP
.TP
\fB\fIDIR_UP \fP\fP
.TP
\fB\fIDIR_DOWN \fP\fP
.PP
Définition à la ligne 29 du fichier Snake\&.hpp\&.
.SH "Documentation des fonctions"
.PP 
.SS "\fBAGame\fP* loadGame ()"

.PP
Définition à la ligne 54 du fichier Snake\&.hpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
