.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/games/snake/Snake.hpp" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/games/snake/Snake.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'AGame\&.hpp'\fP
.br
\fC#include 'Utils\&.hpp'\fP
.br
\fC#include 'GameComponent\&.hpp'\fP
.br
\fC#include 'BackgroundComponent\&.hpp'\fP
.br
\fC#include 'UIComponent\&.hpp'\fP
.br
\fC#include 'AudioComponent\&.hpp'\fP
.br
\fC#include 'HighScoreComponent\&.hpp'\fP
.br
\fC#include 'Protocol\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSnake\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWIDTH\fP   50"
.br
.ti -1c
.RI "#define \fBHEIGHT\fP   30"
.br
.ti -1c
.RI "#define \fBSIZE\fP   3"
.br
.ti -1c
.RI "#define \fBRANDOM_POS\fP   \fBVector2\fP<double>(rand() % (\fBWIDTH\fP \- 1) + 1, rand() % (\fBHEIGHT\fP \- 1) + 1)"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBdirection\fP { \fBDIR_LEFT\fP, \fBDIR_RIGHT\fP, \fBDIR_UP\fP, \fBDIR_DOWN\fP, \fBNOTHING\fP, \fBDIR_LEFT\fP, \fBDIR_RIGHT\fP, \fBDIR_UP\fP, \fBDIR_DOWN\fP }"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBPlay\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBAGame\fP * \fBloadGame\fP ()"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define HEIGHT   30"

.PP
Définition à la ligne 15 du fichier Snake\&.hpp\&.
.SS "#define RANDOM_POS   \fBVector2\fP<double>(rand() % (\fBWIDTH\fP \- 1) + 1, rand() % (\fBHEIGHT\fP \- 1) + 1)"

.PP
Définition à la ligne 17 du fichier Snake\&.hpp\&.
.SS "#define SIZE   3"

.PP
Définition à la ligne 16 du fichier Snake\&.hpp\&.
.SS "#define WIDTH   50"

.PP
Définition à la ligne 14 du fichier Snake\&.hpp\&.
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBdirection\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fIDIR_LEFT \fP\fP
.TP
\fB\fIDIR_RIGHT \fP\fP
.TP
\fB\fIDIR_UP \fP\fP
.TP
\fB\fIDIR_DOWN \fP\fP
.TP
\fB\fINOTHING \fP\fP
.TP
\fB\fIDIR_LEFT \fP\fP
.TP
\fB\fIDIR_RIGHT \fP\fP
.TP
\fB\fIDIR_UP \fP\fP
.TP
\fB\fIDIR_DOWN \fP\fP
.PP
Définition à la ligne 19 du fichier Snake\&.hpp\&.
.SH "Documentation des fonctions"
.PP 
.SS "\fBAGame\fP* loadGame ()"

.PP
Définition à la ligne 48 du fichier Snake\&.hpp\&.
.SS "\fBvoid\fP Play (\fBvoid\fP)"

.PP
Définition à la ligne 203 du fichier Snake\&.cpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
