.TH "Snake" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Snake \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Snake\&.hpp>\fP
.PP
Est dérivée de \fBAGame\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSnake\fP ()"
.br
.ti -1c
.RI "virtual \fB~Snake\fP ()"
.br
.ti -1c
.RI "virtual std::stack< \fBAComponent\fP * > \fBcompute\fP (\fBint\fP key)"
.br
.ti -1c
.RI "virtual std::stack< \fBAComponent\fP * > \fBgetInfos\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBrestart\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBPlay\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgetMap\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBwhereAmI\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBchangeDirection\fP (\fBint\fP key)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 21 du fichier Snake\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Snake::Snake ()"

.PP
Définition à la ligne 3 du fichier Snake\&.cpp\&.
.SS "Snake::~Snake ()\fC [virtual]\fP"

.PP
Définition à la ligne 18 du fichier Snake\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBvoid\fP Snake::changeDirection (\fBint\fP key)"

.PP
Définition à la ligne 103 du fichier Snake\&.cpp\&.
.SS "std::stack< \fBAComponent\fP * > Snake::compute (\fBint\fP key)\fC [virtual]\fP"

.PP
Implémente \fBAGame\fP\&.
.PP
Définition à la ligne 116 du fichier Snake\&.cpp\&.
.SS "std::stack< \fBAComponent\fP * > Snake::getInfos (\fBvoid\fP)\fC [virtual]\fP"

.PP
Implémente \fBAGame\fP\&.
.PP
Définition à la ligne 159 du fichier Snake\&.cpp\&.
.SS "\fBvoid\fP Snake::getMap ()"

.PP
Définition à la ligne 168 du fichier Snake\&.cpp\&.
.SS "\fBvoid\fP Snake::Play (\fBvoid\fP)"

.SS "\fBvoid\fP Snake::restart (\fBvoid\fP)\fC [virtual]\fP"

.PP
Implémente \fBAGame\fP\&.
.PP
Définition à la ligne 21 du fichier Snake\&.cpp\&.
.SS "\fBvoid\fP Snake::whereAmI ()"

.PP
Définition à la ligne 188 du fichier Snake\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
