.TH "Soft_Label_Key_Set::Soft_Label_Key" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Soft_Label_Key_Set::Soft_Label_Key \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursslk\&.h>\fP
.SS "Types publics"

.in +1c
.ti -1c
.RI "enum \fBJustification\fP { \fBLeft\fP =0, \fBCenter\fP =1, \fBRight\fP =2 }"
.br
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSoft_Label_Key\fP & \fBoperator=\fP (char *text)"
.br
.ti -1c
.RI "\fBSoft_Label_Key\fP & \fBoperator=\fP (\fBJustification\fP just)"
.br
.ti -1c
.RI "char * \fBoperator()\fP (\fBvoid\fP) \fBconst\fP "
.br
.ti -1c
.RI "\fBSoft_Label_Key\fP & \fBoperator=\fP (\fBconst\fP \fBSoft_Label_Key\fP &rhs)"
.br
.ti -1c
.RI "\fBSoft_Label_Key\fP (\fBconst\fP \fBSoft_Label_Key\fP &rhs)"
.br
.in -1c
.SS "Amis"

.in +1c
.ti -1c
.RI "class \fBSoft_Label_Key_Set\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 44 du fichier cursslk\&.h\&.
.SH "Documentation des énumérations membres"
.PP 
.SS "enum \fBSoft_Label_Key_Set::Soft_Label_Key::Justification\fP"

.PP
\fBValeurs énumérées\fP
.in +1c
.TP
\fB\fILeft \fP\fP
.TP
\fB\fICenter \fP\fP
.TP
\fB\fIRight \fP\fP
.PP
Définition à la ligne 47 du fichier cursslk\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "Soft_Label_Key_Set::Soft_Label_Key::Soft_Label_Key (\fBconst\fP \fBSoft_Label_Key\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 84 du fichier cursslk\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "char* Soft_Label_Key_Set::Soft_Label_Key::operator() (\fBvoid\fP) const\fC [inline]\fP"

.PP
Définition à la ligne 72 du fichier cursslk\&.h\&.
.SS "\fBSoft_Label_Key\fP& Soft_Label_Key_Set::Soft_Label_Key::operator= (char * text)"

.SS "\fBSoft_Label_Key\fP& Soft_Label_Key_Set::Soft_Label_Key::operator= (\fBJustification\fP just)\fC [inline]\fP"

.PP
Définition à la ligne 66 du fichier cursslk\&.h\&.
.SS "\fBSoft_Label_Key\fP& Soft_Label_Key_Set::Soft_Label_Key::operator= (\fBconst\fP \fBSoft_Label_Key\fP & rhs)\fC [inline]\fP"

.PP
Définition à la ligne 76 du fichier cursslk\&.h\&.
.SH "Documentation des fonctions amies et associées"
.PP 
.SS "friend class \fBSoft_Label_Key_Set\fP\fC [friend]\fP"

.PP
Définition à la ligne 45 du fichier cursslk\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
