.TH "tagITEM" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagITEM \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menu\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBTEXT\fP \fBname\fP"
.br
.ti -1c
.RI "\fBTEXT\fP \fBdescription\fP"
.br
.ti -1c
.RI "struct \fBtagMENU\fP * \fBimenu\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBuserptr\fP"
.br
.ti -1c
.RI "\fBItem_Options\fP \fBopt\fP"
.br
.ti -1c
.RI "short \fBindex\fP"
.br
.ti -1c
.RI "short \fBy\fP"
.br
.ti -1c
.RI "short \fBx\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBtagITEM\fP * \fBleft\fP"
.br
.ti -1c
.RI "struct \fBtagITEM\fP * \fBright\fP"
.br
.ti -1c
.RI "struct \fBtagITEM\fP * \fBup\fP"
.br
.ti -1c
.RI "struct \fBtagITEM\fP * \fBdown\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 69 du fichier menu\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBTEXT\fP tagITEM::description"

.PP
Définition à la ligne 72 du fichier menu\&.h\&.
.SS "struct \fBtagITEM\fP* tagITEM::down"

.PP
Définition à la ligne 84 du fichier menu\&.h\&.
.SS "struct \fBtagMENU\fP* tagITEM::imenu"

.PP
Définition à la ligne 73 du fichier menu\&.h\&.
.SS "short tagITEM::index"

.PP
Définition à la ligne 76 du fichier menu\&.h\&.
.SS "struct \fBtagITEM\fP* tagITEM::left"

.PP
Définition à la ligne 81 du fichier menu\&.h\&.
.SS "\fBTEXT\fP tagITEM::name"

.PP
Définition à la ligne 71 du fichier menu\&.h\&.
.SS "\fBItem_Options\fP tagITEM::opt"

.PP
Définition à la ligne 75 du fichier menu\&.h\&.
.SS "struct \fBtagITEM\fP* tagITEM::right"

.PP
Définition à la ligne 82 du fichier menu\&.h\&.
.SS "struct \fBtagITEM\fP* tagITEM::up"

.PP
Définition à la ligne 83 du fichier menu\&.h\&.
.SS "\fBvoid\fP* tagITEM::userptr"

.PP
Définition à la ligne 74 du fichier menu\&.h\&.
.SS "\fBbool\fP tagITEM::value"

.PP
Définition à la ligne 79 du fichier menu\&.h\&.
.SS "short tagITEM::x"

.PP
Définition à la ligne 78 du fichier menu\&.h\&.
.SS "short tagITEM::y"

.PP
Définition à la ligne 77 du fichier menu\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
