.TH "term" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
term \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <term\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBTERMTYPE\fP \fBtype\fP"
.br
.ti -1c
.RI "short \fBFiledes\fP"
.br
.ti -1c
.RI "\fBTTY\fP \fBOttyb\fP"
.br
.ti -1c
.RI "\fBTTY\fP \fBNttyb\fP"
.br
.ti -1c
.RI "\fBint\fP \fB_baudrate\fP"
.br
.ti -1c
.RI "char * \fB_termname\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 670 du fichier term\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBint\fP term::_baudrate"

.PP
Définition à la ligne 675 du fichier term\&.h\&.
.SS "char* term::_termname"

.PP
Définition à la ligne 676 du fichier term\&.h\&.
.SS "short term::Filedes"

.PP
Définition à la ligne 672 du fichier term\&.h\&.
.SS "\fBTTY\fP term::Nttyb"

.PP
Définition à la ligne 673 du fichier term\&.h\&.
.SS "\fBTTY\fP term::Ottyb"

.PP
Définition à la ligne 673 du fichier term\&.h\&.
.SS "\fBTERMTYPE\fP term::type"

.PP
Définition à la ligne 671 du fichier term\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
