.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/termcap.h" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/termcap.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses/ncurses_dll\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNCURSES_VERSION\fP   '6\&.0'"
.br
.ti -1c
.RI "#define \fBNCURSES_CONST\fP   \fBconst\fP"
.br
.ti -1c
.RI "#define \fBNCURSES_OSPEED\fP   short"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBNCURSES_EXPORT_VAR\fP (char) PC"
.br
.ti -1c
.RI "\fBNCURSES_EXPORT_VAR\fP (char *) \fBUP\fP"
.br
.ti -1c
.RI "\fBNCURSES_EXPORT_VAR\fP (\fBNCURSES_OSPEED\fP) ospeed"
.br
.ti -1c
.RI "\fBNCURSES_EXPORT\fP (char *) tgetstr(\fBNCURSES_CONST\fP char *"
.br
.ti -1c
.RI "\fBNCURSES_EXPORT\fP (\fBint\fP) tgetent(char *"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBint\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define NCURSES_CONST   \fBconst\fP"

.PP
Définition à la ligne 52 du fichier termcap\&.h\&.
.SS "#define NCURSES_OSPEED   short"

.PP
Définition à la ligne 55 du fichier termcap\&.h\&.
.SS "#define NCURSES_VERSION   '6\&.0'"

.PP
Définition à la ligne 40 du fichier termcap\&.h\&.
.SH "Documentation des fonctions"
.PP 
.SS "NCURSES_EXPORT (char *)"

.SS "NCURSES_EXPORT (\fBint\fP)"

.SS "NCURSES_EXPORT_VAR (char)"

.SS "NCURSES_EXPORT_VAR (char *)"

.SS "NCURSES_EXPORT_VAR (\fBNCURSES_OSPEED\fP)"

.SH "Documentation des variables"
.PP 
.SS "int int"

.PP
Définition à la ligne 64 du fichier termcap\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
