.TH "termtype" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
termtype \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <term\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char * \fBterm_names\fP"
.br
.ti -1c
.RI "char * \fBstr_table\fP"
.br
.ti -1c
.RI "\fBNCURSES_SBOOL\fP * \fBBooleans\fP"
.br
.ti -1c
.RI "short * \fBNumbers\fP"
.br
.ti -1c
.RI "char ** \fBStrings\fP"
.br
.ti -1c
.RI "char * \fBext_str_table\fP"
.br
.ti -1c
.RI "char ** \fBext_Names\fP"
.br
.ti -1c
.RI "unsigned short \fBnum_Booleans\fP"
.br
.ti -1c
.RI "unsigned short \fBnum_Numbers\fP"
.br
.ti -1c
.RI "unsigned short \fBnum_Strings\fP"
.br
.ti -1c
.RI "unsigned short \fBext_Booleans\fP"
.br
.ti -1c
.RI "unsigned short \fBext_Numbers\fP"
.br
.ti -1c
.RI "unsigned short \fBext_Strings\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 648 du fichier term\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBNCURSES_SBOOL\fP* termtype::Booleans"

.PP
Définition à la ligne 651 du fichier term\&.h\&.
.SS "unsigned short termtype::ext_Booleans"

.PP
Définition à la ligne 663 du fichier term\&.h\&.
.SS "char** termtype::ext_Names"

.PP
Définition à la ligne 657 du fichier term\&.h\&.
.SS "unsigned short termtype::ext_Numbers"

.PP
Définition à la ligne 664 du fichier term\&.h\&.
.SS "char* termtype::ext_str_table"

.PP
Définition à la ligne 656 du fichier term\&.h\&.
.SS "unsigned short termtype::ext_Strings"

.PP
Définition à la ligne 665 du fichier term\&.h\&.
.SS "unsigned short termtype::num_Booleans"

.PP
Définition à la ligne 659 du fichier term\&.h\&.
.SS "unsigned short termtype::num_Numbers"

.PP
Définition à la ligne 660 du fichier term\&.h\&.
.SS "unsigned short termtype::num_Strings"

.PP
Définition à la ligne 661 du fichier term\&.h\&.
.SS "short* termtype::Numbers"

.PP
Définition à la ligne 652 du fichier term\&.h\&.
.SS "char* termtype::str_table"

.PP
Définition à la ligne 650 du fichier term\&.h\&.
.SS "char** termtype::Strings"

.PP
Définition à la ligne 653 du fichier term\&.h\&.
.SS "char* termtype::term_names"

.PP
Définition à la ligne 649 du fichier term\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
