.TH "TEXT" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TEXT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menu\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBconst\fP char * \fBstr\fP"
.br
.ti -1c
.RI "unsigned short \fBlength\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 63 du fichier menu\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "unsigned short TEXT::length"

.PP
Définition à la ligne 66 du fichier menu\&.h\&.
.SS "\fBconst\fP char* TEXT::str"

.PP
Définition à la ligne 65 du fichier menu\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
