.TH "tinfo_fkeys" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinfo_fkeys \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tic\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "unsigned \fBoffset\fP"
.br
.ti -1c
.RI "\fBchtype\fP \fBcode\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 170 du fichier tic\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBchtype\fP tinfo_fkeys::code"

.PP
Définition à la ligne 172 du fichier tic\&.h\&.
.SS "unsigned tinfo_fkeys::offset"

.PP
Définition à la ligne 171 du fichier tic\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
