.TH "token" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
token \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tic\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char * \fBtk_name\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtk_valnumber\fP"
.br
.ti -1c
.RI "char * \fBtk_valstring\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 157 du fichier tic\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "char* token::tk_name"

.PP
Définition à la ligne 159 du fichier tic\&.h\&.
.SS "\fBint\fP token::tk_valnumber"

.PP
Définition à la ligne 160 du fichier tic\&.h\&.
.SS "char* token::tk_valstring"

.PP
Définition à la ligne 161 du fichier tic\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
