.TH "UIComponent" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UIComponent\&.hpp>\fP
.PP
Est dérivée de \fBAComponent\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBUIComponent\fP (\fBVector2\fP< \fBint\fP > \fBconst\fP &\fBp\fP, \fBVector2\fP< \fBint\fP > \fBconst\fP &\fBs\fP, \fBComponentColor\fP \fBcolor\fP, \fBconst\fP \fBstd::string\fP &text, \fBconst\fP \fBstd::string\fP &\fBfontName\fP, unsigned \fBint\fP fontSize)"
.br
.ti -1c
.RI "virtual \fB~UIComponent\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBstd::string\fP & \fBgetText\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBconst\fP \fBstd::string\fP & \fBgetFontName\fP () \fBconst\fP "
.br
.ti -1c
.RI "unsigned \fBint\fP \fBgetFontSize\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBsetText\fP (\fBconst\fP \fBstd::string\fP &text)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetFontName\fP (\fBconst\fP \fBstd::string\fP &\fBfontName\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetFontSize\fP (unsigned \fBint\fP fontSize)"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 20 du fichier UIComponent\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "UIComponent::UIComponent (\fBVector2\fP< \fBint\fP > \fBconst\fP & p, \fBVector2\fP< \fBint\fP > \fBconst\fP & s, \fBComponentColor\fP color, \fBconst\fP \fBstd::string\fP & text, \fBconst\fP \fBstd::string\fP & fontName, unsigned \fBint\fP fontSize)"

.PP
Définition à la ligne 13 du fichier UIComponent\&.cpp\&.
.SS "UIComponent::~UIComponent ()\fC [virtual]\fP"

.PP
Définition à la ligne 22 du fichier UIComponent\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBconst\fP \fBstd::string\fP & UIComponent::getFontName () const"

.PP
Définition à la ligne 32 du fichier UIComponent\&.cpp\&.
.SS "unsigned \fBint\fP UIComponent::getFontSize () const"

.PP
Définition à la ligne 37 du fichier UIComponent\&.cpp\&.
.SS "\fBconst\fP \fBstd::string\fP & UIComponent::getText () const"

.PP
Définition à la ligne 27 du fichier UIComponent\&.cpp\&.
.SS "\fBvoid\fP UIComponent::setFontName (\fBconst\fP \fBstd::string\fP & fontName)"

.PP
Définition à la ligne 47 du fichier UIComponent\&.cpp\&.
.SS "\fBvoid\fP UIComponent::setFontSize (unsigned \fBint\fP fontSize)"

.PP
Définition à la ligne 52 du fichier UIComponent\&.cpp\&.
.SS "\fBvoid\fP UIComponent::setText (\fBconst\fP \fBstd::string\fP & text)"

.PP
Définition à la ligne 42 du fichier UIComponent\&.cpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
