.TH "UIComponent" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UIComponent\&.hpp>\fP
.PP
Est dérivée de \fBAComponent\fP\&.
.PP
Dérivée par \fBUIAdvanceComponent\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBUIComponent\fP (\fBVector2\fP< double > \fBconst\fP &pos, enum \fBComponentColor\fP \fBcolor\fP, \fBVector2\fP< double > \fBconst\fP &\fBdim\fP, \fBstd::string\fP \fBconst\fP &)"
.br
.ti -1c
.RI "virtual \fB~UIComponent\fP ()"
.br
.ti -1c
.RI "\fBVector2\fP< double > \fBconst\fP & \fBgetDim\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBstd::string\fP \fBconst\fP & \fBgetText\fP () \fBconst\fP "
.br
.ti -1c
.RI "\fBvoid\fP \fBsetText\fP (\fBconst\fP \fBstd::string\fP &\fBtext\fP)"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "\fBVector2\fP< double > \fBdim\fP"
.br
.ti -1c
.RI "\fBstd::string\fP \fBtext\fP"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 10 du fichier UIComponent\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "UIComponent::UIComponent (\fBVector2\fP< double > \fBconst\fP & pos, enum \fBComponentColor\fP color, \fBVector2\fP< double > \fBconst\fP & dim, \fBstd::string\fP \fBconst\fP &)"

.PP
Définition à la ligne 14 du fichier UIComponent\&.cpp\&.
.SS "UIComponent::~UIComponent ()\fC [virtual]\fP"

.PP
Définition à la ligne 20 du fichier UIComponent\&.cpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "\fBVector2\fP< double > \fBconst\fP & UIComponent::getDim () const"

.PP
Définition à la ligne 30 du fichier UIComponent\&.cpp\&.
.SS "\fBstd::string\fP \fBconst\fP & UIComponent::getText () const"

.PP
Définition à la ligne 25 du fichier UIComponent\&.cpp\&.
.SS "\fBvoid\fP UIComponent::setText (\fBconst\fP \fBstd::string\fP & text)"

.PP
Définition à la ligne 35 du fichier UIComponent\&.cpp\&.
.SH "Documentation des données membres"
.PP 
.SS "\fBVector2\fP<double> UIComponent::dim\fC [protected]\fP"

.PP
Définition à la ligne 13 du fichier UIComponent\&.hpp\&.
.SS "\fBstd::string\fP UIComponent::text\fC [protected]\fP"

.PP
Définition à la ligne 14 du fichier UIComponent\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
