.TH "/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/unctrl.h" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/library/ncurses/include/unctrl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses/curses\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNCURSES_VERSION\fP   '6\&.0'"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBNCURSES_EXPORT\fP (\fBNCURSES_CONST\fP char *) unctrl(\fBchtype\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBchtype\fP"
.br
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define NCURSES_VERSION   '6\&.0'"

.PP
Définition à la ligne 48 du fichier unctrl\&.h\&.
.SH "Documentation des fonctions"
.PP 
.SS "NCURSES_EXPORT (\fBNCURSES_CONST\fP char *)"

.SH "Documentation des variables"
.PP 
.SS "\fBchtype\fP"

.PP
Définition à la ligne 60 du fichier unctrl\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
