.TH "UserDefinedFieldType" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserDefinedFieldType \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursesf\&.h>\fP
.PP
Est dérivée de \fBNCursesFieldType\fP\&.
.PP
Dérivée par \fBUserDefinedFieldType_With_Choice\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBUserDefinedFieldType\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBNCursesFormField\fP &\fBf\fP)"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBfield_check\fP (\fBNCursesFormField\fP &\fBf\fP)=0"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBchar_check\fP (\fBint\fP \fBc\fP)=0"
.br
.in -1c
.SS "Amis"

.in +1c
.ti -1c
.RI "class \fBUDF_Init\fP"
.br
.ti -1c
.RI "\fBbool\fP \fB_nc_xx_fld_fcheck\fP (\fBFIELD\fP *, \fBconst\fP \fBvoid\fP *)"
.br
.ti -1c
.RI "\fBbool\fP \fB_nc_xx_fld_ccheck\fP (\fBint\fP \fBc\fP, \fBconst\fP \fBvoid\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP * \fB_nc_xx_fld_makearg\fP (\fBva_list\fP *)"
.br
.in -1c
.SS "Membres hérités additionnels"
.SH "Description détaillée"
.PP 
Définition à la ligne 898 du fichier cursesf\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "UserDefinedFieldType::UserDefinedFieldType ()\fC [inline]\fP"

.PP
Définition à la ligne 927 du fichier cursesf\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "virtual \fBbool\fP UserDefinedFieldType::char_check (\fBint\fP c)\fC [protected]\fP, \fC [pure virtual]\fP"

.SS "virtual \fBbool\fP UserDefinedFieldType::field_check (\fBNCursesFormField\fP & f)\fC [protected]\fP, \fC [pure virtual]\fP"

.SS "\fBvoid\fP UserDefinedFieldType::set (\fBNCursesFormField\fP & f)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implémente \fBNCursesFieldType\fP\&.
.PP
Définition à la ligne 913 du fichier cursesf\&.h\&.
.SH "Documentation des fonctions amies et associées"
.PP 
.SS "\fBbool\fP _nc_xx_fld_ccheck (\fBint\fP c, \fBconst\fP \fBvoid\fP *)\fC [friend]\fP"

.SS "\fBbool\fP _nc_xx_fld_fcheck (\fBFIELD\fP *, \fBconst\fP \fBvoid\fP *)\fC [friend]\fP"

.SS "\fBvoid\fP* _nc_xx_fld_makearg (\fBva_list\fP *)\fC [friend]\fP"

.SS "friend class UDF_Init\fC [friend]\fP"

.PP
Définition à la ligne 900 du fichier cursesf\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
