.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/Vector2.hpp" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/Vector2.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVector2< T >\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "template<class T > std::ostream & \fBoperator<<\fP (std::ostream &\fBstream\fP, \fBVector2\fP< T > \fBconst\fP &\fBv\fP)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "template<class T > std::ostream& operator<< (std::ostream & stream, \fBVector2\fP< T > \fBconst\fP & v)"

.PP
Définition à la ligne 40 du fichier Vector2\&.hpp\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
