.TH "Vector2< T >" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector2< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vector2\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBVector2\fP (T \fBx\fP, T \fBy\fP)"
.br
.ti -1c
.RI "\fBVector2\fP ()"
.br
.ti -1c
.RI "\fB~Vector2\fP ()"
.br
.ti -1c
.RI "\fBVector2\fP \fBoperator+\fP (\fBVector2\fP \fBconst\fP &vector2)"
.br
.ti -1c
.RI "\fBVector2\fP \fBoperator\-\fP (\fBVector2\fP \fBconst\fP &vector2)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBVector2\fP \fBconst\fP &vector2) \fBconst\fP "
.br
.ti -1c
.RI "\fBVector2\fP \fBinvert\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBisEqual\fP (\fBVector2\fP< T > \fBconst\fP &other, double delta) \fBconst\fP "
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.ti -1c
.RI "T \fBy\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 

.SS "template<class T>class Vector2< T >"

.PP
Définition à la ligne 8 du fichier Vector2\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "template<class T> \fBVector2\fP< T >::\fBVector2\fP (T x, T y)\fC [inline]\fP"

.PP
Définition à la ligne 13 du fichier Vector2\&.hpp\&.
.SS "template<class T> \fBVector2\fP< T >::\fBVector2\fP ()\fC [inline]\fP"

.PP
Définition à la ligne 14 du fichier Vector2\&.hpp\&.
.SS "template<class T> \fBVector2\fP< T >::~\fBVector2\fP ()\fC [inline]\fP"

.PP
Définition à la ligne 15 du fichier Vector2\&.hpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "template<class T> \fBVector2\fP \fBVector2\fP< T >::\fBinvert\fP ()\fC [inline]\fP"

.PP
Définition à la ligne 28 du fichier Vector2\&.hpp\&.
.SS "template<class T> \fBbool\fP \fBVector2\fP< T >::isEqual (\fBVector2\fP< T > \fBconst\fP & other, double delta) const\fC [inline]\fP"

.PP
Définition à la ligne 32 du fichier Vector2\&.hpp\&.
.SS "template<class T> \fBVector2\fP \fBVector2\fP< T >::operator+ (\fBVector2\fP< T > \fBconst\fP & vector2)\fC [inline]\fP"

.PP
Définition à la ligne 16 du fichier Vector2\&.hpp\&.
.SS "template<class T> \fBVector2\fP \fBVector2\fP< T >::operator\- (\fBVector2\fP< T > \fBconst\fP & vector2)\fC [inline]\fP"

.PP
Définition à la ligne 20 du fichier Vector2\&.hpp\&.
.SS "template<class T> \fBbool\fP \fBVector2\fP< T >::operator== (\fBVector2\fP< T > \fBconst\fP & vector2) const\fC [inline]\fP"

.PP
Définition à la ligne 24 du fichier Vector2\&.hpp\&.
.SH "Documentation des données membres"
.PP 
.SS "template<class T> T \fBVector2\fP< T >::\fBx\fP"

.PP
Définition à la ligne 10 du fichier Vector2\&.hpp\&.
.SS "template<class T> T \fBVector2\fP< T >::\fBy\fP"

.PP
Définition à la ligne 11 du fichier Vector2\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
