.TH "Vector2< T >" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector2< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vector2\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBVector2\fP (T \fBx\fP, T \fBy\fP)"
.br
.ti -1c
.RI "\fBVector2\fP (\fBconst\fP \fBVector2\fP< T > &\fBobj\fP)"
.br
.ti -1c
.RI "\fB~Vector2\fP ()"
.br
.ti -1c
.RI "\fBVector2\fP< T > & \fBoperator=\fP (\fBconst\fP \fBVector2\fP< T > &vec)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBVector2\fP< T > &vec) \fBconst\fP "
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.ti -1c
.RI "T \fBy\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 

.SS "template<class T>class Vector2< T >"

.PP
Définition à la ligne 17 du fichier Vector2\&.hpp\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "template<class T> \fBVector2\fP< T >::\fBVector2\fP (T x, T y)\fC [inline]\fP"

.PP
Définition à la ligne 22 du fichier Vector2\&.hpp\&.
.SS "template<class T> \fBVector2\fP< T >::\fBVector2\fP (\fBconst\fP \fBVector2\fP< T > & obj)\fC [inline]\fP"

.PP
Définition à la ligne 29 du fichier Vector2\&.hpp\&.
.SS "template<class T> \fBVector2\fP< T >::~\fBVector2\fP ()\fC [inline]\fP"

.PP
Définition à la ligne 34 du fichier Vector2\&.hpp\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "template<class T> \fBVector2\fP<T>& \fBVector2\fP< T >::operator= (\fBconst\fP \fBVector2\fP< T > & vec)\fC [inline]\fP"

.PP
Définition à la ligne 37 du fichier Vector2\&.hpp\&.
.SS "template<class T> \fBbool\fP \fBVector2\fP< T >::operator== (\fBconst\fP \fBVector2\fP< T > & vec) const\fC [inline]\fP"

.PP
Définition à la ligne 44 du fichier Vector2\&.hpp\&.
.SH "Documentation des données membres"
.PP 
.SS "template<class T> T \fBVector2\fP< T >::\fBx\fP"

.PP
Définition à la ligne 19 du fichier Vector2\&.hpp\&.
.SS "template<class T> T \fBVector2\fP< T >::\fBy\fP"

.PP
Définition à la ligne 20 du fichier Vector2\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
