.TH "/home/wery_a/rendu/CPP/cpp_arcade/inc/lib/ncurses/Window.hpp" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/wery_a/rendu/CPP/cpp_arcade/inc/lib/ncurses/Window.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ncurses\&.h'\fP
.br
\fC#include 'Vector2\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBncurses::Window\fP"
.br
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBncurses\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
