.TH "xGLXHyperpipeConfigSGIXReq" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXHyperpipeConfigSGIXReq \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "CARD8 \fBreqType\fP"
.br
.ti -1c
.RI "CARD8 \fBglxCode\fP"
.br
.ti -1c
.RI "CARD16 \fBlength\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 vendorCode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 screen \fBB32\fP"
.br
.ti -1c
.RI "CARD32 npipes \fBB32\fP"
.br
.ti -1c
.RI "CARD32 networkId \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1259 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 \fBlength\fP xGLXHyperpipeConfigSGIXReq::B16"

.PP
Définition à la ligne 1262 du fichier glxproto\&.h\&.
.SS "CARD32 vendorCode xGLXHyperpipeConfigSGIXReq::B32"

.PP
Définition à la ligne 1263 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXHyperpipeConfigSGIXReq::B32"

.PP
Définition à la ligne 1264 du fichier glxproto\&.h\&.
.SS "CARD32 screen xGLXHyperpipeConfigSGIXReq::B32"

.PP
Définition à la ligne 1265 du fichier glxproto\&.h\&.
.SS "CARD32 npipes xGLXHyperpipeConfigSGIXReq::B32"

.PP
Définition à la ligne 1266 du fichier glxproto\&.h\&.
.SS "CARD32 networkId xGLXHyperpipeConfigSGIXReq::B32"

.PP
Définition à la ligne 1267 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXHyperpipeConfigSGIXReq::B32"

.PP
Définition à la ligne 1268 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXHyperpipeConfigSGIXReq::B32"

.PP
Définition à la ligne 1269 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXHyperpipeConfigSGIXReq::glxCode"

.PP
Définition à la ligne 1261 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXHyperpipeConfigSGIXReq::reqType"

.PP
Définition à la ligne 1260 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
