.TH "xGLXHyperpipeConfigSGIXReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXHyperpipeConfigSGIXReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBn\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 npipes \fBB32\fP"
.br
.ti -1c
.RI "CARD32 hpId \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1277 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXHyperpipeConfigSGIXReply::B16"

.PP
Définition à la ligne 1280 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1281 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1282 du fichier glxproto\&.h\&.
.SS "CARD32 \fBn\fP xGLXHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1283 du fichier glxproto\&.h\&.
.SS "CARD32 npipes xGLXHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1284 du fichier glxproto\&.h\&.
.SS "CARD32 hpId xGLXHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1285 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1286 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1287 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXHyperpipeConfigSGIXReply::type"

.PP
Définition à la ligne 1278 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXHyperpipeConfigSGIXReply::unused"

.PP
Définition à la ligne 1279 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
