.TH "xGLXIsDirectReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXIsDirectReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "\fBBOOL\fP \fBisDirect\fP"
.br
.ti -1c
.RI "CARD8 \fBpad1\fP"
.br
.ti -1c
.RI "CARD16 pad2 \fBB16\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad7 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 716 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXIsDirectReply::B16"

.PP
Définition à la ligne 719 du fichier glxproto\&.h\&.
.SS "CARD16 pad2 xGLXIsDirectReply::B16"

.PP
Définition à la ligne 723 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXIsDirectReply::B32"

.PP
Définition à la ligne 720 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXIsDirectReply::B32"

.PP
Définition à la ligne 724 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXIsDirectReply::B32"

.PP
Définition à la ligne 725 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXIsDirectReply::B32"

.PP
Définition à la ligne 726 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXIsDirectReply::B32"

.PP
Définition à la ligne 727 du fichier glxproto\&.h\&.
.SS "CARD32 pad7 xGLXIsDirectReply::B32"

.PP
Définition à la ligne 728 du fichier glxproto\&.h\&.
.SS "\fBBOOL\fP xGLXIsDirectReply::isDirect"

.PP
Définition à la ligne 721 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXIsDirectReply::pad1"

.PP
Définition à la ligne 722 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXIsDirectReply::type"

.PP
Définition à la ligne 717 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXIsDirectReply::unused"

.PP
Définition à la ligne 718 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
