.TH "xGLXGetVisualConfigsReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetVisualConfigsReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numVisuals \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numProps \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 702 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetVisualConfigsReply::B16"

.PP
Définition à la ligne 705 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetVisualConfigsReply::B32"

.PP
Définition à la ligne 706 du fichier glxproto\&.h\&.
.SS "CARD32 numVisuals xGLXGetVisualConfigsReply::B32"

.PP
Définition à la ligne 707 du fichier glxproto\&.h\&.
.SS "CARD32 numProps xGLXGetVisualConfigsReply::B32"

.PP
Définition à la ligne 708 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXGetVisualConfigsReply::B32"

.PP
Définition à la ligne 709 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXGetVisualConfigsReply::B32"

.PP
Définition à la ligne 710 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetVisualConfigsReply::B32"

.PP
Définition à la ligne 711 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetVisualConfigsReply::B32"

.PP
Définition à la ligne 712 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetVisualConfigsReply::type"

.PP
Définition à la ligne 703 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetVisualConfigsReply::unused"

.PP
Définition à la ligne 704 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
