.TH "xGLXQueryServerStringReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXQueryServerStringReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBn\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 793 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXQueryServerStringReply::B16"

.PP
Définition à la ligne 796 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXQueryServerStringReply::B32"

.PP
Définition à la ligne 797 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXQueryServerStringReply::B32"

.PP
Définition à la ligne 798 du fichier glxproto\&.h\&.
.SS "CARD32 \fBn\fP xGLXQueryServerStringReply::B32"

.PP
Définition à la ligne 799 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXQueryServerStringReply::B32"

.PP
Définition à la ligne 800 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXQueryServerStringReply::B32"

.PP
Définition à la ligne 801 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXQueryServerStringReply::B32"

.PP
Définition à la ligne 802 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXQueryServerStringReply::B32"

.PP
Définition à la ligne 803 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXQueryServerStringReply::type"

.PP
Définition à la ligne 794 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXQueryServerStringReply::unused"

.PP
Définition à la ligne 795 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
