.TH "xGLXQueryHyperpipeConfigSGIXReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXQueryHyperpipeConfigSGIXReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBn\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 npipes \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1242 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXQueryHyperpipeConfigSGIXReply::B16"

.PP
Définition à la ligne 1245 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXQueryHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1246 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXQueryHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1247 du fichier glxproto\&.h\&.
.SS "CARD32 \fBn\fP xGLXQueryHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1248 du fichier glxproto\&.h\&.
.SS "CARD32 npipes xGLXQueryHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1249 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXQueryHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1250 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXQueryHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1251 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXQueryHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1252 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXQueryHyperpipeConfigSGIXReply::type"

.PP
Définition à la ligne 1243 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXQueryHyperpipeConfigSGIXReply::unused"

.PP
Définition à la ligne 1244 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
