.TH "xGLXRenderModeReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXRenderModeReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 retval \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBsize\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 newMode \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 674 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXRenderModeReply::B16"

.PP
Définition à la ligne 677 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXRenderModeReply::B32"

.PP
Définition à la ligne 678 du fichier glxproto\&.h\&.
.SS "CARD32 retval xGLXRenderModeReply::B32"

.PP
Définition à la ligne 679 du fichier glxproto\&.h\&.
.SS "CARD32 \fBsize\fP xGLXRenderModeReply::B32"

.PP
Définition à la ligne 680 du fichier glxproto\&.h\&.
.SS "CARD32 newMode xGLXRenderModeReply::B32"

.PP
Définition à la ligne 681 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXRenderModeReply::B32"

.PP
Définition à la ligne 682 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXRenderModeReply::B32"

.PP
Définition à la ligne 683 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXRenderModeReply::B32"

.PP
Définition à la ligne 684 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXRenderModeReply::type"

.PP
Définition à la ligne 675 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXRenderModeReply::unused"

.PP
Définition à la ligne 676 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
