.TH "xGLXGetFBConfigsReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetFBConfigsReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numFBConfigs \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numAttribs \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 812 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetFBConfigsReply::B16"

.PP
Définition à la ligne 815 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetFBConfigsReply::B32"

.PP
Définition à la ligne 816 du fichier glxproto\&.h\&.
.SS "CARD32 numFBConfigs xGLXGetFBConfigsReply::B32"

.PP
Définition à la ligne 817 du fichier glxproto\&.h\&.
.SS "CARD32 numAttribs xGLXGetFBConfigsReply::B32"

.PP
Définition à la ligne 818 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXGetFBConfigsReply::B32"

.PP
Définition à la ligne 819 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXGetFBConfigsReply::B32"

.PP
Définition à la ligne 820 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetFBConfigsReply::B32"

.PP
Définition à la ligne 821 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetFBConfigsReply::B32"

.PP
Définition à la ligne 822 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetFBConfigsReply::type"

.PP
Définition à la ligne 813 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetFBConfigsReply::unused"

.PP
Définition à la ligne 814 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
