.TH "xGLXGetMinmaxReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetMinmaxReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 660 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetMinmaxReply::B16"

.PP
Définition à la ligne 663 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetMinmaxReply::B32"

.PP
Définition à la ligne 664 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXGetMinmaxReply::B32"

.PP
Définition à la ligne 665 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXGetMinmaxReply::B32"

.PP
Définition à la ligne 666 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXGetMinmaxReply::B32"

.PP
Définition à la ligne 667 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXGetMinmaxReply::B32"

.PP
Définition à la ligne 668 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetMinmaxReply::B32"

.PP
Définition à la ligne 669 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetMinmaxReply::B32"

.PP
Définition à la ligne 670 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetMinmaxReply::type"

.PP
Définition à la ligne 661 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetMinmaxReply::unused"

.PP
Définition à la ligne 662 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
