.TH "xGLXGetConvolutionFilterReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetConvolutionFilterReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBwidth\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBheight\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 632 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetConvolutionFilterReply::B16"

.PP
Définition à la ligne 635 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetConvolutionFilterReply::B32"

.PP
Définition à la ligne 636 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXGetConvolutionFilterReply::B32"

.PP
Définition à la ligne 637 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXGetConvolutionFilterReply::B32"

.PP
Définition à la ligne 638 du fichier glxproto\&.h\&.
.SS "CARD32 \fBwidth\fP xGLXGetConvolutionFilterReply::B32"

.PP
Définition à la ligne 639 du fichier glxproto\&.h\&.
.SS "CARD32 \fBheight\fP xGLXGetConvolutionFilterReply::B32"

.PP
Définition à la ligne 640 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetConvolutionFilterReply::B32"

.PP
Définition à la ligne 641 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetConvolutionFilterReply::B32"

.PP
Définition à la ligne 642 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetConvolutionFilterReply::type"

.PP
Définition à la ligne 633 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetConvolutionFilterReply::unused"

.PP
Définition à la ligne 634 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
