.TH "xGLXMakeCurrentReadSGIReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXMakeCurrentReadSGIReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.ti -1c
.RI "CARD32 writeVid \fBB32\fP"
.br
.ti -1c
.RI "CARD32 writeType \fBB32\fP"
.br
.ti -1c
.RI "CARD32 readVid \fBB32\fP"
.br
.ti -1c
.RI "CARD32 readType \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 962 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXMakeCurrentReadSGIReply::B16"

.PP
Définition à la ligne 965 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXMakeCurrentReadSGIReply::B32"

.PP
Définition à la ligne 966 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag xGLXMakeCurrentReadSGIReply::B32"

.PP
Définition à la ligne 967 du fichier glxproto\&.h\&.
.SS "CARD32 writeVid xGLXMakeCurrentReadSGIReply::B32"

.PP
Définition à la ligne 968 du fichier glxproto\&.h\&.
.SS "CARD32 writeType xGLXMakeCurrentReadSGIReply::B32"

.PP
Définition à la ligne 969 du fichier glxproto\&.h\&.
.SS "CARD32 readVid xGLXMakeCurrentReadSGIReply::B32"

.PP
Définition à la ligne 970 du fichier glxproto\&.h\&.
.SS "CARD32 readType xGLXMakeCurrentReadSGIReply::B32"

.PP
Définition à la ligne 971 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXMakeCurrentReadSGIReply::B32"

.PP
Définition à la ligne 972 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXMakeCurrentReadSGIReply::type"

.PP
Définition à la ligne 963 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXMakeCurrentReadSGIReply::unused"

.PP
Définition à la ligne 964 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
