.TH "xGLXQueryHyperpipeNetworkSGIXReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXQueryHyperpipeNetworkSGIXReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBn\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 npipes \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1174 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXQueryHyperpipeNetworkSGIXReply::B16"

.PP
Définition à la ligne 1177 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXQueryHyperpipeNetworkSGIXReply::B32"

.PP
Définition à la ligne 1178 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXQueryHyperpipeNetworkSGIXReply::B32"

.PP
Définition à la ligne 1179 du fichier glxproto\&.h\&.
.SS "CARD32 \fBn\fP xGLXQueryHyperpipeNetworkSGIXReply::B32"

.PP
Définition à la ligne 1180 du fichier glxproto\&.h\&.
.SS "CARD32 npipes xGLXQueryHyperpipeNetworkSGIXReply::B32"

.PP
Définition à la ligne 1181 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXQueryHyperpipeNetworkSGIXReply::B32"

.PP
Définition à la ligne 1182 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXQueryHyperpipeNetworkSGIXReply::B32"

.PP
Définition à la ligne 1183 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXQueryHyperpipeNetworkSGIXReply::B32"

.PP
Définition à la ligne 1184 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXQueryHyperpipeNetworkSGIXReply::type"

.PP
Définition à la ligne 1175 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXQueryHyperpipeNetworkSGIXReply::unused"

.PP
Définition à la ligne 1176 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
