.TH "xGLXQueryExtensionsStringReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXQueryExtensionsStringReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBn\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 775 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXQueryExtensionsStringReply::B16"

.PP
Définition à la ligne 778 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXQueryExtensionsStringReply::B32"

.PP
Définition à la ligne 779 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXQueryExtensionsStringReply::B32"

.PP
Définition à la ligne 780 du fichier glxproto\&.h\&.
.SS "CARD32 \fBn\fP xGLXQueryExtensionsStringReply::B32"

.PP
Définition à la ligne 781 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXQueryExtensionsStringReply::B32"

.PP
Définition à la ligne 782 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXQueryExtensionsStringReply::B32"

.PP
Définition à la ligne 783 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXQueryExtensionsStringReply::B32"

.PP
Définition à la ligne 784 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXQueryExtensionsStringReply::B32"

.PP
Définition à la ligne 785 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXQueryExtensionsStringReply::type"

.PP
Définition à la ligne 776 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXQueryExtensionsStringReply::unused"

.PP
Définition à la ligne 777 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
