.TH "xGLXGetColorTableReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetColorTableReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBwidth\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 899 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetColorTableReply::B16"

.PP
Définition à la ligne 902 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetColorTableReply::B32"

.PP
Définition à la ligne 903 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXGetColorTableReply::B32"

.PP
Définition à la ligne 904 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXGetColorTableReply::B32"

.PP
Définition à la ligne 905 du fichier glxproto\&.h\&.
.SS "CARD32 \fBwidth\fP xGLXGetColorTableReply::B32"

.PP
Définition à la ligne 906 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXGetColorTableReply::B32"

.PP
Définition à la ligne 907 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetColorTableReply::B32"

.PP
Définition à la ligne 908 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetColorTableReply::B32"

.PP
Définition à la ligne 909 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetColorTableReply::type"

.PP
Définition à la ligne 900 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetColorTableReply::unused"

.PP
Définition à la ligne 901 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
