.TH "xGLXGetHistogramReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetHistogramReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBwidth\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 646 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetHistogramReply::B16"

.PP
Définition à la ligne 649 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetHistogramReply::B32"

.PP
Définition à la ligne 650 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXGetHistogramReply::B32"

.PP
Définition à la ligne 651 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXGetHistogramReply::B32"

.PP
Définition à la ligne 652 du fichier glxproto\&.h\&.
.SS "CARD32 \fBwidth\fP xGLXGetHistogramReply::B32"

.PP
Définition à la ligne 653 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXGetHistogramReply::B32"

.PP
Définition à la ligne 654 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetHistogramReply::B32"

.PP
Définition à la ligne 655 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetHistogramReply::B32"

.PP
Définition à la ligne 656 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetHistogramReply::type"

.PP
Définition à la ligne 647 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetHistogramReply::unused"

.PP
Définition à la ligne 648 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
