.TH "xGLXVendorPrivReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXVendorPrivReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 retval \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBsize\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 757 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXVendorPrivReply::B16"

.PP
Définition à la ligne 760 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXVendorPrivReply::B32"

.PP
Définition à la ligne 761 du fichier glxproto\&.h\&.
.SS "CARD32 retval xGLXVendorPrivReply::B32"

.PP
Définition à la ligne 762 du fichier glxproto\&.h\&.
.SS "CARD32 \fBsize\fP xGLXVendorPrivReply::B32"

.PP
Définition à la ligne 763 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXVendorPrivReply::B32"

.PP
Définition à la ligne 764 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXVendorPrivReply::B32"

.PP
Définition à la ligne 765 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXVendorPrivReply::B32"

.PP
Définition à la ligne 766 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXVendorPrivReply::B32"

.PP
Définition à la ligne 767 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXVendorPrivReply::type"

.PP
Définition à la ligne 758 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXVendorPrivReply::unused"

.PP
Définition à la ligne 759 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
