.TH "xGLXPbufferClobberEvent" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXPbufferClobberEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBpad\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD16 event_type \fBB16\fP"
.br
.ti -1c
.RI "CARD16 draw_type \fBB16\fP"
.br
.ti -1c
.RI "CARD32 drawable \fBB32\fP"
.br
.ti -1c
.RI "CARD32 buffer_mask \fBB32\fP"
.br
.ti -1c
.RI "CARD16 aux_buffer \fBB16\fP"
.br
.ti -1c
.RI "CARD16 \fBx\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD16 \fBy\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD16 \fBwidth\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD16 \fBheight\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD16 \fBcount\fP \fBB16\fP"
.br
.ti -1c
.RI "CARD32 unused2 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1389 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXPbufferClobberEvent::B16"

.PP
Définition à la ligne 1392 du fichier glxproto\&.h\&.
.SS "CARD16 event_type xGLXPbufferClobberEvent::B16"

.PP
Définition à la ligne 1393 du fichier glxproto\&.h\&.
.SS "CARD16 draw_type xGLXPbufferClobberEvent::B16"

.PP
Définition à la ligne 1394 du fichier glxproto\&.h\&.
.SS "CARD16 aux_buffer xGLXPbufferClobberEvent::B16"

.PP
Définition à la ligne 1397 du fichier glxproto\&.h\&.
.SS "CARD16 \fBx\fP xGLXPbufferClobberEvent::B16"

.PP
Définition à la ligne 1398 du fichier glxproto\&.h\&.
.SS "CARD16 \fBy\fP xGLXPbufferClobberEvent::B16"

.PP
Définition à la ligne 1399 du fichier glxproto\&.h\&.
.SS "CARD16 \fBwidth\fP xGLXPbufferClobberEvent::B16"

.PP
Définition à la ligne 1400 du fichier glxproto\&.h\&.
.SS "CARD16 \fBheight\fP xGLXPbufferClobberEvent::B16"

.PP
Définition à la ligne 1401 du fichier glxproto\&.h\&.
.SS "CARD16 \fBcount\fP xGLXPbufferClobberEvent::B16"

.PP
Définition à la ligne 1402 du fichier glxproto\&.h\&.
.SS "CARD32 drawable xGLXPbufferClobberEvent::B32"

.PP
Définition à la ligne 1395 du fichier glxproto\&.h\&.
.SS "CARD32 buffer_mask xGLXPbufferClobberEvent::B32"

.PP
Définition à la ligne 1396 du fichier glxproto\&.h\&.
.SS "CARD32 unused2 xGLXPbufferClobberEvent::B32"

.PP
Définition à la ligne 1403 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXPbufferClobberEvent::pad"

.PP
Définition à la ligne 1391 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXPbufferClobberEvent::type"

.PP
Définition à la ligne 1390 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
