.TH "xGLXMakeContextCurrentReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXMakeContextCurrentReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 846 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXMakeContextCurrentReply::B16"

.PP
Définition à la ligne 849 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXMakeContextCurrentReply::B32"

.PP
Définition à la ligne 850 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag xGLXMakeContextCurrentReply::B32"

.PP
Définition à la ligne 851 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXMakeContextCurrentReply::B32"

.PP
Définition à la ligne 852 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXMakeContextCurrentReply::B32"

.PP
Définition à la ligne 853 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXMakeContextCurrentReply::B32"

.PP
Définition à la ligne 854 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXMakeContextCurrentReply::B32"

.PP
Définition à la ligne 855 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXMakeContextCurrentReply::B32"

.PP
Définition à la ligne 856 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXMakeContextCurrentReply::type"

.PP
Définition à la ligne 847 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXMakeContextCurrentReply::unused"

.PP
Définition à la ligne 848 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
