.TH "xGLXGetTexImageReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetTexImageReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBwidth\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBheight\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBdepth\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 604 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetTexImageReply::B16"

.PP
Définition à la ligne 607 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetTexImageReply::B32"

.PP
Définition à la ligne 608 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXGetTexImageReply::B32"

.PP
Définition à la ligne 609 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXGetTexImageReply::B32"

.PP
Définition à la ligne 610 du fichier glxproto\&.h\&.
.SS "CARD32 \fBwidth\fP xGLXGetTexImageReply::B32"

.PP
Définition à la ligne 611 du fichier glxproto\&.h\&.
.SS "CARD32 \fBheight\fP xGLXGetTexImageReply::B32"

.PP
Définition à la ligne 612 du fichier glxproto\&.h\&.
.SS "CARD32 \fBdepth\fP xGLXGetTexImageReply::B32"

.PP
Définition à la ligne 613 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetTexImageReply::B32"

.PP
Définition à la ligne 614 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetTexImageReply::type"

.PP
Définition à la ligne 605 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetTexImageReply::unused"

.PP
Définition à la ligne 606 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
