.TH "xGLXDestroyHyperpipeConfigSGIXReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXDestroyHyperpipeConfigSGIXReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBn\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 success \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1208 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXDestroyHyperpipeConfigSGIXReply::B16"

.PP
Définition à la ligne 1211 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXDestroyHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1212 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXDestroyHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1213 du fichier glxproto\&.h\&.
.SS "CARD32 \fBn\fP xGLXDestroyHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1214 du fichier glxproto\&.h\&.
.SS "CARD32 success xGLXDestroyHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1215 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXDestroyHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1216 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXDestroyHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1217 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXDestroyHyperpipeConfigSGIXReply::B32"

.PP
Définition à la ligne 1218 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXDestroyHyperpipeConfigSGIXReply::type"

.PP
Définition à la ligne 1209 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXDestroyHyperpipeConfigSGIXReply::unused"

.PP
Définition à la ligne 1210 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
