.TH "xGLXGetDrawableAttributesReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetDrawableAttributesReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numAttribs \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 882 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetDrawableAttributesReply::B16"

.PP
Définition à la ligne 885 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetDrawableAttributesReply::B32"

.PP
Définition à la ligne 886 du fichier glxproto\&.h\&.
.SS "CARD32 numAttribs xGLXGetDrawableAttributesReply::B32"

.PP
Définition à la ligne 887 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXGetDrawableAttributesReply::B32"

.PP
Définition à la ligne 888 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXGetDrawableAttributesReply::B32"

.PP
Définition à la ligne 889 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXGetDrawableAttributesReply::B32"

.PP
Définition à la ligne 890 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetDrawableAttributesReply::B32"

.PP
Définition à la ligne 891 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetDrawableAttributesReply::B32"

.PP
Définition à la ligne 892 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetDrawableAttributesReply::type"

.PP
Définition à la ligne 883 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetDrawableAttributesReply::unused"

.PP
Définition à la ligne 884 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
