.TH "xGLXGetDrawableAttributesSGIXReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetDrawableAttributesSGIXReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 numAttribs \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1089 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetDrawableAttributesSGIXReply::B16"

.PP
Définition à la ligne 1092 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetDrawableAttributesSGIXReply::B32"

.PP
Définition à la ligne 1093 du fichier glxproto\&.h\&.
.SS "CARD32 numAttribs xGLXGetDrawableAttributesSGIXReply::B32"

.PP
Définition à la ligne 1094 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXGetDrawableAttributesSGIXReply::B32"

.PP
Définition à la ligne 1095 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXGetDrawableAttributesSGIXReply::B32"

.PP
Définition à la ligne 1096 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXGetDrawableAttributesSGIXReply::B32"

.PP
Définition à la ligne 1097 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetDrawableAttributesSGIXReply::B32"

.PP
Définition à la ligne 1098 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetDrawableAttributesSGIXReply::B32"

.PP
Définition à la ligne 1099 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetDrawableAttributesSGIXReply::type"

.PP
Définition à la ligne 1090 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetDrawableAttributesSGIXReply::unused"

.PP
Définition à la ligne 1091 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
