.TH "xGLXGetErrorReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetErrorReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 error \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 562 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetErrorReply::B16"

.PP
Définition à la ligne 565 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetErrorReply::B32"

.PP
Définition à la ligne 566 du fichier glxproto\&.h\&.
.SS "CARD32 error xGLXGetErrorReply::B32"

.PP
Définition à la ligne 567 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXGetErrorReply::B32"

.PP
Définition à la ligne 568 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXGetErrorReply::B32"

.PP
Définition à la ligne 569 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXGetErrorReply::B32"

.PP
Définition à la ligne 570 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetErrorReply::B32"

.PP
Définition à la ligne 571 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetErrorReply::B32"

.PP
Définition à la ligne 572 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetErrorReply::type"

.PP
Définition à la ligne 563 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetErrorReply::unused"

.PP
Définition à la ligne 564 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
