.TH "xGLXQueryMaxSwapBarriersSGIXReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXQueryMaxSwapBarriersSGIXReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 max \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBsize\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 1144 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXQueryMaxSwapBarriersSGIXReply::B16"

.PP
Définition à la ligne 1147 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXQueryMaxSwapBarriersSGIXReply::B32"

.PP
Définition à la ligne 1148 du fichier glxproto\&.h\&.
.SS "CARD32 max xGLXQueryMaxSwapBarriersSGIXReply::B32"

.PP
Définition à la ligne 1149 du fichier glxproto\&.h\&.
.SS "CARD32 \fBsize\fP xGLXQueryMaxSwapBarriersSGIXReply::B32"

.PP
Définition à la ligne 1150 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXQueryMaxSwapBarriersSGIXReply::B32"

.PP
Définition à la ligne 1151 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXQueryMaxSwapBarriersSGIXReply::B32"

.PP
Définition à la ligne 1152 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXQueryMaxSwapBarriersSGIXReply::B32"

.PP
Définition à la ligne 1153 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXQueryMaxSwapBarriersSGIXReply::B32"

.PP
Définition à la ligne 1154 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXQueryMaxSwapBarriersSGIXReply::type"

.PP
Définition à la ligne 1145 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXQueryMaxSwapBarriersSGIXReply::unused"

.PP
Définition à la ligne 1146 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
