.TH "xGLXCreateGLXPbufferReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXCreateGLXPbufferReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBsuccess\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 865 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXCreateGLXPbufferReply::B16"

.PP
Définition à la ligne 868 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXCreateGLXPbufferReply::B32"

.PP
Définition à la ligne 869 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXCreateGLXPbufferReply::B32"

.PP
Définition à la ligne 870 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXCreateGLXPbufferReply::B32"

.PP
Définition à la ligne 871 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXCreateGLXPbufferReply::B32"

.PP
Définition à la ligne 872 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXCreateGLXPbufferReply::B32"

.PP
Définition à la ligne 873 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXCreateGLXPbufferReply::B32"

.PP
Définition à la ligne 874 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXCreateGLXPbufferReply::B32"

.PP
Définition à la ligne 875 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXCreateGLXPbufferReply::success"

.PP
Définition à la ligne 867 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXCreateGLXPbufferReply::type"

.PP
Définition à la ligne 866 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
