.TH "xGLXMakeCurrentReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXMakeCurrentReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "\fBGLXContextTag\fP contextTag \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 576 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXMakeCurrentReply::B16"

.PP
Définition à la ligne 579 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXMakeCurrentReply::B32"

.PP
Définition à la ligne 580 du fichier glxproto\&.h\&.
.SS "\fBGLXContextTag\fP contextTag xGLXMakeCurrentReply::B32"

.PP
Définition à la ligne 581 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXMakeCurrentReply::B32"

.PP
Définition à la ligne 582 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXMakeCurrentReply::B32"

.PP
Définition à la ligne 583 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXMakeCurrentReply::B32"

.PP
Définition à la ligne 584 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXMakeCurrentReply::B32"

.PP
Définition à la ligne 585 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXMakeCurrentReply::B32"

.PP
Définition à la ligne 586 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXMakeCurrentReply::type"

.PP
Définition à la ligne 577 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXMakeCurrentReply::unused"

.PP
Définition à la ligne 578 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
