.TH "xGLXGetSeparableFilterReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXGetSeparableFilterReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBwidth\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 \fBheight\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 618 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXGetSeparableFilterReply::B16"

.PP
Définition à la ligne 621 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXGetSeparableFilterReply::B32"

.PP
Définition à la ligne 622 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXGetSeparableFilterReply::B32"

.PP
Définition à la ligne 623 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXGetSeparableFilterReply::B32"

.PP
Définition à la ligne 624 du fichier glxproto\&.h\&.
.SS "CARD32 \fBwidth\fP xGLXGetSeparableFilterReply::B32"

.PP
Définition à la ligne 625 du fichier glxproto\&.h\&.
.SS "CARD32 \fBheight\fP xGLXGetSeparableFilterReply::B32"

.PP
Définition à la ligne 626 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXGetSeparableFilterReply::B32"

.PP
Définition à la ligne 627 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXGetSeparableFilterReply::B32"

.PP
Définition à la ligne 628 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXGetSeparableFilterReply::type"

.PP
Définition à la ligne 619 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXGetSeparableFilterReply::unused"

.PP
Définition à la ligne 620 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
