.TH "xGLXQueryVersionReply" 3 "Mercredi 30 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXQueryVersionReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 majorVersion \fBB32\fP"
.br
.ti -1c
.RI "CARD32 minorVersion \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 688 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXQueryVersionReply::B16"

.PP
Définition à la ligne 691 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXQueryVersionReply::B32"

.PP
Définition à la ligne 692 du fichier glxproto\&.h\&.
.SS "CARD32 majorVersion xGLXQueryVersionReply::B32"

.PP
Définition à la ligne 693 du fichier glxproto\&.h\&.
.SS "CARD32 minorVersion xGLXQueryVersionReply::B32"

.PP
Définition à la ligne 694 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXQueryVersionReply::B32"

.PP
Définition à la ligne 695 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXQueryVersionReply::B32"

.PP
Définition à la ligne 696 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXQueryVersionReply::B32"

.PP
Définition à la ligne 697 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXQueryVersionReply::B32"

.PP
Définition à la ligne 698 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXQueryVersionReply::type"

.PP
Définition à la ligne 689 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXQueryVersionReply::unused"

.PP
Définition à la ligne 690 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
