.TH "xGLXReadPixelsReply" 3 "Jeudi 31 Mars 2016" "Version 1" "Arcade" \" -*- nroff -*-
.ad l
.nh
.SH NAME
xGLXReadPixelsReply \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glxproto\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBtype\fP"
.br
.ti -1c
.RI "CARD8 \fBunused\fP"
.br
.ti -1c
.RI "CARD16 sequenceNumber \fBB16\fP"
.br
.ti -1c
.RI "CARD32 \fBlength\fP \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad1 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad2 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad3 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad4 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad5 \fBB32\fP"
.br
.ti -1c
.RI "CARD32 pad6 \fBB32\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 590 du fichier glxproto\&.h\&.
.SH "Documentation des données membres"
.PP 
.SS "CARD16 sequenceNumber xGLXReadPixelsReply::B16"

.PP
Définition à la ligne 593 du fichier glxproto\&.h\&.
.SS "CARD32 \fBlength\fP xGLXReadPixelsReply::B32"

.PP
Définition à la ligne 594 du fichier glxproto\&.h\&.
.SS "CARD32 pad1 xGLXReadPixelsReply::B32"

.PP
Définition à la ligne 595 du fichier glxproto\&.h\&.
.SS "CARD32 pad2 xGLXReadPixelsReply::B32"

.PP
Définition à la ligne 596 du fichier glxproto\&.h\&.
.SS "CARD32 pad3 xGLXReadPixelsReply::B32"

.PP
Définition à la ligne 597 du fichier glxproto\&.h\&.
.SS "CARD32 pad4 xGLXReadPixelsReply::B32"

.PP
Définition à la ligne 598 du fichier glxproto\&.h\&.
.SS "CARD32 pad5 xGLXReadPixelsReply::B32"

.PP
Définition à la ligne 599 du fichier glxproto\&.h\&.
.SS "CARD32 pad6 xGLXReadPixelsReply::B32"

.PP
Définition à la ligne 600 du fichier glxproto\&.h\&.
.SS "\fBBYTE\fP xGLXReadPixelsReply::type"

.PP
Définition à la ligne 591 du fichier glxproto\&.h\&.
.SS "CARD8 xGLXReadPixelsReply::unused"

.PP
Définition à la ligne 592 du fichier glxproto\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Arcade à partir du code source\&.
